### ISSUE TITLE
Fix all View.propTypes deprecated warning

### ISSUE THREAD

**Issue by anhtuank7c** [wix/react-native-ui-lib#10]
Please use `ViewPropTypes` instead of `View.propTypes`

![screen shot 2017-06-08 at 4 11 42 pm](https://user-images.githubusercontent.com/3163410/26921099-32a2531a-4c65-11e7-8df2-9d3cb839f9db.png)

Ex: https://github.com/wix/react-native-ui-lib/blob/master/src/components/card/CardSection.js#L16

**Comment by ethanshar** [comment]
Replaced everywhere I found. 
unfortunately since some of the components are using `react-native-blur` which hasn't fixed this warning yet, you will still might get them.

**Comment by anhtuank7c** [comment]
@ethanshar 
Thank you so much

**Comment by ethanshar** [comment]
Great. so it will be fixed automatically once they decided to release a new version.
