### ISSUE TITLE
V6 supports Dark/Light themes or Option to customize all colors?

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#1016]
**Which component?**

**What is the new feature?**
A clear and concise description of what the required feature

**Code snippet**
How you would have use this feature? How the API will look like?

**Comment by saravanakumargn** [comment]
1. #1014 
2. Not able to change`showCharacterCounter` in `TextField`

**Comment by ethanshar** [comment]
Hi @saravanakumargn 
Can you open a separate ticket for **2.** 
We'll support it in our new TextField implementation
