### ISSUE TITLE
we can't setState in a render flow

### ISSUE THREAD

**Issue by ethanshar** [wix/react-native-ui-lib#102]
@Inbal-Tish 
We have an issue in the following line
https://github.com/wix/react-native-ui-lib/blob/e95a864fd70237baf97ea20cb3be3e150f0109bf/src/components/inputs/TextInput.js#L193

`getHeight` is being called in a `renderTextInput` function. 
It's impossible to setState inside a render.
it also throws a warning

**Comment by Inbal-Tish** [comment]
Done.
