### ISSUE TITLE
Missed Button component from documentation site

### ISSUE THREAD

**Issue by aefimov64** [wix/react-native-ui-lib#1022]
**Describe the bug**
I cannot find description of Button component on the doc site
https://wix.github.io/react-native-ui-lib/getting-started/setup

**Component?**
Button
![no_button_in_doc](https://user-images.githubusercontent.com/2856462/98223248-e9851080-1f62-11eb-9b1c-0caf2c911367.png)

**Comment by ethanshar** [comment]
Hi @aefimov64 
Thank you for bringing it to our attention. 

It appear that our auto generated doc site has recently fail generating some components.
I'm still investigating, I'll update when this issue fixed.
