### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by hreochen** [wix/react-native-ui-lib#1028]

**Comment by ethanshar** [comment]
Hi @hreochen 
can you please add your code here so we can investigate.
Thanks.

**Comment by awHamer** [comment]
This is still an issue.
This reproducible on Android only, for iOS it works like a charm. Any thoughts on this?

**Comment by andrewBIsP** [comment]
Or you can just use `{ TouchableOpacity } from 'react-native-gesture-handler'`
