### ISSUE TITLE
I got error: Invariant Violation: Tried to register two views with the same name CustomKeyboardViewNativeTemp

### ISSUE THREAD

**Issue by vitalizis** [wix/react-native-ui-lib#1037]
I got the next error: Invariant Violation: Tried to register two views with the same name CustomKeyboardViewNativeTemp My package.json:
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
  },
  "dependencies": {
    "emoji-dictionary": "^1.0.11",
    "emojilib": "^2.4.0",
    "expo": "~39.0.2",
    "expo-splash-screen": "~0.6.0",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "lodash": "^4.17.20",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-emoji-render": "^1.2.4",
    "react-native": "~0.63.2",
    "react-native-autogrow-textinput": "^5.4.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-picker-select": "^8.0.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-ui-lib": "^5.16.0",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "react-router-native": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```
I use CustomKeyboardViewNativeTemp in my code only once time.

const CustomKeyboardViewNativeAndroid = requireNativeComponent('CustomKeyboardViewNativeTemp');

I dont find 'CustomKeyboardViewNativeTemp' in my node_modules.

How to fix it?

**Comment by M-i-k-e-l** [comment]
Hi @vitalizis,
Is this a new project or are you migrating from `react-native-keyboard-input`? Or why are you not using the `KeyboardAccessoryView` component?

**Comment by vitalizis** [comment]
Hi @M-i-k-e-l ! I just take code from react-native-keyboard-input example. You mean we should try replacing  CustomKeyboardViewNativeTemp on KeyboardAccessoryView?

**Comment by M-i-k-e-l** [comment]
You are looking at the implementation, not the usage.
You should look at our example screen on how to use the `KeyboardAccessoryView` ([KeyboardInputViewScreen](https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/nativeComponentScreens/keyboardInput/KeyboardInputViewScreen.js)).
