### ISSUE TITLE
incubator link

### ISSUE THREAD

**Issue by sinafbd** [wix/react-native-ui-lib#1042]
**Describe the bug**
https://wix.github.io/react-native-ui-lib/docs/Incubator/
this is incubator link in docs which is broken 

**Component?**
Are there missing docs for a component? Which component? 
incubator

**Comment by ethanshar** [comment]
Yes, the reason for that is that `Incubator` is not really a component but just a namespace that ground all experimental components that are WIP. 
We need to fix our docs to avoid it sending users to a 404 page. 

@M-i-k-e-l 
Can you please fix it in the our docs. 
Maybe we can make the **Incubator** item in navbar un-clickable or something..

**Comment by M-i-k-e-l** [comment]
@ethanshar I don't see the `Incubator` sections when running locally (tried the branch from your [PR](https://github.com/wix/react-native-ui-lib/pull/1036)), any idea?

**Comment by ethanshar** [comment]
ohh ok, 
due the previous bug and the changes I made, before running our docs locally you will need to run `npm run build` to create all the JS files out of typescript.. 
at the moment, gatsby generates docs fine only out of JS files :/
