### ISSUE TITLE
KeyboardAccessoryView Use is not stable on Android operating system

### ISSUE THREAD

**Issue by luudatphat** [wix/react-native-ui-lib#1049]
KeyboardAccessoryView  not stable on Android 

- I using code example of Keyboard Accessory View but it not working same demo ???? when build 'react-native run-android --variant = release' and run app.

- Being on Android 7.1, 8.1, 9.0

- Could you please help me, how I can fix it. 

Thank you.

Version : 
`"react-native-ui-lib": "^5.16.0",
  "react-native": "^0.62.2",`

[![video247cea61-6d2c-4691-92dd-f309bc22fc48video](https://user-images.githubusercontent.com/48847163/100419908-0de29180-30b8-11eb-84e0-274f504fe140.gif)](url)

**Comment by luudatphat** [comment]
@M-i-k-e-l  ,can you help me . Thank You very much

**Comment by nguyenvanan18031993** [comment]
Same problem in Android. ! It works when I debug but not when release APK. Please help!! Thanks

**Comment by M-i-k-e-l** [comment]
Hi @luudatphat and @nguyenvanan18031993,

Could you please look at [these setup instructions](https://github.com/wix/react-native-ui-lib/issues/1072#issuecomment-748644721), and then add the following (taken mostly from [here](https://www.instamobile.io/android-development/generate-react-native-release-build-android/)):
1. Run the following (change values as necessary) `keytool -genkey -v -keystore your_key_name.keystore -alias your_key_alias -keyalg RSA -keysize 2048 -validity 10000`
2. Answer the questions in the terminal.
3. Move the keystore to you android folder: `mv my-release-key.keystore /android/app`
4. Add the following to your build.gradle file:
```
android {
....
  signingConfigs {
    release {
      storeFile file('your_key_name.keystore')
      storePassword 'your_key_store_password'
      keyAlias 'your_key_alias'
      keyPassword 'your_key_file_alias_password'
    }
  }
  buildTypes {
    release {
      ....
      signingConfig signingConfigs.release
    }
  }
}
```
5. Make sure you have the following folder: `android/app/src/main/assets/`
6. Run `npx react-native run-android --variant=release`

This has worked for me. If this is not working for you, please give me some more information:
1. An example project which has the problem.
2. An emulator (from AndroidStudio) I should install it on (with an exact API).
3. What exactly you expect to happen and does not happen (I'm sorry, but your video may be obvious to you but not to me, it looks like you've changed the layout so I'm not sure what to expect).
