### ISSUE TITLE
Picker.item multi value throwing Error 5.17.0

### ISSUE THREAD

**Issue by vikasg603** [wix/react-native-ui-lib#1053]
**Describe the bug**
When we click on save button inside Picket multi mode, The Picker is throwing an error "TypeError: undefined is not an object (Evaluating 'itemsByValue[item].label')"

**To Reproduce**
1. Go to 'Picker component multi mode'
2. Select Item and click on save
3. See error

**Expected behavior**
There should be no error

**Code snippet**
<Picker
	placeholder="None"
	titleStyle={styles.titleStyle}
	title="Style"
	mode={'MULTI'}
	value={this.state.Style}
	enableModalBlur={false}
	onChange={(item) => this.setState({Style: item})}
	topBarProps={{
		title: 'Style',
		titleStyle: {fontFamily: 'Mulish-Regular', lineHeight:18, fontSize: 16}
	}}
	showSearch
	searchPlaceholder={'Search for styles'}
	searchStyle={{
		placeholderTextColor: Colors.dark50,
	}}>
	{this.state.ProductsData.Style.map((item, index) => (
		<Picker.Item
			key={index.toString()}
			value={index}
			label={item.title}
		/>
	))}
</Picker>

**Comment by ethanshar** [comment]
As discussed in our Discord channel...

When the `Picker.Item`s are based on a dynamic value (`this.state.ProductsData.Style` in this case) and might change in runtime, I suggest passing to the `Picker` component the `key` props to let it know it needs to reconstruct. 

Something like that can do the trick
```
<Picker key={this.state.ProductsData.Style.length} ..... />
```
