### ISSUE TITLE
Migrate to @react-native-picker/picker from @react-native-community/picker

### ISSUE THREAD

**Issue by manoj398** [wix/react-native-ui-lib#1056]
**Describe the bug**
Migrating to the @react-native-picker/picker manually keeping old @react-native community/picker (removing it causes error using react-native-ui-lib)  gives error,  during gradle build,  of having multiple classes with same name. The package needs to be migrated in react-native-ui-lib instead.

**To Reproduce**
1. Install both the packages in demo project
2. run npx react-native run android

**Expected behavior**
Should support migration to @react-native-picker/picker as its doc suggests

**Comment by manoj398** [comment]
refer https://www.npmjs.com/package/@react-native-community/picker

**Comment by ethanshar** [comment]
Hi @manoj398 
Thanks for the bug report.

It will take us couple of weeks till we can merge a fix due to some internal architecture with our native dependencies. 
And due to the fact we can't have both decencies at the same time.. 

We will update as soon as possible.

**Comment by gran33** [comment]
Any update here?
When the fix version will be released?

**Comment by manoj398** [comment]
Will be fixed by https://github.com/wix/react-native-ui-lib/pull/954/

**Comment by manoj398** [comment]
Also fixed in https://github.com/wix/react-native-ui-lib/pull/1063

**Comment by gran33** [comment]
Thanks @manoj398, when a version with the fix will be released?

**Comment by manoj398** [comment]
> Thanks @manoj398, when a version with the fix will be released?

@ethanshar When is 5.21.0 due?

**Comment by ethanshar** [comment]
Fixed in 5.21.0

**Comment by Epick362** [comment]
Having 
```
    "react-native-ui-lib": "^5.21.0",
    "@react-native-picker/picker": "^1.9.11",
```
in package.json causes this error
```
Unable to resolve module `@react-native-community/picker` from `node_modules/react-native-ui-lib/src/optionalDependencies/PickerPackage.js`: @react-native-community/picker could not be found within the project.
```
Having both packages causes Android build crash for duplicate packages. I tried removing node_modules completely but that did not help. I will have to downgrade for the time being.

**Comment by manoj398** [comment]
Did you delete package-lock while reinstalling? New version doesn't use `@react-native-community/picker` so such issue shouldn't occur. Unless package-lock references old bindings
