### ISSUE TITLE
How can I change the color of the blue underline under a TabBar Item?

### ISSUE THREAD

**Issue by stanica** [wix/react-native-ui-lib#1060]
Title says it all. I can change the label color but not the underline color (or size).

**Comment by ethanshar** [comment]
Hi @stanica 
Are you referring to our TabController component to TabBar ?

**Comment by stanica** [comment]
![2020-12-07 11 44 14](https://user-images.githubusercontent.com/1376740/101378949-b4c9e900-3881-11eb-8e82-117c5f3f1811.jpg)

I'm referring to the blue line under UPCOMING

**Comment by Inbal-Tish** [comment]
pass it in `indicatorStyle` prop

**Comment by stanica** [comment]
Thanks!
