### ISSUE TITLE
Request example for Picker with MULTI 

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#1061]
## Ask us any question

Please let us know what is Wrong with my implementation?
```
"react-native-ui-lib": "^5.17.2",
```

```
const [language2, setlanguage2] = useState(options[2].value)

<Picker
    migrate
    title="Language"
    placeholder="Favorite Language"
    value={language2}
    onChange={value => setlanguage2(value)}
    topBarProps={{title: 'Languages'}}
    showSearch
    searchPlaceholder={'Search a language'}
    mode={'MULTI'}
    // useNativePicker
    >
    {options.map(option => (
        <Picker.Item key={option.value} value={option.value} label={option.label} disabled={option.disabled} />
    ))}
</Picker>
```
In above code with `useState(options[2].value)` getting below warning
`
Picker in MULTI mode must accept an array for value 
`

```
const [language2, setlanguage2] = useState(options[2])
```
In above code with `useState(options[2])` getting below warning and nothing preselected in Pickeritems.
`
UILib Picker will stop supporting passing object as value in the next major version. Please use either string or a number as value 
`

**Comment by ethanshar** [comment]
Hi @saravanakumargn 
Regarding the first case. 
When using `mode={'MULTI'}` you'll have to use an array for `value`. And it seem you're sending a non-array. 
For instance 
```
<Picker
    migrate
    value={['js', 'python']} // must send an array of values in Multi mode
    mode={'MULTI'}

</Picker>
```

Regarding the 2nd case
You are receiving a migration warning for not sending value as **objects**. 
From now on we will start supporting only primitive (string/number) for the `value` prop.
But again, if you want a **Multi** select picker, pass an array of strings/numbers.

**Comment by saravanakumargn** [comment]
@ethanshar Thanks for your help.
