### ISSUE TITLE
I try to install keyboard package from yarn or npm and cannot find it for https://github.com/wix/react-native-keyboard-input#important-deprecation-alert

### ISSUE THREAD

**Issue by tastafur** [wix/react-native-ui-lib#1070]
### Describe the bug

I try to install keyboard package from yarn or npm and cannot find it for https://github.com/wix/react-native-keyboard-input#important-deprecation-alert and https://github.com/wix/react-native-keyboard-tracking-view#important-deprecation-alert

### To Reproduce

yarn add react-native-ui-lib/keyboard or npm install react-native-ui-lib/keyboar

### Expected behavior

That these libraries will be installed

### Screenshots

![Captura de pantalla 2020-12-09 a las 17 15 37](https://user-images.githubusercontent.com/11853181/101655755-3f594680-3a42-11eb-98fc-d0035d7f704b.png)
![Captura de pantalla 2020-12-09 a las 17 15 44](https://user-images.githubusercontent.com/11853181/101655778-484a1800-3a42-11eb-84c0-69d6797b92a4.png)

**Comment by ethanshar** [comment]
@tastafur 
To use the keyboard components you must install `react-native-ui-lib` **and not** `react-native-ui-lib/keyboard`

Try this
- `npm install react-native-ui-lib`
- In your code import the keyboard package
```
import {KeyboardTrackingView, KeyboardAwareInsetsView, KeyboardRegistry, KeyboardAccessoryView, KeyboardUtils} from 'react-native-ui-lib/keyboard';

...
```

**Comment by tastafur** [comment]
So this react-native-ui-lib/keyboard method won't work for now?

**Comment by ethanshar** [comment]
> So this react-native-ui-lib/keyboard method won't work for now?

Not sure I understand what you mean, `react-native-ui-lib/keyboard` is not a method, but an path to import.

**Comment by tastafur** [comment]
I mean, what do you recommend in their respective libraries to install it that way too, I was wondering if at some point it would be possible to use them that way?
![Uploading Captura de pantalla 2021-01-14 a las 9.38.25.png…]()

**Comment by byteasc** [comment]
> I mean, what do you recommend in their respective libraries to install it that way too, I was wondering if at some point it would be possible to use them that way?

You do not install individual libraries, you install the `react-native-ui-lib` package and then import what you want (or all)

**Comment by eughene-cherepov** [comment]
Any updates on it? Is there any way not to install the whole library if I need only `react-native-ui-lib/keyboard`?
