### ISSUE TITLE
Apply loadColors multiple times

### ISSUE THREAD

**Issue by tareqdayya** [wix/react-native-ui-lib#1080]
### Which component?
Colors.loadColors

### What is the new feature?
Right now, it seems that `Colors.loadColors` can be called only once before using any of the components. I.e. Switching to a different theme, it wouldn't be possible to set those custom colors we had loaded to something else.

For example, this is a Text component with the custom color "success". If I change the theme, say from light to dark, it would make sense for me to be able to set the success color to something different:
`<Text success>Some Text</Text>`

### Code snippet
`    toggleTheme(theme: 'dark' | 'light') {
        Colors.loadColors(MY_COLORS[theme]);
    },`

**Comment by ethanshar** [comment]
Hi @tareqdayya, 
To make sure I understand the issue. 
You wish `Colors.loadColors` to affect components in runtime?

**Comment by tareqdayya** [comment]
@ethanshar yup, exactly.

**Comment by ethanshar** [comment]
I don't think it's possible at the moment. 
Our Colors class just keeps a map of all colors - it's not connected to your screen state in any way. 
In order to trigger a re-render you'll have to change the screen's state/props. 

Maybe you can load the new colors and trigger a setState in the screen - did you trying doing something like that?

**Comment by tareqdayya** [comment]
> I don't think it's possible.
> Our Colors class just keeps a map of all colors - it's not connected to your screen state in any way.
> In order to trigger a re-render you'll have to change the screen's state/props.
> 
> Maybe you can load the new colors and trigger a setState in the screen - did you trying doing something like that?

Yup, exactly, `loadColors` seems not to affect, or be affected by, the app state, hence the feature request 🙂
Here's a simple example of what you prescribed if i got what you said correctly:

`
Colors.loadColors({
  reddish: 'red',
  greenish: 'green',
});

const Home: FC<Props> = () => {
  // forces a re-render
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0);

  useEffect(() => {
    setTimeout(() => {
      Colors.loadColors({
        reddish: 'green',
        greenish: 'red',
      });

      // force the re-render
      forceUpdate();
    }, 3000);
  }, []);

  console.count('render');

  return <Text reddish>Some Text</Text>;
};
`

In the example above, i'm reversing the colors and forcing the update of the component. Unfortunately, nothing happens. The Text component's color is still the same as the first one loaded.

It seems that the problem is not in the `loadColors` method, bur rather in whatever maps the props "reddish" and "greenish" to modifiers on the components after calling the `loadColors` method for the first time. Maybe the `asBaseComponent` HOC?

**Comment by ethanshar** [comment]
Ok, yes. it seems like the modifiers don't recreate when colors change. 
Just for the sake of experiment. 
what happen if you'll render the Text like this
```
  return <Text style={{color: Colors.reddish}}>Some Text</Text>;
```

This works, right?

**Comment by tareqdayya** [comment]
> Ok, yes. it seems like the modifiers don't recreate when colors change.
> Just for the sake of experiment.
> what happen if you'll render the Text like this
> 
> ```
>   return <Text style={{color: Colors.reddish}}>Some Text</Text>;
> ```
> 
> This works, right?

This one does work indeed if i force a re-render after the change.

**Comment by ethanshar** [comment]
Regarding the force of the re-render, loadColors API won't be able to handle that cause it's not connected in any way to react state. 
I suggest creating a wrapper in your code that triggers a re-render when a theme is changed. 
If you'll trigger a re-render **after** re-loading the colors, Ii should work. 

Here's a code example: 
```
// Loading initial the "reddish" color
Colors.loadColors({
  reddish: 'red'
});

export default class PlaygroundScreen extends Component {
  state = {
    theme: undefined
  };

  changeTheme = () => {
    // reload colors - change reddish
    Colors.loadColors({
      reddish: 'green'
    });

    // trigger a re-render
    this.setState({theme: Date.now()});
  };
  render() {
    return (
      // Here I use the key prop to reconstruct the screen when a theme has changed, it will re-render the view and its children
     // and you'll see the color change. 
      <View bg-dark80 flex padding-20 key={this.state.theme}>
        <Text reddish onPress={this.changeTheme}>
          REDDISH
        </Text>
      </View>
    );
  }
}
```

**Comment by tareqdayya** [comment]
@ethanshar This does work, however the workaround of having to update every component might be a hassle. Right now, i'm using my own provider so I can switch the theme, and in order to pass props, I copied [uhm, was influenced by 👮] the logic for the props from your library.

Would it be possible to connect the "Colors" module to the state through a provider which would be exported, and instead of exporting the loadColors method, have it implicitly run every time the value passed to the provider is updated? This way, instead of having to use loadColors, loadTypographies and loadSpacings, we could just pass a prop to the exported provider. This way, all components within the app can have access to the theme context which would make the color props dynamic. I think that's how react native paper does it.

This would be a breaking change, of course, so I understand if you're not interested or want to leave it for a future time.
Also, if you need help with it, I would be more than happy to help.

**Comment by ethanshar** [comment]
@tareqdayya 
Can you maybe add a code example of how you would have used that.

If I understand correctly, you want us to create a theme context and export a provider which you can use in your screens and this way have theme values that change in runtime?

**Comment by tareqdayya** [comment]
Hi, sorry for the delayed response.

Your guess is correct. RnuLib would export a provider, it would be a replacement for all the _**load*()**_ methods it exports now. The user would pass their theme to it:

`
import { RnuLibProvider } from 'react-native-ui-lib/style';

// includes everything: colors, shadows, typography, spacings...etc
const theme = {
  color: {
    light: {
      primary: 'blue,
      secondary: 'grey',
      tertiary: 'red',
    },
    dark: {},
  },
  typography: {
    B: { fontWeight: '900' },
    M: { fontWeight: '600' },
    L: { fontWeight: '300' },
  },
  spacing: {
    s: 10,
    m: 16,
    l: 24,
  },
};

const App = () => (
  <RnuLibProvider theme={theme}>
    <YourAppRoutesHere />
  </RnuLibProvider>
);`


The RnuLibProvider would execute all the logic currently done by the load* methods every time the value passed to the `theme` prop changes. You could optionally export a useTheme() hook to consume the context which hosts the processed theme.

The user would be responsible for changing themes passed down to the provider, e.g. redux.

**Comment by ethanshar** [comment]
Hi @tareqdayya
TBH, not sure how useful will it be to provide this kind of provider. 
This is something you can easily do yourself.. not sure what's the benefit of us creating a theme context. 
If you have a redux store in your app you can easily manage that. 

Instead I've worked on a draft for dark mode support in our modifiers ( I assume we're this is all for dark mode, right?)
See draft: https://github.com/wix/react-native-ui-lib/pull/1147

It allows to configure color schemes (similar to what you have in your example), like this
```
Colors.loadSchemes({
   light: {
     screenBG: 'transparent',
     textColor: Colors.grey10
   },
   dark: {
     screenBG: Colors.grey10,
     textColor: Colors.white
   }
 });
```

And use them in the code as modifiers like this
```
<View flex bg-screenBG>
  <Text textColor >Dark Mode</Text>
</View>
```

And in case you don't want to pass the scheme colors everywhere. You don't have to.. 
You can use `ThemeManager` to set them as defaults like this
```
ThemeManager.setComponentTheme('View', {
  'bg-screenBG': true
});

ThemeManager.setComponentTheme('Text', {
  'textColor': true
});
```

Let me know what you think? 

https://user-images.githubusercontent.com/1780255/105609048-426c8400-5daf-11eb-8fba-bc9464498b65.mov

**Comment by tareqdayya** [comment]
Exactly, It's all about switching to dark mode and using the built-in methods in the Colors module.
It does seems like #1147  takes care of that.
Looking forward to it 🙂

**Comment by RatebSeirawan** [comment]
dark, light themes don't solve the problem especially if you have more than light/dark themes in your app, with Providers we can change the current theme dynamically and programmatically, and different themes can be applied to different parts of the components tree, It would be much better to be added to the library, but for now, I wrote something hacky to change the theme dynamically

```ts
const useTheme = () => {
  const [scheme, setScheme] = useState<"bluish" | "pinky" | "grayish">(
    "bluish"
  );

  Colors.loadColors(theme[scheme]);

  setTimeout(() => {
    Colors.loadColors({});
  }, 0);

  return { setScheme };
};
```

```ts
const theme = {
  bluish: {
    primaryColor: "#2364AA",
  },
  pinky: {
    primaryColor: "#fafa",
  },
  grayish: {
    primaryColor: "#cccc",
  },
};
```

```ts
export const MyScreen = () => {
  const { setScheme } = useTheme();

  return (
    <View flex padding-page useSafeArea margin-12>
      <Button
        label="Pink"
        bg-primaryColor
        onPress={() => {
          setScheme("pinky");
        }}
      ></Button>
      <Button
        label="Blue"
        bg-primaryColor
        onPress={() => {
          setScheme(() => "bluish");
        }}
      ></Button>
      <Button
        label="Gray"
        bg-primaryColor
        onPress={() => {
          setScheme(() => "grayish");
        }}
      ></Button>
    </View>
  );
};

```
