### ISSUE TITLE
How to use the loaderScreen

### ISSUE THREAD

**Issue by NikoMontana** [wix/react-native-ui-lib#109]
The link in the docs is down, can anybody explain how to use it?

https://wix.github.io/react-native-ui-lib/docs/LoaderScreen/

**Comment by ethanshar** [comment]
Hey @NikoMontana, 
The LoaderScreen is a full screen component, You can render it as the root component of your screen. 
Another option is to render it on top of an existing content using the `overlay` prop. 
please see example here: 
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreenScreens/LoadingScreen.js

**Comment by isaachinman** [comment]
@ethanshar Just a heads up, the [code example link on this page](https://wix.github.io/react-native-ui-lib/docs/LoaderScreen/) for LoaderScreen is broken.

**Comment by isaachinman** [comment]
@ethanshar @NikoMontana In assuming that `react-native-ui-lib` is compatible with `react-native-navigation`, is it possible to configure the `LoaderScreen` to cover the navigation bar? Or will this simply depend on where the `LoaderScreen` is mounted?

**Comment by isaachinman** [comment]
In the interim for anyone else wondering, I just recreated the component with a `Modal` directly from RN to allow covering of the navigation bar:

    <Modal
      visible={active}
      transparent
      animationType='fade'
      hardwareAccelerated
    >
      <View style={styles.container}>
        <ActivityIndicator size='large' color={whitePrimary} />
      </View>
    </Modal>

**Comment by Inbal-Tish** [comment]
That's right, the LoaderScreen is a component you can render as you need (show modal, push, render as part of a screen by condition, etc.).
By the way, I fixed the broken link. Thanks for the note!
