### ISSUE TITLE
tab bug in the demo 

### ISSUE THREAD

**Issue by jamesjara** [wix/react-native-ui-lib#1097]
I'm adding the video , there is a bug in the tabs, just navigate between tabs and it will be reproduced, the selected tab index is not the same in the pane area. Any idea, we could try to fix it if we have some direction, thanks 

https://user-images.githubusercontent.com/780219/103140343-217b1b00-46ab-11eb-9954-4cab799a846c.mp4

**Comment by ethanshar** [comment]
Hi @jamesjara 
Which version of react-native-reanimated you have installed?

**Comment by RobertBaron** [comment]
Having the same issue with "react-native-reanimated": "^1.7.0",

**Comment by ethanshar** [comment]
I suggest upgrading reanimated version, try installing latest (should be 1.13.1)
