### ISSUE TITLE
Shadow not working on Android

### ISSUE THREAD

**Issue by NikoMontana** [wix/react-native-ui-lib#110]
Shadow is displayed on iOS but not on Android.

            <Button
              marginT-10
              backgroundColor="#6E9BC1"
              label="Register"
              labelStyle={{ fontWeight: "600" }}
              enableShadow
              onPress={() => this.phoneLogin()}
            />

**Comment by ethanshar** [comment]
Hey @NikoMontana, 
please get latest version of uilib, the issue should be resolved.

**Comment by cinder92** [comment]
where are your docs? this shadows works like on iOS?

**Comment by Inbal-Tish** [comment]
@cinder92 Shadows only work on iOS, in Android, we're using `elevation`.
