### ISSUE TITLE
Can TextField support custom component?

### ISSUE THREAD

**Issue by wangyi7099** [wix/react-native-ui-lib#1108]
Hi ! I just want to use the label of text component...     I dont want to render a `Text` but a picker or something else? Can I do this? Thanks! This feature is like [`InputComponent`](https://reactnativeelements.com/docs/input#inputcomponent) of RNE

**Comment by ethanshar** [comment]
Hi @wangyi7099 
Just making I understand, you want to pass for `label` a custom element instead of passing a string?

**Comment by wangyi7099** [comment]
Sorry. I don't mean this. My english is poor.   
Currently I use `TextField`  component. But this can only render a label and a input.    I want to render a label and a timepick or something else. Can I do this? Thanks!

**Comment by wangyi7099** [comment]
I want to keep the label style and dont render a input but a picker or something else

**Comment by ethanshar** [comment]
Ohh I see, you want a custom input but with the structure of our TextField ? correct?

**Comment by wangyi7099** [comment]
Is there any progress?

**Comment by ethanshar** [comment]
Create a PR for supporting passing `children` prop to Incubator.TextField to render a custom input

**Comment by ethanshar** [comment]
This feature was already added recently, you can now pass `children` and have a custom input instead of RN TextInput
