### ISSUE TITLE
Demo App at expo needs to be updated

### ISSUE THREAD

**Issue by wangyi7099** [wix/react-native-ui-lib#1109]
Currently expo client sdk version is 37.0.0 and demo is using 36.0.0. This will cause user cannot view demo at latest expo client!

**Comment by ethanshar** [comment]
Hi @wangyi7099 
Are you sure about it? 
I see we use expo 40.0
https://github.com/wix/react-native-ui-lib/blob/5c9179f6b8c929382cd7e19ddcf83ab3b90d329d/expoDemo/package.json#L18

**Comment by wangyi7099** [comment]
Hi  I have just downloaded the latest expo client and scan the qrcode at README.MD of this repo and show then show me above error!

**Comment by fasalir** [comment]
> Hi I have just downloaded the latest expo client and scan the qrcode at README.MD of this repo and show then show me above error!

Me too
![WhatsApp Image 2021-01-12 at 11 36 11](https://user-images.githubusercontent.com/19751530/104270256-a7300080-54ca-11eb-88c3-feea27ca5032.jpeg)

![WhatsApp Image 2021-01-12 at 11 48 49](https://user-images.githubusercontent.com/19751530/104270964-4a354a00-54cc-11eb-8dc3-65d5657189fb.jpeg)

**Comment by ethanshar** [comment]
Hi All, 
I just republished the app. 
Can you try again 🙏

**Comment by wangyi7099** [comment]
> Hi All,
> I just republished the app.
> Can you try again 🙏

Thanks! The demo looks good now !!!
