### ISSUE TITLE
[Android] ActionSheet options cannot be pressed when using custom 'renderAction', works fine on IOS. 

### ISSUE THREAD

**Issue by RyanxWolton** [wix/react-native-ui-lib#1120]
### Describe the bug

I have a simple component which consists of a button which when pressed, displays the ActionSheet. I want icons for each of my actions, so I've used the renderAction option to provide a custom component for each action. This is all working fine on IOS, however, on Android, the actions cannot be pressed, there is no feedback from the TouchableOpacity either. I am able to interact with the ActionSheet itself by dragging. 

Everything works fine if I remove the 'renderAction' option. 

### To Reproduce

1. Use ActionSheet with a custom 'renderAction' function
2. Test on Android
3. Unable to interact with options

### Code snippet

```
  <ActionSheet
    onDismiss={() => setShowActions(false)}
    visible={showActions}
    title={title}
    options={options}
    renderAction={renderAction}
    containerStyle={{ 
      borderRadius: 10, 
      paddingBottom: SAFE_AREA_BOTTOM ,
      backgroundColor: colors.background
    }}
  />
```

#### The renderAction function
```
  const renderAction = ({label, icon, onPress}: Action) => (
    <TouchableOpacity onPress={() => { onPress(); setShowActions(false);}} key={label}>
      <View padding-gap>
        <Row centerV>
          <FontAwesomeIcon icon={icon} size={28} color={colors.primary}/>
          <Text body marginL-gap color={colors.text}>{label}</Text>
        </Row>
      </View>
    </TouchableOpacity>
  )
```

### Device 

 - Device: Huawei P40 lite E
 - OS: Android 10

**Comment by lidord-wix** [comment]
Hey @RyanxWolton, 
We couldn't reproduce this bug - it acts the same way on iOS and on Android for us.
Which ui-lib's version are you using?
And anyway, `renderAction` should be function of this type:
`renderAction?: (option: ButtonProps, index: number, onOptionPress: ActionSheetOnOptionPress) => ReactElement;`
Try to use it that way - it might solve the problem :)

**Comment by RyanxWolton** [comment]
I've tried this already, the only reason I started using 'onPress' is because onOptionPress doesn't seem to work, it causes the ActionBar to close, but does not invoke the onPress function defined in the option. I have just tried it again to be sure and I still have the same problem on Android, and now the problem I described with onOptionPress on iOS as well. 

I'm using v5.13.0

**Comment by lidord-wix** [comment]
Which version of RN are you using?

**Comment by RyanxWolton** [comment]
I've now updated to v5.19.1, and RN version is 0.63.3.

Unfortunately this has not resolved my original issue on android and onOptionPress still does not work, it just closes the ActionBar as mentioned previously. 

renderAction now looks like this:

```
  const renderAction = ({label, icon}: Action, index: number, onOptionPress: ActionSheetOnOptionPress) => (
    <TouchableOpacity onPress={onOptionPress} key={label}>
      <View padding-gap>
        <Row centerV>
          <FontAwesomeIcon icon={icon} size={28} color={colors.primary}/>
          <Text body marginL-gap color={colors.text}>{label}</Text>
        </Row>
      </View>
    </TouchableOpacity>
  );
```

**Comment by RyanxWolton** [comment]
I've just tried a simple experiment in a fresh view, importing ActionSheet directly with a simple implementation, just to be sure it wasn't something I was doing, but I get the same result.

**Comment by lidord-wix** [comment]
Try to use `renderAction` that way please: 
```
 const renderAction = ({label, icon}: Action, index: number, onOptionPress: ActionSheetOnOptionPress) => (
    <TouchableOpacity onPress={() => onOptionPress(index)} key={label}>
      <View padding-gap>
        <Row centerV>
          <FontAwesomeIcon icon={icon} size={28} color={colors.primary}/>
          <Text body marginL-gap color={colors.text}>{label}</Text>
        </Row>  
      </View>
    </TouchableOpacity>
  );
```

**Comment by RyanxWolton** [comment]
Hi, ok yes, thank you, that does solve it for iOS, onOptionPress now performs the action correctly. Android is unchanged, tested now also on a Samsung device with the same result

**Comment by RyanxWolton** [comment]
OK, I've got it working. Turns out it wasn't an issue with ActionSheet after all, I was importing TouchableOpacity from react-native-gesture-handler and for some reason this is what is causing the problem, I imported it from react-native instead and now this is working. 

Thanks for your time on this.

**Comment by lidord-wix** [comment]
You're welcome :)
