### ISSUE TITLE
Wizard Label Container background color Config option + Wizard documentation update

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [wix/react-native-ui-lib#1128]
### Wizard Styling

```
  ThemeManager.setComponentTheme('View', {   backgroundColor: '#000',
    color: '#fff');
  ```
  
 This command leaves what looks like (from the Inspector)  nested Views + an RCTView with hard coded 'Background' colors of '#FFFFFF'
 
 Documentation for the Wizard (https://wix.github.io/react-native-ui-lib/docs/Wizard/) and the Wizard Steps (https://wix.github.io/react-native-ui-lib/docs/Wizard.Step/) does not seem to show all options are available for the basics, but styling the background color _specifically_ is missing.
 
 How do I fix that?

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Can you assist here..

**Comment by M-i-k-e-l** [comment]
Hi @AlphaJuliettOmega,

You are right on two counts:
1. It seems we lack background configuration :/
2. The wizard has a bit of an odd configuration when using theme, we'll need to add better docs for that.

**Comment by AlphaJuliettOmega** [comment]
@M-i-k-e-l 
Woah, thank you very much!

**Re. 1**
This is to reproduce:
```
<Wizard style={minimalDark}>Steps...</Wizard>
```
Where minimalDark:
```
{
    backgroundColor: '#000',
    color: '#FFF'
  }
  ```
A genius (a wizard wizard) sent me this:

```
ThemeManager.setComponentTheme('Wizard', (props, context) => {
  console.log(props);
  //console.log(context);
});
```

Props output was this:
```
{"activeIndex": 0, "children": [<Wizard.Step backgroundColor="#000".../>x6], "onActiveIndexChanged": [Function anonymous], "style": {"backgroundColor": "#000", "color": "#fff"}, "testID": "uilib.wizard"}
```

I'm hoping that background color already being set correctly means that it will be a small fix to drop the color into the one view that doesn't change color.

**Re. 2**

Interesting, looking forward to savoring when the doc update comes 👍

**Comment by M-i-k-e-l** [comment]
@AlphaJuliettOmega 
The #1148 PR, is adding the `circleBackgroundColor` you've requested.
The docs will take a little longer, but you can see an example in the #1140 PR.
Please let me know if that's clear enough.

**Comment by AlphaJuliettOmega** [comment]
@M-i-k-e-l very cool! 

I'm thinking the way forward for me is to wait for the next release so I can version-bump in my package.json, I'd rather go that route than a work-around to get that latest commit into my codebase.

I appreciate the info, will watch for release like a hawk.

**Comment by AlphaJuliettOmega** [comment]
@M-i-k-e-l ahhh, hmmm

That property wasn't documented yes

Is that the property that would be able to _backgroundColor_ the white area in this screenshot or is that a different property I'm missing?

![image](https://user-images.githubusercontent.com/19306746/106931296-18a44d00-671f-11eb-87c7-24a4036ef862.png)

Just in case it matters:
```react-native-ui-lib@^5.20.1:```

I was looking for `Wizard.Step.propTypes` and I found this line:
https://github.com/wix/react-native-ui-lib/blob/e16c2667f16201860af56f7f9de415254ef0afa2/src/components/wizard/index.js#L107

Just after that there is padding, 
It looks like the props should combine and I should be able to change that backgroundColor &or the padding.

I tried to do something like that but it looks like it doesn't use the style I pass or I'm missing something.

**Comment by M-i-k-e-l** [comment]
Not sure I understood you, can you please try sending  `containerStyle={{backgroundColor: 'black'}}` to `Wizard`? You can change the padding (vertical or horizontal) there.

**Comment by AlphaJuliettOmega** [comment]
@M-i-k-e-l You're the best, it worked thank you!

**Comment by M-i-k-e-l** [comment]
Still have the documentation to fix (need to build infra for it)
