### ISSUE TITLE
Links to wiki in readme are not working

### ISSUE THREAD

**Issue by thomasthiebaud** [wix/react-native-ui-lib#1129]
Both links on the the main readme are linking to pages that do not seem to exist anymore.

<img width="911" alt="Screenshot 2021-01-12 at 11 07 38" src="https://user-images.githubusercontent.com/3715715/104300164-67ffb080-54c6-11eb-8e02-dcf771dc232b.png">

The pages are
- https://github.com/wix/react-native-ui-lib/wiki/SETUP
- https://github.com/wix/react-native-ui-lib/wiki/V5-%5BBreaking-Change%5D

but it seems that the wiki is not setup

**Comment by ethanshar** [comment]
Fixed
