### ISSUE TITLE
does the Button's iconSource support the popular react-native-vector-icons's icon?

### ISSUE THREAD

**Issue by wilbyang** [wix/react-native-ui-lib#113]

**Comment by ethanshar** [comment]
Currently we didn't try to support it, you're welcome to PR us with a solution.

**Comment by skuzoluk** [comment]
Do you think it is a good idea to add a new prop to Button component named iconRenderer that takes function type like `iconStyle => <SomeIconComponent style={iconStyle} name="bla-bla-icon" />`
So we can check the new prop and if it exists we can just return the custom icon component, if not fallback to iconSource. Any other solution ?

**Comment by RZsam** [comment]
I think it's a good idea to add `iconRenderer` to `<TextField>`  too
