### ISSUE TITLE
Add instructions to install/use the demo

### ISSUE THREAD

**Issue by MaxInMoon** [wix/react-native-ui-lib#115]
Maybe I missed it, but it would be nice to have a few instructions about **how to install/test the [demo](https://github.com/wix/react-native-ui-lib/tree/master/demo)**.

Thanks

**Comment by MaxInMoon** [comment]
I found this: https://github.com/xsokev/react-native-ui-lib-expo

But not able to run ([#1](https://github.com/xsokev/react-native-ui-lib-expo/issues/1))

**Comment by Inbal-Tish** [comment]
Just run the project with $react-native run-ios ($npm run ios) or $react-native run-android ($npm run android). You can also run the native project from Xcode / Android studio. Make sure you run the packager with $npm run start).

**Comment by MaxInMoon** [comment]
@Inbal-Tish thank you! Do you consider that it could be useful to add a little note in the readme? I could handle it

**Comment by Inbal-Tish** [comment]
Sure. Make a pull request and we'll review it with the others. Thanks!
