### ISSUE TITLE
Expo snack app issues

### ISSUE THREAD

**Issue by VernonHawk** [wix/react-native-ui-lib#1150]
### Is there an issue with the Expo snack app?
Yes, tested on iPhone 11, iOS 14.3, attaching screenshots and videos.

- In the main list, pressing on "Chip" does nothing
- Can't reach the last item in the list, scroll view doesn't let me

https://user-images.githubusercontent.com/22412306/105695620-f9314700-5f0a-11eb-98b7-e5a652f934fd.MP4

- There is an empty item under the Button in Components

<img src="https://user-images.githubusercontent.com/22412306/105695739-182fd900-5f0b-11eb-8aa9-cfb53057d16c.png" width=400 />

- Pressing on “Card” gives me a red screen

<img src="https://user-images.githubusercontent.com/22412306/105695773-22ea6e00-5f0b-11eb-9d36-7403a0006326.png" width=400 />

**Comment by ethanshar** [comment]
Published new version of expo with fixes
