### ISSUE TITLE
Hint component throws a TypeError

### ISSUE THREAD

**Issue by benlevy0** [wix/react-native-ui-lib#1159]
### Describe the bug

When wrapping an icon with a Hint, it throws `TypeError: undefined is not an object (evaluating '_this.targetRef.measureInWindow')`.

### To Reproduce

I installed all of the dependencies and the lib with yarn and wrapped an RN Paper IconButton with a Hint. The error is due to the Hint component; removing it solves the issue.

### Code snippet

```javascript
import { Hint } from 'react-native-ui-lib';
import { IconButton } from 'react-native-paper';
```

```javascript
<Hint
	visible
	message={
		<Text>
			message{' '}
			<Text style={{ textDecorationLine: 'underline' }} onPress={() => {}}>
				click here
			</Text>
		</Text>
	}
	position={Hint.positions.TOP}
	color="purple"
	useSideTip
	testID="Hint"
>
	<IconButton
		icon="send"
		style={{ marginRight: 20 }}
		color="purple"
		size={20}
		onPress={() => this.doSomething()}
	/>
</Hint>
```

### Device (please complete the following information)

iPhone 11 iOS 14.3 simulator

**Comment by ethanshar** [comment]
If `IconButton` was implemented in a way it doesn't forward ref. 
It means the `Hint` component can trigger the native component method `measureInWindow`
Since IconButton is not an RNUILib component we can't fix that..

But what you can try is wrapping the IconButton with our `View` component.

**Comment by benlevy0** [comment]
Wrapping the IconButton with your View component worked, thanks!
