### ISSUE TITLE
[Feature Request] Please update for vertical carousel

### ISSUE THREAD

**Issue by JaeWangL** [wix/react-native-ui-lib#1163]
### Which component?
Carousel

### What is the new feature?
Vertical Carousel

### Code snippet
<Carousel vertical>{children}</ Carousel>

I really love UILib's Carousel than snap-carousel package
But, This seems like not supporting vertical type
Thank you for wix's effort

**Comment by ethanshar** [comment]
Hey @JaeWangL 
This should be available in our next version (5.21.0), stay tuned..
