### ISSUE TITLE
Homepage link to snack that crashes

### ISSUE THREAD

**Issue by vuki656** [wix/react-native-ui-lib#1165]
### Describe the bug

`Expo-Snack Demo` button on the home page of the docs leads to a snack that doesn't run in the web version of expo. Not sure if it's supposed to or not. 

To reproduce, open the link and click the web version of expo above the device.

![image](https://user-images.githubusercontent.com/8104698/106296532-19863c00-6252-11eb-812c-694a50375cb0.png)

**Comment by ethanshar** [comment]
Our demo app doesn't not support running on web. 
I suggest running it on a device.
