### ISSUE TITLE
Unable to "select" Radio button - Clicking/tapping on Radio Button in the group has no effect

### ISSUE THREAD

**Issue by girishjjain-rh** [wix/react-native-ui-lib#1169]
### Describe the bug
Tapping/Clicking on Radio Button has no effect. Selecting a Radio Button option should deselect previously selected option and select the one tapped on but it's broken with latest release (v5.19.1). It was last working fine for me with v5.14.0, so it broke somewhere between 5.14 and 5.19.1.

### To Reproduce
Below code used to work fine until v5.14.0 of the library but with the latest version, tapping on the Radio Button has no effect. The tapped one is not getting selected.
```typescript
          <View>
            <RadioGroup initialValue={RateType.PerAnnumUsingMonths.toString()}
              onValueChange={value => this.setState({rateType: +value})}
            >
              <TextField
                title={'Interest Rate %'}
                onChange={() => this.setState({interestRateError: ''})}
                onChangeText={value => this.setState({interestRate: +value})}
                keyboardType={'numeric'}
                validate={'required'}
                errorMessage={Strings.RequiredNumericField}
                error={this.state.interestRateError}
                validateOnChange
              />
              <View row paddingT-5>
                <RadioButton value={RateType.PerAnnumUsingMonths.toString()} label={'Per Year'} />
                <Text>      </Text>
                <RadioButton value={RateType.PerMonth.toString()} label={'Per Month'} />
              </View>
            </RadioGroup>
          </View>
```

### Expected behavior
Not sure if there was a breaking change introduced to Radio Button component after v5.14, did not come across that in release notes. If there is no breaking change introduced the Radio Button component looks broke (after v5.14.0, at least with latest release v5.19.1), user is not able to click/tap on a radio button choice, clicking has no effect but is expected to "select" the choice.

### Code snippet
```typescript
          <View>
            <RadioGroup initialValue={RateType.PerAnnumUsingMonths.toString()}
              onValueChange={value => this.setState({rateType: +value})}
            >
              <TextField
                title={'Interest Rate %'}
                onChange={() => this.setState({interestRateError: ''})}
                onChangeText={value => this.setState({interestRate: +value})}
                keyboardType={'numeric'}
                validate={'required'}
                errorMessage={Strings.RequiredNumericField}
                error={this.state.interestRateError}
                validateOnChange
              />
              <View row paddingT-5>
                <RadioButton value={RateType.PerAnnumUsingMonths.toString()} label={'Per Year'} />
                <Text>      </Text>
                <RadioButton value={RateType.PerMonth.toString()} label={'Per Month'} />
              </View>
            </RadioGroup>
          </View>
```

### Screenshots
User is not able to select between two Radio Button choices:
![Screen Shot 2021-01-31 at 7 16 16 PM](https://user-images.githubusercontent.com/40406953/106404601-d61a0200-63f8-11eb-83a7-5a3a858c7399.png)

### Device (please complete the following information)
 - Device: iPhone 12 Pro Max Simulator, iPhone 7 Device
 - OS: iOS 14.3

### Additional context
NA

**Comment by lidord-wix** [comment]
Hi @girishjjain-rh,
Please try to pass `this.state.rateType` to the RadioGroup initialValue prop. 
This prop determines which RadioButton in the group is selected :)

**Comment by M-i-k-e-l** [comment]
Hi @girishjjain-rh,
I see what you mean, looking into it.
