### ISSUE TITLE
Picker Code Sample Update

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [wix/react-native-ui-lib#1176]
### Describe the bug
Picker code sample causes the app to crash with no error

### Component?
Picker component

### Is there a general issue with the docs site?
The Code Sample was probably written with a previous version of the library & just needs an update from someone with lots of familiarity

### Is there an issue with the Expo snack app?
Unknown, not using Expo

**Comment by AlphaJuliettOmega** [comment]
Might be related to https://github.com/wix/react-native-ui-lib/issues/1056

**Comment by ethanshar** [comment]
Hi @AlphaJuliettOmega 
Are you trying to run our demo app? 
Or in a different project?

**Comment by AlphaJuliettOmega** [comment]
@ethanshar the app hard crashed with no error output logged when using the Picker as shown in the example code
