### ISSUE TITLE
Avatar ContainerStyle prop only considers certain styling attributes

### ISSUE THREAD

**Issue by juddey** [wix/react-native-ui-lib#118]
Hello, Thanks to the folks at wix for another great library.

I am trying to apply a border to the avatar component using a [ContainerStyle Prop](https://github.com/wix/react-native-ui-lib/blob/master/src/components/avatar/index.js#L38), but the additional styles seem to be filtered out by [this function](https://github.com/wix/react-native-ui-lib/blob/master/src/components/avatar/index.js#L178) ([source](https://github.com/wix/react-native-ui-lib/blob/master/src/commons/BaseComponent.js#L75)):
```
 extractContainerStyle(props) {
    let containerStyle = {};
    if (props.containerStyle) {
      containerStyle = _.pickBy(props.containerStyle, (value, key) => {
        return key.includes('margin') || _.includes(['alignSelf', 'transform'], key);
      });
    }

    return containerStyle;
  }
```
Is there a reason only certain styles are passed through to this component? (I ask because the listitem component has this function commented out).

**Comment by ethanshar** [comment]
Hey @juddey, 
Sorry for the late response, you're right, the initial thought was to enforce what's being passed in containerStyle to avoid UI issues, but clearly this should be own by the user and not the library. 
I will fix it.

**Comment by juddey** [comment]
thanks @ethanshar ! :raised_hands:
