### ISSUE TITLE
Flow type error when evaluating tmp.json

### ISSUE THREAD

**Issue by MaxInMoon** [wix/react-native-ui-lib#119]
`tmp.json` file is empty and causes a flow type error.
I had to ignore it (`.*/node_modules/react-native-ui-lib/tmp.json`) in my .flowconfig.

Do you know how to avoid the manual "ignore"?

Thanks

**Comment by Inbal-Tish** [comment]
Hi. We will remove the empty file so you won't need to ignore it manually.
