### ISSUE TITLE
Error: spawn gradlew.bat ENOENT when running demo

### ISSUE THREAD

**Issue by Rc85** [wix/react-native-ui-lib#1194]
### Describe the bug
After cloning the repo, doing npm install in both demo directory and root, and running `npm run android` in root gave me this error. I cd into the android directory and try to run `gradlew` and it says it is not a recognized command.

### To Reproduce
See above.

### Device (please complete the following information)
Windows 10 Pro desktop

**Comment by ethanshar** [comment]
Seem like your android environment is not configured correctly. 
Can you run a fresh react native project?

**Comment by DiegoBM** [comment]
Same error here. Any other newly created react-native project will work all right,  so my environment is definitely properly set. Also npm start fails. I presume that this scripts were created with *nix users in mind only, but they won't work on windows

**Comment by ethanshar** [comment]
@DiegoBM 
Can you please submit a PR to fix this. 
Unfortunately I don't have a Windows machine to investigate this issue.

**Comment by DiegoBM** [comment]
Basically, if you create a new project with "npx react-native init PROJECT_NAME", and you go to the newly generated android folder, you'll see that there is a "gradlew.bat" file which is missing in the RNUI.

I'd create the PR but, you seem to have that file explicitly ignored in your ".gitignore" file, and I don't know if your team had a valid reason for that (something related to intelliJ?). As far as I can tell @lidord-wix pushed that change, so maybe you can check with him, but that's the file that the command line uses in windows.

**Comment by lidord-wix** [comment]
@ethanshar - We put it in `.gitignore` in this PR - https://github.com/wix/react-native-ui-lib/pull/865, we might do a rethink about it.

**Comment by ethanshar** [comment]
I don't think there a real reason.. 
IMO We can remove it from gitignore and add the it back and see if it solve the issue

**Comment by DiegoBM** [comment]
Unfortunate
