### ISSUE TITLE
Selected Tab Doesn't Have Correct Color on Load

### ISSUE THREAD

**Issue by shkfnly** [wix/react-native-ui-lib#1199]
### Describe the bug
When the tab controller loads the TabItems the Selected Tab renders with black color text no matter what.

### To Reproduce

1. Load a Tab Controller
2. Set the Label Style to a Color
3. Navigate to Page with Tab Controller
4. Notice that the Tab is black
5. Click on other Tab and the first tab is the right colors.

### Expected behavior
TabItems should inherit label style from the beginning.

### Code snippet
      <TabController
        // key={key}
        asCarousel={false}
        selectedIndex={selectedIndex}
        onChangeIndex={onChangeIndex}
        items={items}
      >
        <TabController.TabBar
          indicatorStyle={{ backgroundColor: colors.primary }}
          enableShadow={false}
          centerSelected
          backgroundColor={colors.dark}
          labelColor={colors.primary}
          selectedLabelColor={"white"}

### Screenshots
<img width="380" alt="Screen Shot 2021-02-20 at 6 11 38 PM" src="https://user-images.githubusercontent.com/5394790/108612583-ce69cf80-739e-11eb-82ce-8cdc12d806f7.png">
<img width="376" alt="Screen Shot 2021-02-20 at 6 11 45 PM" src="https://user-images.githubusercontent.com/5394790/108612582-ce69cf80-739e-11eb-9a6f-9a05d39a98f1.png">
<img width="379" alt="Screen Shot 2021-02-20 at 6 11 49 PM" src="https://user-images.githubusercontent.com/5394790/108612581-cd38a280-739e-11eb-8841-efede441b5dd.png">

### Device (please complete the following information)
 - Expo

**Comment by M-i-k-e-l** [comment]
Hi @shkfnly,
Thank you for taking the time to let us know about this.
For me the problem was not only in the first tab, and only on iOS, can you confirm? 

@ethanshar,
It seems that iOS on expo has a bug with `interpolateColor` ([this line](https://github.com/wix/react-native-ui-lib/blob/master/src/components/tabController/TabBarItem.tsx#L211)), if I changed [color](https://github.com/wix/react-native-ui-lib/blob/master/src/components/tabController/TabBarItem.tsx#L222) to `color: inactiveColor` or `color: activeColor` there was no issue.
I did not find a bug on this, do you have any thoughts\ideas how to continue?

**Comment by M-i-k-e-l** [comment]
If you mean in the demoExpo, I did not use that, I created a new project.
From what I can gather (it seems that `npm ls` is not working properly in this expo project) it has the same version (`1.13.2`).

**Comment by shkfnly** [comment]
@M-i-k-e-l yeah it was on iOS and was on multiple tabs too now that I look at it. I think it has something to do with the FadedView too cause I cloned and removed that from the tabcontroller and it seems to work fine

**Comment by M-i-k-e-l** [comment]
@shkfnly, sorry for the delay. what do you mean by `FadedView`?
I've tried to replace `FadedScrollView` and I got the same result. Please note that this seems to happen only on the first render, so if you change anything you'll need to reload the app to see the bug again.

**Comment by M-i-k-e-l** [comment]
Hi @shkfnly, it's been a while so I'm closing this, if this is still relevant please open or leave a comment.
