### ISSUE TITLE
Modal enableModalBlur broken on Android

### ISSUE THREAD

**Issue by isaachinman** [wix/react-native-ui-lib#120]
The `Modal` component's `enableModalBlur` works great on iOS.

However, I get this critical breaking error on Android:

    Error: [ReactNativeBlur]: BlurView cannot contain any child views on Android. You should use "position: absolute" on the BlurView, and place other views in front of it.

This error occurs when I try to launch the modal in question. Previous to launching the modal, I see this yellow box warning:

    Warning: Failed prop type: The prop `viewRef` is marked as required in `BlurView` but its value is `undefined`.

Not entirely sure what's happening here, or if it's my fault, but it seems the `BlurView` setup with this `Modal` component is broken on Android.

Here's my code:

    <Modal
      visible={ui.modals.myModal.open}
      onRequestClose={this.handleClose}
      animationType='slide'
      transparent
      hardwareAccelerated
      enableModalBlur
    >
      <Container>
        <Header>
          <Left>
            <Button
              onPress={this.handleClose}
              transparent
            >
              <Text>Close icon</Text>
            </Button>
          </Left>
          <Body>
            <Text style={styles.headerTitle}>Choose something</Text>
          </Body>
          <Right />
        </Header>
        <Content contentContainerStyle={styles.content}>
          <Grid>
            <Row>
              <Col style={styles.imageContainer}>
                <Image
                  style={styles.image}
                  resizeMode='contain'
                  source={item.image}
                />
              </Col>
            </Row>
          </Grid>
        </Content>
      </Container>
    </Modal>

**Comment by Inbal-Tish** [comment]
I added a fix for the crash in Android. Please note that we are supporting modal blueView only in iOS at the moment

**Comment by isaachinman** [comment]
Okay, I wasn't aware the blurView is only for iOS. That's a shame!
