### ISSUE TITLE
Self created simple custom keyboard not working

### ISSUE THREAD

**Issue by sankomil** [wix/react-native-ui-lib#1208]
### Ask us any question

Hi, I wasn't sure if this should go as I think the problem is more from my end than anything else. I have been trying to create a simple, basic keyboard of my own to get a better understanding of it until the docs are updated. My keyboard look as seen below:
```
import React from 'react';
import { ScrollView } from '../../base-components'; // This is a react-native TScrollView 
import { Text } from '../text'; // This is a react-native Text converted in styled system component
import { KeyboardRegistry } from 'react-native-ui-lib/keyboard';

function KeyboardView() {
  return (
    <ScrollView contentContainerStyle={{ backgroundColor: 'purple' }}>
      <Text style={{ color: 'white' }}>HELLOOOO!!!</Text>
      <Text style={{ color: 'white' }}>Hey it works</Text>
    </ScrollView>
  );
}

KeyboardRegistry.registerKeyboard('MyKeyboardView', () => KeyboardView);
```
And my screen is:
```
import React, { useRef } from 'react';
import { Flex } from '../../base-components';
import { TextInput, Button } from 'react-native';
// import { Button } from '../button';
import { KeyboardRegistry, KeyboardAccessoryView } from 'react-native-ui-lib/keyboard';
import { KeyboardView } from './demo-keyboard';

export const Keyboard = () => {
  const ShowKeyboard = () => {
    KeyboardRegistry.requestShowKeyboard('MyKeyboardView');
    console.log('check');
  };

  const onButtonPress = () => {
    KeyboardRegistry.onItemSelected('KeyboardView', {
      message: 'item selected from KeyboardView',
    });
    ShowKeyboard();
  };

  const inputRef = useRef(null);

  return (
    <Flex>
      <TextInput
        ref={inputRef}
        style={{ borderWidth: 2, width: 100, marginBottom: 15 }}
        disableFullscreenUI={true}
      />
      <Button title="Press" onPress={() => onButtonPress()} />
      <KeyboardAccessoryView
        kbComponent={KeyboardView}
        kbInputRef={inputRef}
        revealKeyboardInteractive
      />
    </Flex>
  );
};
```
However, when I click the button or the TextInput, I only get the normal keyboard and not my new one. I know there are a few things I have not included, but those shouldn't affect the displaying of the keyboard right? Also, I am running this via Storybook, is that a possible issue for this? Thanks in advance!

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Can you take a look?

**Comment by M-i-k-e-l** [comment]
Hi @sankomil,
It's been a while since you've opened this, sorry for the delay and I hope this will help a bit.
If I understand the problem, you want to open your keyboard by default, I think this is a bit of an issue for us (see [this](https://github.com/wix/react-native-ui-lib/issues/1009) for a partial solution).
But, from what I've seen in your code you need to replace this `kbComponent={KeyboardView}` with `kbComponent={this.state.componentID}` where `componentID` is either `undefined` or `MyKeyboardView`,  I don't think you can simply keep it a constant `string` (and definitely not the component itself like in your code).

**Comment by sankomil** [comment]
Hey, thanks for getting back to me! So componentID would be whatever name I have registered my keyboard component with right? Can you please help me understand why I cannot keep it as a string? Thanks!

**Comment by dpadula** [comment]
Hey @sankomil is the keyboard working for you? I'm interested in the way you are using this. I need to make an hexadecimal keyboard (0-9 and A-F keys).
Thanks

**Comment by M-i-k-e-l** [comment]
@sankomil, yes, in your case it's `MyKeyboardView`.
TBH, I'm not sure why the constant string is not working, I'll have to look at it again, unfortunately it'll have to be in a later date.

**Comment by sankomil** [comment]
@M-i-k-e-l ah I see, no problem. So if I were to just store the string in a variable then that would be fine right?

@dpadula I had been working on a number pad when I ran into the error. However I have not had the chance yet to test it with that, and have only been trying to work with the minimal example I had given above.

**Comment by dpadula** [comment]
> @M-i-k-e-l ah I see, no problem. So if I were to just store the string in a variable then that would be fine right?
> 
> @dpadula I had been working on a number pad when I ran into the error. However I have not had the chance yet to test it with that, and have only been trying to work with the minimal example I had given above.

Hey @sankomil, thanks for reply, but I can't get the example to work either, is there a way to test this? The documentation on site is good but maybe with tutorial step by step. I can't see the native screen coming from below like native keyboards. Where I can find an example or sandbox working ?

**Comment by M-i-k-e-l** [comment]
@sankomil, no, as far as I know you'll need to change the object (var) sent to `kbComponent`, otherwise a `string` would be good enough.

@dpadula, we have demo [screens](https://github.com/wix/react-native-ui-lib/tree/master/demo/src/screens) for a lot of our components (in the demo app), [this is the folder](https://github.com/wix/react-native-ui-lib/tree/master/demo/src/screens/nativeComponentScreens/keyboardInput) for the `keyboardInput`.

**Comment by sankomil** [comment]
@M-i-k-e-l Got it, thanks. In that case shall I close the issue?

**Comment by M-i-k-e-l** [comment]
I've created an internal ticket, closing this.

**Comment by dpadula** [comment]
I'm sorry guys, did not see this on time. Maybe, if were possible,  can you create a tiny  funcional component example of mini keyboard? I can't make work the example indicated by @M-i-k-e-l. At least not as I expect. The keyboard that shows is the traditional on Android not the custom one.
Can you give me extra help?
Thanks in advance

**Comment by M-i-k-e-l** [comment]
Could you please open a new ticket? Since this does not seem related to the original issue.

**Comment by dpadula** [comment]
Yes, sorry. I'll post it in a new issue
