### ISSUE TITLE
Unable to resolve module `@react-native-community/picker`

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#1216]
```
"@react-native-picker/picker": "^1.9.11",
"react-native-ui-lib": "^5.21.0",
```

```
error: Error: Unable to resolve module `@react-native-community/picker` from `node_modules/react-native-ui-lib/src/optionalDependencies/PickerPackage.js`: @react-native-community/picker could not be found within the project.
```

**Comment by nanhlua96** [comment]
https://github.com/react-native-picker/picker/issues/82#issuecomment-747578526
I think it's not issue off this project

**Comment by saravanakumargn** [comment]
I am getting this error from `src/optionalDependencies/PickerPackage.ts`

After removed import of `'@react-native-community/picker'` it's working fine.

Before
```
let PickerPackage: any, CommunityPickerPackage: any;
try {
  PickerPackage = require('@react-native-picker/picker'); // New package
} catch (error) {
  try {
    CommunityPickerPackage = require('@react-native-community/picker'); // Deprecated package
  } catch (error) {}
}

export {PickerPackage, CommunityPickerPackage};
```

After
```
let PickerPackage, CommunityPickerPackage;

try {
  PickerPackage = require('@react-native-picker/picker'); // New package
} catch (error) {
}

export { PickerPackage, CommunityPickerPackage };
```

**Comment by nanhlua96** [comment]
in tsconfig.json you can check 
```
"moduleResolution": "node"
```
and yarn cache clean

**Comment by zhahaoyu** [comment]
> in tsconfig.json you can check
> 
> ```
> "moduleResolution": "node"
> ```
> 
> and yarn cache clean
does not work for me.

**Comment by ethanshar** [comment]
Hi @saravanakumargn which version `metro` do you have installed?

**Comment by zhahaoyu** [comment]
Any update?

**Comment by ethanshar** [comment]
> Please find the details below:
> 
> ```
> "react-native": "0.63.4",
> "metro-react-native-babel-preset": "^0.65.2",
> ```

Can you please check for `npm ls metro`

**Comment by ethanshar** [comment]
@saravanakumargn 
I created a new project with `react-native-ui-lib` and used few components from our library (View, Text, etc..)
I **didn't install** `@react-native-community/picker` and things seem to work as expected 

Anything else I'm missing?

**Comment by saravanakumargn** [comment]
My `npm ls metro`
```
└─┬ UNMET PEER DEPENDENCY react-native@0.63.4
  └─┬ @react-native-community/cli@4.13.1
    ├── metro@0.58.0
    └─┬ metro-config@0.58.0
      └── metro@0.58.0  deduped

npm ERR! peer dep missing: react-native@^0.59.5, required by react-native-fs@2.16.6
```

@ethanshar Without `react-native-ui-lib` `Picker` I think no issues. Can you please check with Basic `Picker` & `Picker.Item` ?

**Comment by zhahaoyu** [comment]
@ethanshar My metro version is `0.58.0` from the yarn.lock frile.

Also the library was running fine before I use `Card` component. I don't need `Picker` either, but it seems `Card` has a strong dependency on `Picker`. This also focuses me to install the extra pods that I don't need.

**Comment by ethanshar** [comment]
@saravanakumargn  @zhahaoyu 
Please make sure you have metro version 0.59 and above. 
This is not specified as a peer dependency cause I didn't thought anyone will lock this version. 

The issue is related to the new Optional Dependencies feature we added in the last version. 
You can read more about it [here](https://github.com/react-native-community/discussions-and-proposals/issues/120)
