### ISSUE TITLE
Not able to use RNUI 

### ISSUE THREAD

**Issue by hiharsh27** [wix/react-native-ui-lib#1221]
### Describe the bug

I newly created react native app after installation I installed RNUI using **npm install react-native-ui-lib**  and then I installed **npm i react-native-gesture-handler react-native-reanimated @react-native-community/blur @react-native-community/datetimepicker @react-native-community/netinfo @react-native-picker/picker** but I am getting too many error I just copied example from [https://wix.github.io/react-native-ui-lib/getting-started/usage](url) 

### Expected behavior

It should show login screen as mentioned in docs 

### Code snippet
A code snippet that reproduce the issue. 

import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
} from 'react-native';
import { View, TextField, Text, Button } from 'react-native-ui-lib';

const App = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
       >
          <View flex paddingH-25 paddingT-120>
            <Text blue50 text20>Welcome</Text>
            <TextField text50 placeholder="username" dark10 />
            <TextField text50 placeholder="password" secureTextEntry dark10 />
            <View marginT-100 center>
              <Button text70 white background-orange30 label="Login" />
              <Button link text70 orange30 label="Sign Up" marginT-20 />
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

export default App;

### Errors

 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
App@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:99376:54
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:68389:22
[Fri Mar 12 2021 14:27:30.146]  ERROR    Error: Requiring module "node_modules\react-native-ui-lib\src\components\button\index.js", which threw an exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
App@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:99376:54
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:68389:22
[Fri Mar 12 2021 14:27:30.146]  ERROR    TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "./components/button").default')

This error is located at:
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Mar 12 2021 14:27:30.147]  ERROR    TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "./components/button").default')

This error is located at:
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

### Device (please complete the following information)

 - Device: Oppo Realme 1 (Android)

### Additional Information
npm version - 7.6.3
node version - v14.16.0
react-native version - 0.63.4
react version - 16.13.1

**Comment by RatebSeirawan** [comment]
I believe it's due to the recent react-native-reanimated major release `2.0.0` which is backward compatible with a little change -> https://docs.swmansion.com/react-native-reanimated/docs/migration 
You can try installing react-native-reanimated `1.13.1` instead of `2.0.0`

**Comment by RatebSeirawan** [comment]
> I believe it's due to the recent react-native-reanimated major release `2.0.0` which is backward compatible with a little change -> https://docs.swmansion.com/react-native-reanimated/docs/migration
> You can try installing react-native-reanimated `1.13.1` instead of `2.0.0`

https://github.com/wix/react-native-ui-lib/issues/1217

**Comment by hiharsh27** [comment]
> > I believe it's due to the recent react-native-reanimated major release `2.0.0` which is backward compatible with a little change -> https://docs.swmansion.com/react-native-reanimated/docs/migration
> > You can try installing react-native-reanimated `1.13.1` instead of `2.0.0`
> 
> #1217

i removed react-native-reanimated latest version and installed as mentioned by you but now it is giving another error
`Error: Unable to resolve module ./reanimated2 from L:\Haryanvi developer\Freelancing\Ikenso react-native\mobile-app\ikensho\node_modules\react-native-reanimated\src\Animated.js:

None of these files exist:
  * node_modules\react-native-reanimated\src\reanimated2(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-reanimated\src\reanimated2\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import { Image, ScrollView, Text, View } from 'react-native';
  2 | import Easing from './Easing';
  3 | import AnimatedClock from './core/AnimatedClock';
  4 | import AnimatedValue from './core/AnimatedValue';`

**Comment by RatebSeirawan** [comment]
I'm currently installing it with the latest reanimated2 version, I was mistaken it's not the issue,
can you make sure you followed the reanimated 2 instructions correctly? https://docs.swmansion.com/react-native-reanimated/docs/installation

from what I see in the error message that you have
`Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.`

TurboModules are installed manually when adding reanimated 2, make sure it's correctly installed on Android

**Comment by hiharsh27** [comment]
> I'm currently installing it with the latest reanimated2 version, I was mistaken it's not the issue,
> can you make sure you followed the reanimated 2 instructions correctly? https://docs.swmansion.com/react-native-reanimated/docs/installation
> 
> from what I see in the error message that you have
> `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.`
> 
> TurboModules are installed manually when adding reanimated 2, make sure it's correctly installed on Android

I followed all steps but I am getting some error
` Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?, js engine: hermes
    at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:99367:66)
    at RCTView
    at RCTView
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:68389:22)
[Fri Mar 12 2021 15:59:09.310]  ERROR    Error: Requiring module "node_modules\react-native-ui-lib\src\components\textField\index.js", which threw an exception: Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?, js engine: hermes
    at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:99367:66)
    at RCTView
    at RCTView
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:68389:22)
[Fri Mar 12 2021 15:59:09.310]  ERROR    TypeError: Cannot read property 'default' of undefined

This error is located at:
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39), js engine: hermes
[Fri Mar 12 2021 15:59:09.320]  ERROR    TypeError: Cannot read property 'default' of undefined

This error is located at:
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39), js engine: hermes`


only thing that I didn't add is this line
-keep class com.facebook.react.turbomodule.** { *; }
because it is not mentioned in docs where to include this file

**Comment by RatebSeirawan** [comment]
@hiharsh27 Hi buddy try installing these exact versions and it should work, expo or bare RN project

```
  "peerDependencies": {
    "react": ">=16.0.0",
    "react-native": ">=0.63.4",
    "react-native-gesture-handler": ">=1.9.0",
    "react-native-reanimated": ">=1.13.2",
    "@react-native-community/blur": ">=3.4.1",
    "@react-native-community/datetimepicker": "^2.1.0",
    "@react-native-community/netinfo": "^5.6.2",
    "@react-native-picker/picker": "^1.9.4"
  },
```

**Comment by ethanshar** [comment]
@hiharsh27 
Im closing this. 

The errors are coming from react-native-reanimated v2. 
Either go over the installation steps mentioned here for reanimated v2
or install an older version.
