### ISSUE TITLE
`style` prop overrides style passed to component from `ThemeManager.setComponentTheme`.

### ISSUE THREAD

**Issue by izakfilmalter** [wix/react-native-ui-lib#1229]
### Ask us any question

Given the following code:
```tsx
ThemeManager.setComponentTheme('Button', (props: ButtonProps) => {
  return {
    style: { backgroundColor: 'red' },
  }
})

const Test = () => <Button label='Test Button' style={{marginLeft: 'auto'}} />
```

The styling provided by ThemeManager is overridden by the styling coming from the Button inside Test.

This behavior feels really unnatural for me coming from Material-UI where the global theme styling gets applied, and then what is in the components style prop merges in. 

I ended up doing the following monkey patch within `modifiers.js`:
```js
const getStyles = (style) => {
  if (Array.isArray(style)) {
    return style.filter(value => value !== undefined)
  } else if (typeof style === 'object' && style !== null) {
    return [style]
  }

  return []
}

export function getThemeProps(props = this.props, context = this.context) {
  //@ts-ignore
  const componentName = this.displayName || this.constructor.displayName || this.constructor.name;
  let themeProps;

  if (_.isFunction(ThemeManager.components[componentName])) {
    themeProps = ThemeManager.components[componentName](props, context);
  } else {
    themeProps = ThemeManager.components[componentName];
  }

  let forcedThemeProps;

  if (_.isFunction(ThemeManager.forcedThemeComponents[componentName])) {
    forcedThemeProps = ThemeManager.forcedThemeComponents[componentName](props, context);
  } else {
    forcedThemeProps = ThemeManager.forcedThemeComponents[componentName];
  }

  const themeStyle = themeProps ? themeProps.style : undefined
  const propsStyle = props ? props.style : undefined

  return { ...themeProps,
    ...props,
    ...forcedThemeProps,

    style: [...getStyles(themeStyle), ...getStyles(propsStyle)]
  };
}
```

I know this is a giant hack, but it does what I am expecting. I really like how MUI theming works as it lets me target every element within a component and set a global style for it, while letting me have instance specific styling as well.

**Comment by ethanshar** [comment]
Hi @izakfilmalter 
That's the reason we have two methods for setting components themes. 
`ThemeManager.setComponentTheme` & `ThemeManager.setComponentForcedTheme`

`ThemeManager.setComponentTheme` - will acts as the default theme and will be overridden completely when passing specific props. 

`ThemeManager.setComponentForcedTheme` - On the other hand will override what's being passed as a prop to the component. 
In this case, if you want to merge a default theme with a specific case styling you can do the following

```
ThemeManager.setComponentForcedTheme('Card', (props, context) => {
  return {
    containerStyle: [styles.defaultContainerStyle, props.containerStyle]
  };
});
```
Here you can see how I merged (in the order I want) the `Card` defaultContainerStyle and on top of it apply the `containerStyle` passed as a prop.
