### ISSUE TITLE
Search in Picker component

### ISSUE THREAD

**Issue by wangyi7099** [wix/react-native-ui-lib#1244]
### Describe the bug

When we has very much data in Picker component, the Children will be optimized in FlatList which is used in Picker  and searching will not work correctly.  How to resolve this problem?

**Comment by ethanshar** [comment]
@M-i-k-e-l 
I think it's the same issue we had with our Country picker. 
Do you think we can fix it in the OS code?

**Comment by ethanshar** [comment]
This will be released in v5.24.0
