### ISSUE TITLE
TextArea value

### ISSUE THREAD

**Issue by zaali33** [wix/react-native-ui-lib#1248]
The text area value doesn't get empty even if the value inside it is empty. So let's say I have a value for textarea which is equal to description state variable. Now, even if the description is equal to "" (empty string), it still shows me the value which I recently entered. 

### What I want?
      When the variable inside the value is empty, textarea must also show nothing.

### Sample Code
<TextArea 
    placeholder="Write description..." 
    value={description} 
    onChangeText={text => setDescription(text)} 
    style={{marginTop: 10}}
/>

Can you please fix it or if its related to the docs (in docs, may be there is a way which is miseed), can you please fix it by tomorrow as soon as possible? Thanks! I like your library a lot!!

**Comment by ethanshar** [comment]
Hi @zaali33 
It seems there's an issue with the "controlled" behavior of the component. 
I suggest using our new implementation of TextField -> `Incubator.TextField` 
https://wix.github.io/react-native-ui-lib/docs/Incubator.TextField/

You might need to style it to have a TextArea look, but it should behave as expected.
