### ISSUE TITLE
"Toast" doc may need to be updated

### ISSUE THREAD

**Issue by Pix-00** [wix/react-native-ui-lib#1249]
### Describe the bug
The props described in the doc does not match the component's props.
![image](https://user-images.githubusercontent.com/15878537/113371471-09492500-9399-11eb-8554-4fac94a6bd7a.png)
![image](https://user-images.githubusercontent.com/15878537/113371499-19f99b00-9399-11eb-948b-a1b0ffcd6b16.png)

### Component?
Toast

### Is there a general issue with the docs site?
No

### Is there an issue with the Expo snack app?
As the snack app not able to run ...... I guess yes ....

**Comment by M-i-k-e-l** [comment]
Hi @Pix-00,
I'm not sure why this is related to the snack (yes, we have issues there around components with native features), but I hope this will solve your issue.
