### ISSUE TITLE
More frequently-used components support?

### ISSUE THREAD

**Issue by likeSo** [wix/react-native-ui-lib#1255]
### Which component?

- `LoadingToast`: A rounded rectangle with an activity indicator at the screen center, with a mask, which prevents user interactions.
- `PopupMenu`: A context menu with an entry component, usually a button to trigger Menu display
- ...

### What is the new feature?

Undefined

### Code snippet

- `LoadingToast`: 
  -  `LoadingToast.showLoading({text: string, icon: ReactNode, duration?: number})`
  - `LoadingToast.showInfo({text?: string)`
  - `LoadingToast.showError({text?: string})`
  - `LoadingToast.dismiss()`
  - `LoadingToast.dismissAll()`

- `PopupMenu`
  -  `<PopupMenu entryPoint={<Button />} visible={visible}><PopupMenu.Item><Text>Popup Menu Item</Text></PopupMenu.Item></PopupMenu>`

**Comment by likeSo** [comment]
And we need a complete doc that can show us how to use a component and what will that component look like~
Example code should be clear and simple

**Comment by likeSo** [comment]
- <TextInput />: support textFormatters, such as input-numbers-only

**Comment by CyxouD** [comment]
I would like to see popup menu

**Comment by likeSo** [comment]
@CyxouD It seems... No. The owner closed this issue. There is a `Toast` component now, but no PopupMenu found. If you need a popup menu component right now, checkout React Native Paper and Native Base

**Comment by CyxouD** [comment]
@likeSo thank you! Also found component https://github.com/mxck/react-native-material-menu, but I haven't tested it yet

**Comment by likeSo** [comment]
@CyxouD It's better to use a component library, not a single component. 
For a better UI look, consider React Native Paper, but it has a very slow update cycle.
Native Base also has a Popup Menu component.
