### ISSUE TITLE
Picker  mode='MULTI' item selection not working with custom renderPicker in 5.22.0

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#1258]
### Describe the bug

When I use custom `renderPicker` in the `Picker` component with `mode='MULTI'` not able to select any item from the `Picker.Item` and `props.isSelected` always false.

```
"react-native-ui-lib": "^5.22.0",
```

**Comment by lidord-wix** [comment]
Hi @saravanakumargn,
Did it work in a previous version of `react-native-ui-lib`?
Can you please share the relevant snippet of your code?

**Comment by lidord-wix** [comment]
Hi @saravanakumargn,
Is the issue resolved?

**Comment by lidord-wix** [comment]
Closing this issue.
@saravanakumargn - Please reopen if you still have this bug.

**Comment by saravanakumargn** [comment]
Yes, It was working fine before v5.22.  and Not working in v5.27 also.

Not Working with "MULTI" and renderPicker
```
<Picker title={t('common:batches')}
  mode="MULTI"
  value={selectedStudentBatchRef.current ?? []}
  onChange={function(option: any) {
    console.log(option);
  }}
  renderPicker={function() {
    return (
      <View>
        <Button label={t('common:addBatch')} />
      </View>
    );
  }}>

...
```


Working without renderPicker
```
<Picker title={t('common:batches')}
  mode="MULTI"
  value={selectedStudentBatchRef.current ?? []}
  onChange={function(option: any) {
    console.log(option);
  }}>

...
```
