### ISSUE TITLE
Failed prop type: Invalid prop `imageSource` supplied to `Card.Image`.

### ISSUE THREAD

**Issue by isaachinman** [wix/react-native-ui-lib#126]
The `Card.Image` component does not seem to accept external URIs as `imageSource`:

    <Card.Image width={115} imageSource={uri} />

Where `uri` is something like `https://mycdn.com/image.jpg`.

**Comment by Inbal-Tish** [comment]
if source is a uri use it like this:
<Card.Image width={115} imageSource={{uri: uri}}
or:
<Card.Image width={115} imageSource={{uri: 'https://mycdn.com/image.jpg'}}

**Comment by isaachinman** [comment]
Okay, I ended up handrolling the card component because I wanted to use `AnimatedImage` instead. Thanks for this, probably add to docs?

**Comment by Inbal-Tish** [comment]
Ok. Thanks for the note!
