### ISSUE TITLE
Stepper increase 0.5

### ISSUE THREAD

**Issue by wangyi7099** [wix/react-native-ui-lib#1276]
Currently Stepper increase 1 every time I press  the add button. How can I increase 0.5 rather than 1. 
I hope the add  a `precise` prop to control how much I increase every time I click add button.

**Comment by Inbal-Tish** [comment]
@wangyi7099 We don't support this option at the moment, but it is a nice feature I'm sure we'll want to add. PRs are welcome!

**Comment by Inbal-Tish** [comment]
@wangyi7099 Hi. I added the feature you requested. Please follow this PR: https://github.com/wix/react-native-ui-lib/pull/1330

**Comment by Inbal-Tish** [comment]
@wangyi7099 See PR #1330
