### ISSUE TITLE
Demo Expo

### ISSUE THREAD

**Issue by binajmen** [wix/react-native-ui-lib#1283]
### Describe the bug

Demo on Expo Go doesn't seem to work

### To Reproduce

Scan the QR code to open Expo Go demo example

### Screenshots

![IMG_ED5B6DE3F64F-1](https://user-images.githubusercontent.com/15611419/116775441-415c8a00-aa63-11eb-8ab3-08bb0d3b1d25.jpeg)

### Device

 - Device: iPhone SE
 - OS: 14.4.2
 - Expo Go: 41.x (Supported SDKs: 38 to 41)

**Comment by ethanshar** [comment]
For iOS I suggest using expo-snack link

**Comment by binajmen** [comment]
Hi @ethanshar, could you be more specific? :)

**Comment by binajmen** [comment]
Ok found it in another post ;)
https://snack.expo.io/@ethanshar/rnuilib_snack
