### ISSUE TITLE
Keyboard doesnt open in a KeyboardAccessoryView keyboard

### ISSUE THREAD

**Issue by daxaxelrod** [wix/react-native-ui-lib#1300]
### Describe the bug
When a registered keyboard is open, and a textinput is focused within said component, the keyboard doesn't appear. Would be a useful feature to add a "filter" option inside the keyboard replacement.

Does the keyboard accessory completely disable the keyboard when viewing another "keyboard replacement"?

**Comment by mendyEdri** [comment]
Hi @daxaxelrod, thanks for reporting :)

Can you please elaborate or drop some code demo? 
not sure if I got it correctly.

Thanks!

**Comment by Nibycz** [comment]
Hello, 
is there any fix or workaround for this error ?

**Comment by bahamutxs** [comment]
The same happens to me in the React Native app I built. I reused the code given in the demo files and the custom keyboard only opens in Android, in iOS there's no response.
