### ISSUE TITLE
library not found for -IReactNativeUiLib

### ISSUE THREAD

**Issue by CodeSpent** [wix/react-native-ui-lib#1307]
My question is what does this error mean, exactly? Is there a native dependency that isn't mentioned that's necessary to use the library?

I've reinstalled a dozen times to no avail, and can't find any existence of `IReactNativeUiLib` in the repository, docs, or on StackOverflow.

```
ld: warning: directory not found for option '-L/Users/codespent/Library/Developer/Xcode/DerivedData/roomease-ccritsugesjcdqcqtcgtgjpdzqew/Build/Products/Debug-iphonesimulator/ReactNativeUiLib'
ld: library not found for -lReactNativeUiLib
```

**Comment by ethanshar** [comment]
Hi @CodeSpent 
Can you share how you installed the library?
In which step did you get this error? 

Our library also has some native modules that are require for some components and features. 
For example, the FeatureHighlight component requires you to install our native lib
Anyway, this should be transparent to you, the native lib is installed automatically with auto-link

**Comment by bogdan2510** [comment]
I get the same error. i use @nrwl/expo to add expo managed app to monorepo. on expo start i get `library not found for -lReactNativeUiLib`. and `clang: error: linker command failed with exit code 1 (use -v to see invocation)`
