### ISSUE TITLE
SegmentedControl undefined

### ISSUE THREAD

**Issue by OmanFerrer** [wix/react-native-ui-lib#1310]
### Describe the bug
I am getting 'undefined' when import 'SegmentedControl' component.

### Code snippet
`import {View, SegmentedControl, Text, Colors} from 'react-native-ui-lib';`

### Screenshots
![image](https://user-images.githubusercontent.com/7102601/118514610-40ca2180-b6fa-11eb-8618-abe0f1cb27cb.png)

**Comment by ethanshar** [comment]
@lidord-wix 
Can you take a look?

**Comment by lidord-wix** [comment]
Sure :)
@omanferrer which version of `react-native-ui-lib` are you using?

**Comment by OmanFerrer** [comment]
@lidord-wix 
`react-native-ui-lib v5.24.2`

**Comment by lidord-wix** [comment]
@OmanFerrer 
Can you please try to run `npm i react-native-ui-lib` and reset your cache?

**Comment by lidord-wix** [comment]
@OmanFerrer 
Is the bug resolved?

**Comment by OmanFerrer** [comment]
@lidord-wix resolved. Thx!!
