### ISSUE TITLE
TextField - bacground color input container

### ISSUE THREAD

**Issue by bagivk56** [wix/react-native-ui-lib#1318]
You can add styles from the theme to the innerContainer so that you can customize the container for the input separately.

<View
          style={[
            this.styles.innerContainer,
            hideUnderline && this.styles.innerContainerWithoutUnderline,
            {borderColor: underlineStateColor},
            {paddingTop: this.getTopPaddings()}
          ]}
        >
          {leadingIcon && <Image {...leadingIcon} style={[this.styles.leadingIcon, leadingIcon.style]}/>}
          {this.renderPrefix()}
          {this.renderPlaceholder()}
          {expandable ? this.renderExpandableInput() : this.renderTextInput()}
          {this.renderRightButton()}
          {this.renderRightIcon()}
          {expandable && this.renderExpandableModal()}
        </View>

**Comment by ethanshar** [comment]
Hi @bagivk56 
What's this issue about? 
Can you please add more details..

**Comment by bagivk56** [comment]
Immediately sorry for the English

Hi I have a TextField component. I would like to change the general style for the input itself. But having studied the structure of the component, I did not find such functionality.

For example, I need the input itself and its element such as: button, placeholder to be inside the customized block.

By customization, I mean the following: change in color, change in rounding, change in internal absences

**Comment by bagivk56** [comment]
![image](https://user-images.githubusercontent.com/81080810/119379650-2f27e180-bcd9-11eb-97dd-1b1418872b30.png)

**Comment by ethanshar** [comment]
Hi @bagivk56, 
Sorry for the late response. 
I recommend checking out our `Incubator.TextField` component. 
It has a more flexible layout and allows better customization. 

For instance, you can do the following to achieve your UI

```
<Incubator.TextField
  placeholder="Placeholder"
  leadingAccessory={<Text>$$ </Text>}
  fieldStyle={{backgroundColor: Colors.grey60, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 4}}
  trailingAccessory={<Button label="Button" link/>}
/>
```
