### ISSUE TITLE
iOS Bug with NativeModules.KeyboardTrackingViewTempManager.KeyboardTrackingScrollBehaviorNone

### ISSUE THREAD

**Issue by leamachado7** [wix/react-native-ui-lib#1322]
### Describe the bug

In android this does not happen, im using EXPO.
In iOS when opening the app through EXPO Go they get this 
![image](https://user-images.githubusercontent.com/80410434/119394870-1c95b400-bca9-11eb-92a9-8dbd1e8d633b.png)

Unhandled JS Exception: TypeError: null is not an object (evaluating 'y.NativeModules.KeyboardTrackingViewTempManager.KeyboardTrackingScrollBehaviorNone')

### To Reproduce
1. Go to the app in expo
2. Click try to open it 
3. Get exception

### Screenshots
app opens, splash screen

**Comment by Nibycz** [comment]
Hello, 
is there any fix or workaround for this ?

**Comment by ethanshar** [comment]
Unfortunately, the Keyboard component is one of our native components. 
And I believe Expo doesn't not support our native components. 
This is something should be support in Expo.
