### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name WheelPicker

### ISSUE THREAD

**Issue by sipian** [wix/react-native-ui-lib#1323]
### Describe the bug

I am creating a react-native project using an expo-managed workflow with the following dependencies in package.json. I use react-native-ui-lib for creating my UI components in the react-native app.

```
  "dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^1.0.1",
    "@react-native-picker/picker": "1.9.11",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "expo": "~41.0.1",
    "expo-app-loading": "^1.0.3",
    "expo-linear-gradient": "~9.1.0",
    "expo-status-bar": "~1.0.4",
    "lodash": "^4.17.21",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-logs": "^3.0.3",
    "react-native-material-ripple": "^0.9.1",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-reanimated": "~2.1.0",
    "react-native-responsive-fontsize": "^0.5.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-root-toast": "^3.2.1",
    "react-native-screens": "~3.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.0",
    "react-native-ui-lib": "^5.24.2",
    "react-native-web": "~0.13.12",
    "validator": "^13.6.0"
  },
```

When running the app on an android device using Expo-Go, I sometimes get the following error message in the expo logs.
```
Invariant Violation: Tried to register two views with the same name WheelPicker
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```
I am currently not using wheelpicker component anywhere in my app. Using grep wheelpicker only exists in 

`node_modules/react-native-ui-lib`

### Expected behavior
There should not be invariant violation crashes occurring in the expo app.

### Device (please complete the following information)

Device: Redmi Note 7S
OS: Android 10

**Comment by lidord-wix** [comment]
Hi @sipian,
Can you please update `react-native-ui-lib` to version `5.25.0` and try to run your app again?

**Comment by M-i-k-e-l** [comment]
Hi @sipian,
I think I've seen these type of bugs happen when saving a JS (or TS) file, I have not found a solution other than reloading the app, and I don't think it's related to our library, but to RN (although I did not find any validation to my suspicion).
My experience is not from expo, so please let me know if that works.
Moreover, if you are not using the said (or other) native component, you should look into using our [packages](https://wix.github.io/react-native-ui-lib/getting-started/setup), I think that may solve this for you altogether.

**Comment by sipian** [comment]
@M-i-k-e-l Could you please tell if such invariant violation errors cause app crashes/issues in production deployed RN apps ?

**Comment by M-i-k-e-l** [comment]
Not to my knowledge. Do you have this error in production?

**Comment by sipian** [comment]
Currently, I am in the development phase of the app. Will have to see after I deploy it in production

**Comment by M-i-k-e-l** [comment]
Do you get the error when saving your JS as I've suggested?
Did you try using our packages?

**Comment by ingjuanbejarano** [comment]
Hi there

I'm having the same issue described here, I'm using the version 5.26.0, and I installed the packages recommended for the page and later uninstalled them and installed packages recommended in other forums, all with the same result. as the publisher said is a random bug so is difficult for me to track or reproduce the error, I attach the log.

Invariant Violation: Tried to register two views with the same name WheelPicker
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0 
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:293:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:154:27 in invoke
at node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0      
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by M-i-k-e-l** [comment]
Hi @ingjuanbejarano,
1. I'm a little bit confused from your message, not sure what else is installed etc, perhaps you can add your `package.json`?
2. If I understand correctly this is not a consistent error, am I right?
3. Is this a development error or does it happen in production?

**Comment by ingjuanbejarano** [comment]
Hi @M-i-k-e-l 

this is my current package:

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-picker/picker": "^1.16.1",
    "expo": "~41.0.1",
    "expo-image-picker": "^10.1.4",
    "expo-status-bar": "~1.0.4",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-offline": "^5.8.0",
    "react-native-reanimated": "^2.1.0",
    "react-native-ui-lib": "^5.26.0",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

As I said, first I installed the peer dependencies recommended [here](https://wix.github.io/react-native-ui-lib/getting-started/setup), but had the same error so I decided to install these, but the result is the same.

The error is not consistent that's right, and so far I tested in development, when I've tested in prod I'll make an update

**Comment by M-i-k-e-l** [comment]
Sorry for the delay.
I'm assuming that you are not using our WheelPicker component (it's not supported in Expo).
If you're importing the entire library, I suggest you try importing [our packages](https://wix.github.io/react-native-ui-lib/getting-started/setup), this way the WheelPicker will not register.
