### ISSUE TITLE
Drawer example in expo is crashing

### ISSUE THREAD

**Issue by rosnaib11** [wix/react-native-ui-lib#1326]
Can't see drawer example in expo example keep crashing when you press. I wanna see what drawer looks like. Also on docs drawer (code example) doesn't redirect to the code. Also examples not in hook

**Comment by MoSattler** [comment]
Hey @rosnaib11, did you manage to get this working? 

I got the same problem, Drawer crashing with expo

**Comment by VityaSchel** [comment]
this is so ridicilous hahahhahahahhah I'm trying to just start writing application already 2 hours, this is how react native works: you spend 99% of time on solving stupid problems and 1% on reinstalling node_modules
