### ISSUE TITLE
Toast: Timer to dismiss after x seconds

### ISSUE THREAD

**Issue by juddey** [wix/react-native-ui-lib#134]
Currently the user has to dismiss the toast manually or we can dismiss it programmatically.

If we have a success message, we might just want to show this, give an option to dismiss, and if neither of those are selected, we auto dismiss the message after a predefined number of seconds (that'd be a prop, I think)

This would also be useful in the case of showing a message without giving an option to dismiss, and then it disappearing after the predefined number of seconds.

Thoughts?

**Comment by ethanshar** [comment]
make sense, we'll add it (:

**Comment by Inbal-Tish** [comment]
@juddey Hi. Please check out our last update with the added 'autoDismiss' prop. Thanks for the nice idea!

**Comment by juddey** [comment]
@Inbal-Tish Thank you, I appreciate it. I'm going update today, so I can use the new function :tada:
