### ISSUE TITLE
Error  when test the Keyboard Example

### ISSUE THREAD

**Issue by dpadula** [wix/react-native-ui-lib#1344]
### Describe the bug
TypeError: undefined is not an object (evaluating '_reactNativeUiLib.Assets.icons.demo.image')

### To Reproduce

1. Create an empty Expo react native application
2. Add all required packages of react-native-ui-lib
3. Add the two files provided in the example at:
   4. https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/nativeComponentScreens/keyboardInput/KeyboardInputViewScreen.js
   5. https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/nativeComponentScreens/keyboardInput/demoKeyboards.js
2. Add the screen at the main file App.js

import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import KeyboardInputViewScreen from './KeyboardInputViewScreen'

export default function App() {
  return (

    <KeyboardInputViewScreen></KeyboardInputViewScreen>
  );
}
Can you help me with this example and make it works ?
Thank you very much

**Comment by M-i-k-e-l** [comment]
Hi @dpadula,
You have a couple of issues:
1. The asset in question is not part of our library, but part of the demo app (see the configuration [here](https://github.com/wix/react-native-ui-lib/blob/master/demo/src/configurations.js)).
2. More importantly: even if you fix the above problem, our `Keyboard` components are native components, and you won't be able to use them in Expo AFAIK :/

Best reagards,
Miki

**Comment by dpadula** [comment]
Oh Ok I see! Thanks agian!
Now let me ask you something: once this is sorted, how should I use the screen? What I need is to type every key and then put the values on a TextInput react native component.
Is that possible with the example you gave me ?

**Comment by M-i-k-e-l** [comment]
I do know what exactly you are trying to do, but it sounds like it is possible with what I've sent you on the other issue.
But again, not in Expo.

I don't think I have the capacity for that, but thanks for the offer :)

**Comment by M-i-k-e-l** [comment]
Yes, I think it is.

**Comment by dpadula** [comment]
Hello @M-i-k-e-l it's been a while. Hope you are well, thanks for all your help. Maybe (if it is not too much to ask) I need a little more.
How should I handle if I had three TextInputs ? I need to write at the three TextInputs but with the same custom keyboard. I'm not sure how handle 3 when this kbInputRef supports only one ref for only one TextInput.
        <KeyboardAccessoryView

          **kbInputRef={this.textInputRef}**

          onRequestShowKeyboard={this.onRequestShowKeyboard}
          useSafeArea={useSafeArea}
        />

I have made one little project but there are some issues like:
1) Sometimes the native traditional keyboard shows up.
2) Sometimes the custom keyboard not shows at all

Just let me how I show you my example project and maybe you could tell me what / how to do .
Again...thank you very much 🤞

**Comment by M-i-k-e-l** [comment]
Hi @dpadula,
Please open a separate ticket for the new question if this is still relevant (with a link to the example project).
