### ISSUE TITLE
when swipe the drawer, the inner component's onPress func is triggered

### ISSUE THREAD

**Issue by surethink** [wix/react-native-ui-lib#1361]
### Describe the bug
I use Drawer to wrap a inner component that has onPress props, when I swipe from right to left, the onPress func is triggered

### Expected behavior
When swiping, the func of inner component should not be triggered

### Code snippet
`
                <Drawer
                    rightItems={rightButtons}
                    index={index}
                    useNativeAnimations
                >
                    <FeedMessage
                        message={item.message}
                        onPress={onPressFunc}
                    />
                </Drawer>
`
### Device (please complete the following information)
ios
react native 0.64
react-native-ui-lib 5.26.0

**Comment by ethanshar** [comment]
It works as expected, see video...
https://user-images.githubusercontent.com/1780255/124441860-d130f400-dd84-11eb-8751-f80504a26190.mov

This is the code I used
```
        <Drawer rightItems={[{text: 'ITEM'}]} useNativeAnimations>
          <TouchableOpacity
            bg-red30
            style={{height: 60}}
            activeOpacity={1}
            activeBackgroundColor={Colors.red60}
            onPress={() => console.warn('item pressed', Date.now())}
          >
            <Text>TOUCHABLE</Text>
          </TouchableOpacity>
        </Drawer>
```

**Comment by surethink** [comment]
> It works as expected, see video...
> https://user-images.githubusercontent.com/1780255/124441860-d130f400-dd84-11eb-8751-f80504a26190.mov
> 
> This is the code I used
> 
> ```
>         <Drawer rightItems={[{text: 'ITEM'}]} useNativeAnimations>
>           <TouchableOpacity
>             bg-red30
>             style={{height: 60}}
>             activeOpacity={1}
>             activeBackgroundColor={Colors.red60}
>             onPress={() => console.warn('item pressed', Date.now())}
>           >
>             <Text>TOUCHABLE</Text>
>           </TouchableOpacity>
>         </Drawer>
> ```
yeah, my code works now, but  I have done nothing to it

thank you for the reply. I will reopen the issue if there is new evidence

**Comment by letrunghieu0803** [comment]
I have same issue, and use useNativeAnimations still don't work.
I fixed this by way: 
   const [isDisable, setIsDisable] = useState(false);
  <Drawer 
      onSwipeableWillOpen={() => {
        setIsDisable(false);
      }}
      onSwipeableWillClose={() => {
        setIsDisable(false);
      }}
      onDragStart={() => {
        setIsDisable(true);
      }}
>
  <TouchableOpacity
        onPress={isDisable ? () => {} : onPress}>
   ...
  </ TouchableOpacity>
  </Drawer>
