### ISSUE TITLE
Picker - Allow disabling (Add a prop 'disable' )

### ISSUE THREAD

**Issue by NileshPatel17** [wix/react-native-ui-lib#1370]
### Which component?
Picker
### What is the new feature?
to be able to disable the picker
### Code snippet
```javascript
<Picker disabled={true} />
```

**Comment by ethanshar** [comment]
Hi @NileshPatel17 
Try passing `editable` with false. 
The Picker input is based on a TextField so this prop works for it as well

**Comment by netsmertia** [comment]
@ethanshar It is not working in case custom `renderPicker` picker is provided.

**Comment by ethanshar** [comment]
> @ethanshar It is not working in case custom `renderPicker` picker is provided.

@lidord-wix  Can yo u take a look?

**Comment by lidord-wix** [comment]
@netsmertia 
Passing `editable={false}` works for me also when I use a custom `renderPicker`.
Can you share a code snippet of your `Picker` where it doesn't work?

**Comment by lidord-wix** [comment]
Closing the issue since it's already fixed.
