### ISSUE TITLE
Picker - Add dark mode support

### ISSUE THREAD

**Issue by lucswart** [wix/react-native-ui-lib#1371]
### Which component?
Picker

### What is the new feature?
Able to customise the default modal to integrate it with dark mode.

### Code snippet
```
<Picker modalProps={{
  style: { backgroundColor: Colors.screenBG } 
}}
```

**Comment by AlixH** [comment]
Up, I am using your lib because native base styles are broken on Android for the Picker

**Comment by lucswart** [comment]
Any update on this topic?

**Comment by AlixH** [comment]
I found a good alternative, react-native-select-dropdown, https://github.com/AdelRedaa97/react-native-select-dropdown/issues

**Comment by MayMyatThu1995** [comment]
I cannot use PickerModalProps to update backgroundColor in Picker (Version-6.9.0)
