### ISSUE TITLE
Provide documentation on how to use `withScrollEnabler`

### ISSUE THREAD

**Issue by awartani** [wix/react-native-ui-lib#1373]
Thank you for the great work!

My Typescript knowledge is very limited, I couldn't figure out how `withScrollEnabler` should be used. It would be great if you can explain how should we use it? and what does it do exactly?

Note: `withScrollEnabler` section inside Expo demo doesn't do anything (kind of broken)

We would like to use `ScrollView` but disable scrolling if device dimensions are big enough and no need to enable scrolling

**Comment by ethanshar** [comment]
Till we fixed the docs. 
Here's a link to the component example screen 
https://github.com/wix/react-native-ui-lib/blob/b7735b0777acb1341b0fdd3528fe39254bb6fa30/demo/src/screens/componentScreens/WithScrollEnablerScreen/index.tsx#L106
https://github.com/wix/react-native-ui-lib/blob/b7735b0777acb1341b0fdd3528fe39254bb6fa30/demo/src/screens/componentScreens/WithScrollEnablerScreen/AutoLockFlatList.tsx#L1

**Comment by awartani** [comment]
@ethanshar thanks for the reference. It would be great if you explain what does `withScrollEnabler` do exactly

**Comment by ethanshar** [comment]
When using it right, it helps with locking scroll behavior in Lists with content that is shorter than the overall list container size. 
Basically it solve the issue when you use a ScrollView for a screen, but the content doesn't necessarily overflows, therefor the scroll is not needed. 
@M-i-k-e-l correct me if Im wrong..

**Comment by M-i-k-e-l** [comment]
It does that, just don't forget to use the relevant props (`onContentSizeChange`, `,onLayout` and `scrollEnabled`; see the examples).

**Comment by M-i-k-e-l** [comment]
BTW, it seems that the screen is broken, thanks for letting us know - I've created a ticket for it.

**Comment by MotasemAghbar** [comment]
withScrollEnabler provides an implementation for (`onContentSizeChange`,`onLayout` and `scrollEnabled`) props that passed to `ScrollView` to control enable/disable scrolling based on content size.

The simplest way to use it is by creating a new component that wraps `ScrollView` with `withScrollEnabler`, then use the new component instead of `ScrollView`,  see `ScrollViewEnabler` component below:

```
import React from 'react';
import {ScrollView} from 'react-native';

import {withScrollEnabler} from 'react-native-ui-lib';

const ScrollViewEnabler = ({scrollEnablerProps: {scrollEnabled, onContentSizeChange, onLayout}, children, ...extra}) => {
  return (
    <ScrollView scrollEnabled={scrollEnabled} onContentSizeChange={onContentSizeChange} onLayout={onLayout} {...extra}>
      {children}
    </ScrollView>
  );
};

export default withScrollEnabler(ScrollViewEnabler);

```

**Comment by awartani** [comment]
Thank you, @MotasemAghbar 

Then we can use it as:
```javascript
<ScrollViewEnabler>
    <Text>some long text in here</Text>
</ScrollViewEnabler>
```
