### ISSUE TITLE
Some components are missing either manual or auto generated typings

### ISSUE THREAD

**Issue by daomtthuan** [wix/react-native-ui-lib#1377]
### Component
- AnimatedImage
- AnimatedScanner
- ColorPalette
- ColorSwatch
- DateTimePicker
- HighlighterOverlayView
- Keyboard
- KeyboardAwareListView
- KeyboardAwareScrollView
- SafeAreaInsetsManager
- SafeAreaSpacerView
- SelectableComponent
- TextField
- Wizard

Ref: `react-native-ui-lib\generatedTypes\index.d.ts`

### What's the issue?
All components that are missing typings
Can you add their typings next version?

**Comment by M-i-k-e-l** [comment]
Fixed typings linking:
ColorPicker
ColorPalette
ColorSwatch

Missing typings (still in Javascript):
AnimatedImage
AnimatedScanner
DateTimePicker
HighlighterOverlayView
Keyboard*
SafeAreaInsetsManager
SafeAreaSpacerView
SelectableComponent

TextField - has manual typings (need to test if it works, in any case this will be migrated to the new TextField soon.

Moved to typescript ([PR](https://github.com/wix/react-native-ui-lib/pull/1390)):
Wizard

**Comment by donnes** [comment]
Some components still missing export and types

**Comment by M-i-k-e-l** [comment]
Hi (all),
A lot of these have been fixed since, and some are much more complex.
I'm closing this, please open tickets on **specific** components\props you are missing.
