### ISSUE TITLE
MaskedInput - renderMaskedText() cannot set state

### ISSUE THREAD

**Issue by NikoMontana** [wix/react-native-ui-lib#138]
First I bind the function: `renderPrice` in the constructor:

`this.renderPrice = this.renderPrice.bind(this);`

In the function I am trying to set the input to signed numbers only by simple iteration. After the iteration I am setting the new signed number with `setState()`. It looks like this:

 ```
renderPrice(value) {
    const hasValue = Boolean(value && value.length > 0);

    let newText = "";
    if (hasValue) {
      let numbers = "0123456789";

      for (var i = 0; i < value.length; i++) {
        if (numbers.indexOf(value[i]) > -1) {
          newText = newText + value[i];
        }
      }

      if (newText === "") newText = "15";

      if (newText.length > 5) newText = newText.substring(0, 5);
    }

    this.setState({ task_posting_budget: newText });

    return (
      <View row center>
        <Text text30 dark50>
          -
        </Text>
        <Text text30 dark10={hasValue} dark60={!hasValue}>
          {hasValue ? newText : "15"}
        </Text>
        <Text text80 dark60>
          $
        </Text>
      </View>
    );
  }
```

`                    <MaskedInput
                      renderMaskedText={this.renderPrice}
                      caretHidden
                      keyboardType={"numeric"}
                    />`

The problem is that by opening this component/screen the app doesnt react anymore, because setState is bein called to often. 

I will try to find a workaround for this and post a solution if possible.

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
> scheduleUpdateImpl
>     index.bundle?platform=android&dev=true&minify=false:5483:109
> scheduleUpdate
>     index.bundle?platform=android&dev=true&minify=false:5480:38
> enqueueSetState
>     index.bundle?platform=android&dev=true&minify=false:4100:185
> setState
>     index.bundle?platform=android&dev=true&minify=false:8063:35
> componentWillReceiveProps
>     index.bundle?platform=android&dev=true&minify=false:78597:20
> callComponentWillReceiveProps
>     index.bundle?platform=android&dev=true&minify=false:4173:47
> updateClassInstance
>     index.bundle?platform=android&dev=true&minify=false:4199:155
> updateClassComponent
>     index.bundle?platform=android&dev=true&minify=false:4290:296
> beginWork
>     index.bundle?platform=android&dev=true&minify=false:4403:48
> performUnitOfWork
>     index.bundle?platform=android&dev=true&minify=false:5316:33
> workLoop
>     index.bundle?platform=android&dev=true&minify=false:5335:142
> _invokeGuardedCallback
>     index.bundle?platform=android&dev=true&minify=false:2476:23
> invokeGuardedCallback
>     index.bundle?platform=android&dev=true&minify=false:2450:41
> performWork
>     index.bundle?platform=android&dev=true&minify=false:5371:41
> batchedUpdates
>     index.bundle?platform=android&dev=true&minify=false:5519:116
> batchedUpdates
>     index.bundle?platform=android&dev=true&minify=false:2627:35
> batchedUpdatesWithControlledComponents
>     index.bundle?platform=android&dev=true&minify=false:2634:34
> _receiveRootNodeIDEvent
>     index.bundle?platform=android&dev=true&minify=false:6417:50
> receiveTouches
>     index.bundle?platform=android&dev=true&minify=false:6431:249
> __callFunction
>     index.bundle?platform=android&dev=true&minify=false:2085:47
> <unknown>
>     index.bundle?platform=android&dev=true&minify=false:1914:29
> __guard
>     index.bundle?platform=android&dev=true&minify=false:2056:11
> callFunctionReturnFlushedQueue
>     index.bundle?platform=android&dev=true&minify=false:1913:19

**Comment by NikoMontana** [comment]
Here is my solution (pretty obvious). My react skills are not that high though I think this could make some bad memory stuff.

`                    <MaskedInput
                      onChangeText={value =>
                        this.setState({
                          task_posting_budget: this.getSignedNumbers(value)
                        })
                      }
                      renderMaskedText={this.renderPrice}
                      caretHidden
                      keyboardType={"numeric"}
                    />`


```
  getSignedNumbers = value => {
    const hasValue = Boolean(value && value.length > 0);

    let newValue = "";
    if (hasValue) {
      let numbers = "0123456789";

      for (var i = 0; i < value.length; i++) {
        if (numbers.indexOf(value[i]) > -1) {
          newValue = newValue + value[i];
        }
      }
    }

    if (newValue === "") newValue = "15";
    if (newValue.length > 5) newValue = newValue.substring(0, 5);

    return newValue;
  };

  renderPrice(value) {
    const hasValue = Boolean(value && value.length > 0);

    var newValue = this.getSignedNumbers(value);

    return (
      <View row center>
        <Text text30 dark50>
          -
        </Text>
        <Text text30 dark10={hasValue} dark60={!hasValue}>
          {hasValue ? newValue : "15"}
        </Text>
        <Text text80 dark60>
          $
        </Text>
      </View>
    );
  }
```

**Comment by ethanshar** [comment]
You can't `setState` inside a render function, it will create an infinite loop. 
setting state are usually located inside callback like `onChange`, `onLayout` or react life cycle methods (componentWillRecieveProps, etc..)
