### ISSUE TITLE
Picker custom modal + search

### ISSUE THREAD

**Issue by ScareCrow95** [wix/react-native-ui-lib#1398]
Hello, 

In the docs for using a picker I did find the snippet for using a custom modal, however I couldn't figure out how to add a custom search or infact any kind of search in the custom modal. Can some one please direct me on how to use the `renderCustomSearch` prop of the Picker?

**Comment by lidord-wix** [comment]
Hi @ScareCrow95,
You can pass your own search component to the `renderCustomSearch` prop of the picker component. 
For example, you can render a search button as your custom search component that way:
```
<Picker
    ...
    showSearch
    renderCustomSearch={() => <Button onPress={() => this.setState({searchValue: !this.state.searchValue})} label={'Search'}/>}
    ...
    >
       {_.map(this.state.searchValue ? longOptions : options, option => (
          <Picker.Item key={option.value} value={option} disabled={option.disabled}/>
        ))}
</Picker>

```
Don't forget to pass the `showSearch` prop as well. :)
