### ISSUE TITLE
example has error

### ISSUE THREAD

**Issue by guanbiao33** [wix/react-native-ui-lib#140]
![qq 20180413111810](https://user-images.githubusercontent.com/16236310/38715195-4cc0a180-3f0c-11e8-988f-f9b7ccb7110e.png)
how can i fix this problem,thank you.

**Comment by ethanshar** [comment]
Hey @guanbiao33, when/where do you get this error? which device are you running on?

**Comment by guanbiao33** [comment]
![1](https://user-images.githubusercontent.com/16236310/38933610-0f4a7c1a-434c-11e8-9585-43619b432548.png)
![2](https://user-images.githubusercontent.com/16236310/38933613-0fec71b4-434c-11e8-951a-d607e3fa5f79.png)


device was genymotion ,android api was 16

**Comment by ethanshar** [comment]
fixed with PR #241
