### ISSUE TITLE
Components with RN Text should accept allowFontScaling prop

### ISSUE THREAD

**Issue by vinceprofeta** [wix/react-native-ui-lib#1406]
### Which component?
Components with a label or that render Text. Chip in this case

### What is the new feature?

Our user base is often increases the text size on their iPhone, we want to set a max. Chip does not allow us to set a max.

### Code snippet

add a allowFontScaling to chip and other components
allowFontScaling={bool || number}

**Comment by ethanshar** [comment]
@vinceprofeta 
Do you wish to set allowFontScaling to all text elements in the app? or specifically to the chips label?
If this is a global behavior, you can set the default prop value on the Text component.. 

Anyway, adding a `labelProps` prop definitely make sense..

**Comment by vinceprofeta** [comment]
A global setting makes sense for now, but might want more control later on. @ethanshar interesting. Can you elaborate on "**you can set the default prop value on the Text component..**"

**Comment by ethanshar** [comment]
You don't even need to use our ThemeManager api, you can just do this...

```
import {Text} from 'react-native';

Text.defaultProps = {
  ...Text.defaultProps,
  allowFontScaling: false
};
```
