### ISSUE TITLE
How to validate Incubator TextField on button click?

### ISSUE THREAD

**Issue by rubek-joshi** [wix/react-native-ui-lib#1418]
I have a screen in which the `<Incubator.Textfield />` is not automatically focused. I have put the `required` text in validation but how do I validate when the user clicks on the sign up button directly? Am I suppose to handle this manually?

**Comment by ethanshar** [comment]
You mean validation using ref for instance?

**Comment by ethanshar** [comment]
you can now pass `ref` and use the `validate` method
