### ISSUE TITLE
Picker dialog close button is overlapped by topbar

### ISSUE THREAD

**Issue by max-frai** [wix/react-native-ui-lib#1421]
`"react-native-ui-lib": "^5.27.0"`

Default code for picker from examples.  Crossbar for closing dialog is overlapped by topbar with time. How to add margin top for dialog?

     <Picker
        value={undefined}
        topBarProps={{ title: "Some text" }}
        showSearch
        searchPlaceholder={"Search text"}
     >
        {longOptions.map((option) => (
           <Picker.Item
              key={option.value}
              value={option}
              disabled={option.disabled}
           />
        ))}
     </Picker>

<img width="454" alt="Screenshot 2021-07-22 at 17 31 17" src="https://user-images.githubusercontent.com/24208746/126656746-775bbf55-daf2-4dde-a892-0b8834477b8f.png">

**Comment by ethanshar** [comment]
Hi @max-frai,
This is how it renders on my simulator
![Screen Shot 2021-08-05 at 7 44 58](https://user-images.githubusercontent.com/1780255/128292204-4ce913ca-99cd-4dce-8901-ed9713c839bd.png)


Which navigation solution are you using? 
The Picker Modal (and Modal.TopBar) should already handle safe area (the top part of the device in this case)

Can you please share more details?

**Comment by nickdalts** [comment]
I'm facing the same issue in 5.29.0.

I'm using Expo SDK 42 and React Navigation. I'm using an inverted Expo StatusBar also

![Simulator Screen Shot - iPhone 11 Pro - 2021-08-23 at 23 24 25](https://user-images.githubusercontent.com/66555465/130527144-468f2b7c-5bae-47b0-aae2-b7604095813f.png)

**Comment by gioramies** [comment]
I'm having the same issue. Have not found a solution yet. I appreciate you help with this. Thank you very much. Great library!

![IMG-20210927-WA0008](https://user-images.githubusercontent.com/6133357/135008494-af725473-0867-467e-b647-76202066763d.jpg)

**Comment by ncortesm** [comment]
As a workaround, I used a help library to get the size of the status bar in ios.
I modified the modal/TopBar.js file and added the following styles.

` 
import 
{
    getStatusBarHeight
}  
from "react-native-iphone-x-helper";
`

`  container: {
    flexDirection: 'row',
    height: TOP_BAR_HEIGHT,
    paddingTop: getStatusBarHeight()
}`

**Comment by jgozner** [comment]
@ethanshar just wanted to note that this is still an issue. You can test this on your expo snack demo. https://snack.expo.dev/@ethanshar/rnuilib_snack?platform=ios&supportedPlatforms=ios,android

**Comment by M-i-k-e-l** [comment]
Hi @jgozner,
Please note that the our demo screen has not been changed, since expo is not our primary usage; the fix was:

> Modal.TopBar - allow sending useSafeArea (for expo or possibly react-navigation)

So in order to fix this in your project, you'll need to pass `useSafeArea` to the `Modal.TopBar`.

**Comment by jrnk** [comment]
Specifically, to fix this for the `Picker` in expo projects, just add the following prop:
`<Picker topBarProps={{ useSafeArea: true }} ...>`

**Comment by jgozner** [comment]
ah thank you!
