### ISSUE TITLE
Incorrect behaviour for Slider and all components using slider

### ISSUE THREAD

**Issue by kozillla** [wix/react-native-ui-lib#1441]
### Describe the bug
Slider and any of the components dependent on the slider (color picker, GradientSlider, etc ) does not behave correctly (tested on iOS)
When drag starts any other movement done in not slider direction increase slider value

### To Reproduce
use of any sliders 

### Expected behavior
on slider thumb drag, value should be smoothly increased/decresed 

### Code snippet
```
import React from 'react';
import {View} from 'react-native';
import {GradientSlider, Colors} from 'react-native-ui-lib';

export default function GeneralSettings() {
  return (
    <View style={{flex: 1}}>
      <GradientSlider
        type="hue"
        color={Colors.blue10}
        onValueChange={() => {}}
      />
    </View>
  );
}
```

### Screenshots
![Screen Recording 2021-07-31 at 4 30 28 pm](https://user-images.githubusercontent.com/16743156/127731348-2aa182df-b9fd-4daa-8545-3ffff62a2749.gif)
![colorpicker](https://user-images.githubusercontent.com/16743156/127732476-9bbdfe68-51fa-4ed6-9aa3-518196a3b262.gif)

### Device (please complete the following information)
 - Device: iPhone12
 - OS: iOS14.5

### Additional context
tested on brand new project, full dependencies list
```
  "dependencies": {
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-picker/picker": "^1.16.4",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.0",
    "react-native-ui-lib": "^5.28.0"
  },
```

**Comment by ethanshar** [comment]
This is fixed in v5.29.0

**Comment by scrapecoder** [comment]
still happing `react-native-ui-lib: ^6.23.1`

**Comment by ozdemiremrah** [comment]
@ethanshar still happening in ^7.1.0.

**Comment by ethanshar** [comment]
@Inbal-Tish 
Maybe the new Incubator.Slider fix these issues?

**Comment by toni1703** [comment]
yes i have this too
