### ISSUE TITLE
Component Exception on Hint when visible=false

### ISSUE THREAD

**Issue by RyanCloudFM** [wix/react-native-ui-lib#1447]
### Describe the bug
setting the 'visible' property to false on the Hint component causes a Component Exception; 'nothing was returned from render'.

### To Reproduce
Render any instance of Hint and set 'visible' to false

### Expected behavior
App displays without errors and component is not visible on screen

### Code snippet
```
const [renderHint, setRenderHint] = useState(true);

return (
  <View>
      <Hint
        message={"some message"}
        visible={renderHint}
        borderRadius={10}
        removePaddings
        onPress={() => setRenderHint(false)}
        targetFrame={{
          y: Dimensions.get('window').width / 2,
          x: 0,
          height: 10,
        }}
        color={colors.secondary}
      />
   </View>
)

```

### Screenshots

<img src="https://user-images.githubusercontent.com/33055882/128161264-a5bedf33-43c6-4aa2-be46-a23d55a5023b.png" alt="exception screenshot" width="293px" height="633px">

### Device (please complete the following information)
 - Device: [e.g. iPhone 12 simulator ]
 - OS: [e.g. iOS14.5]

**Comment by ianfowler** [comment]
This is specifically an issue related to using targetFrame. @RyanCloudFM You can get around this by creating a child view with the correct frame.

For react-native-ui-lib, I'm new to pull requests with git libraries like this and don't feel like learning it right now. To fix, all that would need to be done is change line 513 of src/components/hint/index.js from `return this.props.children` to `return this.props.targetFrame ? <></> : this.props.children`. Right now, there's no case in render for when visible===false and there are no children of the view.

**Comment by ethanshar** [comment]
@ianfowler 
Thanks, we'll try it out
