### ISSUE TITLE
Any way to remove overlay over carousel? 

### ISSUE THREAD

**Issue by saury** [wix/react-native-ui-lib#1469]
Sorry that I'm not able to find the way to remove that gradient overlay by reading doc or checking the source code. Anybody can help?

**Comment by ethanshar** [comment]
Hi @saury, 
What overlay do you mean exactly? 
Can you add a screenshot?

**Comment by saury** [comment]
@ethanshar 
Just like the one from showcase. 
![3.53.21.png](https://i.loli.net/2021/08/13/qFHU7f1sblJ3OCp.png)

**Comment by ethanshar** [comment]
The gradient overlay is part of the Image component and not the carousel. 
By default there is no overlay when using the Carousel component (or the Image component for that matter)

**Comment by saury** [comment]
@ethanshar , didn't aware that the overlay is from image (just copied the sample code and changed base on that). Thanks!
