### ISSUE TITLE
Hint is not appearing in right position?

### ISSUE THREAD

**Issue by KavithaMadhu31** [wix/react-native-ui-lib#1471]

**Comment by ethanshar** [comment]
Hi @KavithaMadhu31 
Can you share a screenshot and also a code snippet. 
In our demo app the component works

**Comment by KavithaMadhu31** [comment]
Hi @ethanshar,
i want to add Hint component inside scrollview, first time when i click hint, position is perfect, after scrolling  top/ down and then clicking the hint, it appears in same position. below added screenshots and code snippet.
![1](https://user-images.githubusercontent.com/37070871/129857200-9b3e7138-c650-4ff9-9d9c-77e5762ae556.png)
![2](https://user-images.githubusercontent.com/37070871/129857225-dbdb690c-ef3f-4fbf-a4fa-70bc4ec38a86.png)
![3](https://user-images.githubusercontent.com/37070871/129857242-5c1c4c7f-80d0-431f-8cb7-70aa7778b2b3.png)

code snippet:
const [isHintVisible, setIsHintVisible] = useState(false);
return(
 <View flex-1>
      <ScrollView style={tw('flex-1')}>
        <View bg-white style={{height: 300}}></View>
        <View bg-white centerH centerV style={{height: 300}}>
          <Hint
            style={{zIndex: 10}}
            visible={isHintVisible}
            message={'Hello'}
            messageStyle={{
              fontSize: 14,
              fontFamily: 'Nunito',
              fontWeight: '700',
              lineHeight: 18,
            }}
            onBackgroundPress={() => setIsHintVisible(false)}
            useSideTip={true}>
            <TouchableOpacity onPress={() => setIsHintVisible(true)}>
              <View padding-v1>
                <HintSvg />
              </View>
            </TouchableOpacity>
          </Hint>
        </View>
        <View bg-white style={{height: 300}}></View>
        <View bg-white style={{height: 300}}></View>
    </View>
);

**Comment by Inbal-Tish** [comment]
@KavithaMadhu31 Hi. Thank you for reporting. I'm working on this bug, hopefully, soon I'll have an update.

**Comment by KavithaMadhu31** [comment]
` const [isHintVisible, setIsHintVisible] = useState(false);
<View flex-1>
      <ScrollView style={tw('flex-1')}>
        <View bg-white style={{height: 300}}></View>
        <View bg-white centerH centerV style={{height: 300}}>
          <Hint
            visible={isHintVisible}
            message={'Hello'}
            onBackgroundPress={() => setIsHintVisible(false)}
            useSideTip={true}>
            <TouchableOpacity onPress={() => setIsHintVisible(true)}>
              <View padding-v1>
                <HintSvg />
              </View>
            </TouchableOpacity>
          </Hint>
        </View>
        <View bg-white style={{height: 300}}></View>
        <View bg-white style={{height: 300}}></View>
     </ScrollView>
    </View>`

**Comment by KavithaMadhu31** [comment]
Sure, Thanks @Inbal-Tish
