### ISSUE TITLE
Incubator.TextField validation not executed when value changed programmatically

### ISSUE THREAD

**Issue by lioryemini** [wix/react-native-ui-lib#1477]
### Bug
Incubator.TextField - Validation not executed when value changed programmatically

### To Reproduce
For example, change the `value` property programmatically by setting it to empty string:
1. Add Incubator.TextField component and make this field validation 'required'.
2. Type some string to make it valid.
3. Change the `value` property **programmatically** (not by typing!), by setting it to empty string. ("clear button" for example)

**As a result, this field will still be valid.** 

### Expected behavior
On every change of `value` property, the field validation should be checked, according the `validate` property rules, and the `validateOnChange` event should be fired.

### Additional context
Please notice, that this bug is a sort of completion of a previous bug fix #1426  that fixed by @mendyEdri.
This previous bug fix solve another problem, and do a `setValue` on every change of `props.value`. 
The missing part is that validation check is also needed there, every time the `value` state changed.

[related changes](https://github.com/wix/react-native-ui-lib/pull/1426/files/3f68ae9689c353e92884aa43ce76355c24333428)

### Suggested Fix
In file: "src/incubator/TextField/useFieldState.ts"
I figured that the `validateField` method, not executing when `value` changed programmatically.
It can be simply fixed by adding useEffect that listen to `value` state, for executing the `validateField` method on every change.
```js
  useEffect(() => {
    validateField();
  }, [value]);
```

Like so:
![image](https://user-images.githubusercontent.com/8045135/129879065-5b32b2a9-00eb-4f0a-bd01-b1d691e9a738.png)

**Comment by ethanshar** [comment]
This is fixed already

**Comment by lioryemini** [comment]
Hi @ethanshar, thanks for your reply.
It's not on master for sure.
The only places that execute the 'validateField' method are:
onStart, onBlur , onChangeText (not in cases of programmatically changes of 'value' state)
My suggested solution is very important.
Please promote this bug fix ASAP. It's critical for my project.

Thanks 🙏🏼

**Comment by lioryemini** [comment]
> This is fixed already

Hi @ethanshar, thanks for your reply.
It's not on master for sure.
The only places that execute the 'validateField' method are:
onStart, onBlur , onChangeText (not in cases of programmatically changes of 'value' state)
My suggested solution is very important, and it's a kind of blocker for me.
Please promote this bug fix ASAP. It's critical for my project.

Thanks 🙏🏼

**Comment by ethanshar** [comment]
Sorry, My bad.
I mixed this ticket with another one we fixed. 
I'll try to prioritize and fix it.

**Comment by lioryemini** [comment]
Hi, I thought I could see this fix on the next  minor version, but it's not in 5.30.1
Which version this fix will be please?

Thanks.

**Comment by lidord-wix** [comment]
Will be included in our next major version (which should be released tomorrow).
