### ISSUE TITLE
FeatureHighlight not working on android

### ISSUE THREAD

**Issue by iwalker7** [wix/react-native-ui-lib#1487]
### Describe the bug

FeatureHighlight is not working on Android 11. IOS works fine. 
Error: Exception is HostFunction: Malformed calls from JS: field sizes are different

### Screenshots

![IMG_20210823_000654](https://user-images.githubusercontent.com/29794449/130386603-568ccfa4-5f3d-4aa8-b280-699e94295e13.jpg)

### Device (please complete the following information)

 - Device: [Redmi note 9 pro 5G]
 - OS: [Android 11]

**Comment by MuhammedKpln** [comment]
Same problem here as well. Meanwhile on iOS it just works fine.

**Comment by atahansezgin** [comment]
make sure collapsable prop set false
