### ISSUE TITLE
Wizard.Step is missing the field 'index'

### ISSUE THREAD

**Issue by MakakWasTaken** [wix/react-native-ui-lib#1496]
### Component

Wizard.Step

### What's the issue?

It seems to be missing the index field. 
I get the warning below when trying to use it without:
```The prop `index` is marked as required in `Wizard.Step`, but its value is `undefined`.```

And I get a classic typescript error when trying with the property set.

**Comment by M-i-k-e-l** [comment]
I see what you mean now, maybe an RN \ typings change caused this to pop-up.
10x
