### ISSUE TITLE
TypeScript Definition Issue - KeyboardAwareScrollView

### ISSUE THREAD

**Issue by girishjjain** [wix/react-native-ui-lib#1499]
### Describe the bug
Module '"react-native-ui-lib"' has no exported member 'KeyboardAwareScrollView'.

### To Reproduce
Add below import to .tsx file:
```
import { Button, KeyboardAwareScrollView, Modal, RadioButton, RadioGroup, TextField, View } from 'react-native-ui-lib';
```

### Expected behavior
TypeScript should not complain about KeyboardAwareScrollView component

### Code snippet
```
import { Button, KeyboardAwareScrollView, Modal, RadioButton, RadioGroup, TextField, View } from 'react-native-ui-lib';
```

### Device (please complete the following information)
 - MacOS 11.5.2

**Comment by girishjjain** [comment]
`Keyboard.KeyboardAwareInsetsView` worked well for me. Thanks for your suggestion @ethanshar.

**Comment by kkhhaalil** [comment]
Hi @ethanshar, I'm getting `Invariant Violation: requireNativeComponent: "KeyboardTrackingViewTemp" was not found in the UIManager.` while using `<Keyboard.KeyboardAwareInsetsView/>`, do you know what might be the reason?

**Comment by tom555my** [comment]
Hi @MichalKrakow, I am also facing this issue.

**Comment by Inbal-Tish** [comment]
@girishjjain Hi. I think it's an export issue. Please follow my PR #2064

**Comment by M-i-k-e-l** [comment]
Hi,

@MichalKrakow, yes, you cannot use any of our **native** components in an expo project.

@kkhhaalil, @tom555my, @jtmozley  are you in an expo environment as well?
