### ISSUE TITLE
ListItem.Part does not exist

### ISSUE THREAD

**Issue by nickdalts** [wix/react-native-ui-lib#1512]
### Component
ListItem.Part

### What's the issue?
Property 'Part' does not exist on type 'ComponentClass<ListItemProps & { useCustomTheme?: boolean; }, any>'.

Using version 5.30.0

**Comment by anthonytoktokdoc** [comment]
Hi, any news on this issue ? this broke our app updating from 5.29 to 5.30

is it a breaking change ?

thanks

**Comment by MakakWasTaken** [comment]
#1529

**Comment by ethanshar** [comment]
Hi @MakakWasTaken 
Thank you for contributing! 

I'm releasing now a hotfix in v5.30.1
