### ISSUE TITLE
Using Colors or Typography with StyleSheet.create

### ISSUE THREAD

**Issue by derscott** [wix/react-native-ui-lib#1513]
### Using `Colors` or `Typography` with `StyleSheet.create`

In our scenario, we are using `Colors.loadColors` and `Typography.loadTypographies` to define own color keys and typographies. Like in your demo app, we call these functions in our root component before rendering anything else.

When using `Colors` or `Typography` inside `StyleSheet.create`, the objects still return the initial values. In development mode, triggering a refresh will make the correct styles appear. In production mode, the updated styles will never get applied.

When using the `Colors` or `Typography` object directly inside component's props, like 
```<Chip labelStyle={[styles.searchChipLabel, Typography.subheading]} />```, 
the styles are correctly applied.

Are we missing something? What is the correct way of injecting and loading own styles?

**Comment by ethanshar** [comment]
Hi @derscott,
I'd suggest loading colors, typographies and components themes before the app loads, before you import any screen or a component files. 
This should guarantee the various foundation presets are loaded before being used in stylesheets. 

Please try it out and let me know how it works.

**Comment by andrewBIsP** [comment]
Hi @ethanshar 
Could you tell me how to load correctly my colors, typographies and etc. Suppose, i have a config file with them, I just need to import it into my application root file, say "app.js" and that's it?

**Comment by ethanshar** [comment]
Yes, import them as soon as possible. 
Usually there's the index file that initiates the app (register the app component) 
I would import the configurations there.

**Comment by evg1n** [comment]
Hi,

Expo default entry file is `/node_modules/expo/AppEntry.js
`
I have tried the workaround above but it gets uglier with every step. Any elegant way to implement `Colors` or `Typography` in `StyleSheet.create()` ?
