### ISSUE TITLE
Invariant violation Error while trying to load SafeArea Spacer demo page

### ISSUE THREAD

**Issue by DiegoBM** [wix/react-native-ui-lib#1532]
### Describe the bug
When trying to open the SafeArea Spacer page from the demo app, the app crashes with the following error: 
```Invariant Violation: requireNativeComponent: "SafeAreaSpacerView" was not found in the UIManager.```

### To Reproduce
1. Open demo app
2. Click on 'Native' tab
3. Click on "SafeArea Spacer" option

### Expected behavior
The screen should open (or indicate to be iOS only, and even in that case it probably should fail gracefully like other iOS pages do)

### Device (please complete the following information)
 - Android emulator
 - OS: Windows 10 + Powershell

### Additional context
As far as I can tell, only an iOS native implementation has been provided, therefore when trying to render the native component on Android it does fail.

**Comment by ethanshar** [comment]
Hi @DiegoBM 
You are definitely right. 
The condition for render the native component or a standard view [here])(https://github.com/wix/react-native-ui-lib/blob/master/lib/components/SafeArea/SafeAreaSpacerView.tsx#L13) was incorrect 
Apparently something in RN api has changed that cause it to break. 
I will change the condition to explicitly render the native view only for iOS
