### ISSUE TITLE
color prop is not passed to GradientSlider in ColourSliderGroup

### ISSUE THREAD

**Issue by kozillla** [wix/react-native-ui-lib#1533]
### Describe the bug
color prop is not passed to <GradientSlider .../>  in ColorSliderGroup.js ,  resulting incorrectly setting initial slider values for ColorSliderGroup and all components using it (ColorPickerDialog , etc)  

### To Reproduce
pass initialColor prop to ColorPickerDialog component. Observe that for any initialColor values, initial sliders  values for 
ColorPickerDialog are always same (color representation is correct , only initial slider position is incorrect),
Easiest way to reproduce is to pass initialColor value as black `#000000` 

### Expected behavior
on ColorPickerDialog open , sliders (Hue , Lightness , Saturation) should correctly represent initial colour representation

### Code snippet
```
        <ColorPickerDialog
          visible={true}
          onDismiss={dis => {}}
          initialColor={"#000000"}
          onSubmit={(val: string) => {}}
          ...
        />
```

### Device (please complete the following information)
any Device 
any OS

### Additional context
https://github.com/wix/react-native-ui-lib/blob/e30ee05a13fd89089e381234685434ceb2d54451/src/components/slider/ColorSliderGroup.tsx#L90
Looks like the issue is in renderSlider function in ColorSliderGroup.js ,  passing ```color={this.props.initialColor}``` fix the problem

**Comment by r1jsheth** [comment]
@ethanshar Can I work on this?

**Comment by ethanshar** [comment]
@r1jsheth 
Definitely, you can assign yourself 👍

**Comment by ethanshar** [comment]
I was actually waiting for a PR. 
@r1jsheth Do you wish to submit a PR with a fix?

**Comment by r1jsheth** [comment]
Created this PR #1606

**Comment by kozillla** [comment]
hi @r1jsheth ,

thanks for PR !

did you test this fix ? the issue is that color is not passed for 

https://github.com/wix/react-native-ui-lib/blob/e30ee05a13fd89089e381234685434ceb2d54451/src/components/slider/ColorSliderGroup.tsx#L90


more info in ```Additional context``` section  in bug description.

**Comment by Inbal-Tish** [comment]
@kozillla Got it. Thanks! will be fixed promptly. See PR #1608
