### ISSUE TITLE
Carousel sensitivity?

### ISSUE THREAD

**Issue by isaachinman** [wix/react-native-ui-lib#154]
Hi there, wondering if it's possible to configure swipe sensitivity for the carousel component. I'm running into issues on Android where swipes _seem_ like they are far enough to the right/left side to trigger a page change, but do not. In general it feels like the threshold for swiping to trigger a page change is too high.

Can provide a screencap if necessary.

**Comment by Inbal-Tish** [comment]
The Carousel component is based on RN's ScrollView with pagingEnabled so the configuration is theirs.
