### ISSUE TITLE
Colors.setScheme works fine for Views but not for Text

### ISSUE THREAD

**Issue by DiegoBM** [wix/react-native-ui-lib#1548]
### Describe the bug
Trying to change the theme at runtime using Colors.setScheme works fine for View background, but not for Text color.

### To Reproduce
0. Create a new react native App
1. Use Colors.loadSchemes to create 'light' and 'dark' themes with screenBG and textColor properties, with values for both themes.
2. Create a View (with bg-screenBG) that contains a Text (with textColor) and a Switch to modify the Theme at runtime.
3. On the switch OnValueChange event, change a state variable that determines the theme and eventually call Colors.setScheme choosing one theme or the other depending on that state variable.
4. While running the app use the switch and you'll see the View changing it's color but not the Text

### Expected behavior
The Text componen should also adapt to the newly set scheme

### Device (please complete the following information)
 - Android emulator
 - OS: Windows 10 + Powershell

### Code sample
```
Colors.loadSchemes({
  light: {
    screenBG: Colors.white,
    textColor: Colors.grey10,
  },
  dark: {
    screenBG: Colors.grey10,
    textColor: Colors.white,
  },
});

const setTheme = (dark: boolean): void => {
  Colors.setScheme(dark ? 'dark' : 'light');
};

const App = () => {
  const [darkTheme, setDarkTheme] = useState(false);

  setTheme(darkTheme);

  return (
    <View flex center bg-screenBG>
      <Text textColor text10>
        Demo
      </Text>
      <Switch value={darkTheme} onValueChange={value => setDarkTheme(value)} />
    </View>
  );
};
```

### Additional context
Both themes display properly if I manually change the value of the state property and refresh.

Additionally the application does not react to a change in the Theme in Android settings like the libraries' Demo application does. I don't know if this is an issue or if there is something not documented to be done. I can raise a separate bug for this if necessary?

**Comment by ethanshar** [comment]
Hi @DiegoBM 
Thanks for reporting the issue. 

I found the problem. 
The recent feature than allows to manually set a scheme (instead of changing it thru the device) was not implemented all the way. 
I'll work on a fix and update

**Comment by DiegoBM** [comment]
Thank you @ethanshar  :)
