### ISSUE TITLE
not working on IOS

### ISSUE THREAD

**Issue by hasanal1995** [wix/react-native-ui-lib#155]
in compile time generate this error:
![screen shot 2018-05-07 at 4 17 59 pm](https://user-images.githubusercontent.com/32715055/39704827-48186642-5215-11e8-8804-ec8aaca41714.png)

**Comment by Inbal-Tish** [comment]
Hi. Can you check if you linked the library properly?

**Comment by hasanal1995** [comment]
@Inbal-Tish  yes im sure

**Comment by ethanshar** [comment]
Hey @hasanal1995, it's really difficult to understand what's the issue. 
can you try to reproduce it on our example project and let us know if you find something..

**Comment by cristianolopessantos** [comment]
Same problem. Anyone knows how to solve this?
