### ISSUE TITLE
Release version of the demo app does not work on android

### ISSUE THREAD

**Issue by DiegoBM** [wix/react-native-ui-lib#1556]
### Describe the bug
When trying to run the release version of the demo app the screen remains blank not showing absolutely anything. The debug version of the app that connects to the server works fine.

### To Reproduce
1. Run `npx react-native run-android --variant=release`
4. See blank screen

### Expected behavior
Demo app should launch

### Device (please complete the following information)
 - Android emulator
 - OS: Windows 10 + Powershell

### Additional context
Creating the release apk with `cd android && ./gradlew.bat assembleRelease`. and installing the apk manually, produces the same results

**Comment by ethanshar** [comment]
We never configured a release variant for the demo app cause we never release it as an official app. 
Why do you need to build it as a release?

**Comment by DiegoBM** [comment]
I see. My intention was to be able to run the demo sideways my app for reference, but I can't since I need metro server serving my app, therefore a needed a fully built version of the app. The one that you provide through expo on your main site seems to be outdated so it was not an option.

**Comment by gaithoben** [comment]
I tried to do the same as well. All in vain.

**Comment by ethanshar** [comment]
Ok, try this... 
We publish our demo app example screens as a separate npm package called `unicorn-demo-app`

In your own app you can render the main screen right next to your app. 
Worth to mention we use `react-native-navigation` for our internal navigation so if you're not using it you might need a different solution.
Let me know..

**Comment by DiegoBM** [comment]
Apologies, what I meant by "run the demo sideways my app" was being able to run both apps, not integrating the demo into my app, my bad.
What you mention could be a valid solution, but I'd rather not add any more unnecessary dependencies to my app, even if they could be removed later, I'm always wary that any new transient dependencies might affect the global behaviour of the app, that once removed you'll need to debug why it's not working now, if that makes sense. But failing everything I could do what you mention. If you could update the expo demo that you provide in the main site to the latest build of RNUI that could work for me as well.

**Comment by ethanshar** [comment]
Hi @DiegoBM 
For now I updated our [Expo-snack](https://snack.expo.dev/@ethanshar/rnuilib_snack?platform=ios&supportedPlatforms=ios,android) demo, please consider using it
