### ISSUE TITLE
TextField borderBottomWidth should be customize

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#1566]
### Which component?
`TextField`

### What is the new feature?

I want to change default `TextField` borderBottomWidth to `borderBottomWidth : StyleSheet.hairlineWidth`. It seems now we don't have the option to change as this is fixed 1 width.

### Code snippet

https://github.com/wix/react-native-ui-lib/blob/master/src/components/textField/index.js#L762

``` js
    innerContainer: {
      // flexGrow: 1, // create bugs with lineHeight
      flexDirection: 'row',
      justifyContent: centered ? 'center' : undefined,
      borderBottomWidth: 1,
```

**Comment by ethanshar** [comment]
Hi @saravanakumargn 
I would encourage you to use our new TextField implementation. 
The new TextField included in our Incubator
```
import {Incubator} from 'react-native-ui-lib'
const {TextField} = Incubator;
```

The new TextField offers more freedom with customizations 
try playing with the `fieldStyle` and `containerStyle` props

**Comment by saravanakumargn** [comment]
@ethanshar  This is Perfect. Thanks for your help.


``` ts
fieldStyle={props.validationMessage ? styles.withErrorUnderline : styles.withUnderline}

const styles = StyleSheet.create({
  container: {},
  withUnderline: {
    borderColor: Colors.black,
  },
  witherrorUnderline: {
    borderColor: Colors.red10,
  },
});
```

This way I managed my error color now. Is this fine or do we have any props available to change the color?.

**Comment by ethanshar** [comment]
the `fieldStyle` prop can accept a callback ((context: FieldContextType) => ViewStyle)
where `FieldContextType` contains info like `isFocused`, `isValid` and more.. 
based on that info you can return the relevant field style you wish

**Comment by mountain-hiker** [comment]
@ethanshar  I am trying to use the callback as you have mentioned, but am having no luck.

Am I missing something?

```
<Incubator.TextField
    fieldStyle={(context: any, props: any) => {console.log("here")}}>
</Incubator.TextField>
```

I would expect this to log to my console

**Comment by mountain-hiker** [comment]
Okay just found this! 

dynamicFieldStyle is the prop I needed not fieldStyle as that is now static only.
```
<Incubator.TextField
    dynamicFieldStyle={(context: any, props: any) => {console.log("here")}}>
</Incubator.TextField>
```

Per this pr: https://github.com/wix/react-native-ui-lib/pull/1682
