### ISSUE TITLE
Button background with gradient ?

### ISSUE THREAD

**Issue by KaKaVip** [wix/react-native-ui-lib#157]
As title?
how to config it ?

**Comment by ethanshar** [comment]
We don't really support gradient background for Button at the moment, feel free to PR with a solution.

**Comment by runninghead** [comment]
Been trying to Google anything regarding gradients in Wix today.
I can't beleive such a CSS-friendly and universally prevalent feature is missing from the standard Wix editor- so where is it?
All I see in the colour picker is flat colours.
