### ISSUE TITLE
Keyboard.KeyboardAccessoryView show error message

### ISSUE THREAD

**Issue by Adamcrg** [wix/react-native-ui-lib#1573]
### Describe the bug

when i use `const KeyboardAccessoryView = Keyboard.KeyboardAccessoryView;`
An error occurred
Unhandled promise rejection [RangeError: Maximum call stack size exceeded (native stack depth)]

### To Reproduce

1. `npx ignite-cli new PizzaApp`
2. `yarn add react-native-ui-lib`
3. add react-native-reanimated
4. `
import { Keyboard } from "react-native-ui-lib"
const KeyboardAccessoryView = Keyboard.KeyboardAccessoryView
`
5. See error

### Expected behavior

no error tip

### Code snippet

https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/nativeComponentScreens/keyboardInput/KeyboardInputViewScreen.js

### Screenshots

![image](https://user-images.githubusercontent.com/34224261/135048934-afdd1343-5b09-4c61-bebf-73c27a309faa.png)

### Device (please complete the following information)

 - Device: [e.g.  oneplus 6]
 - OS: [e.g. android 11]

**Comment by thanhdatpd** [comment]
+1

**Comment by superandrew213** [comment]
@thanhdatpd @Adamcrg did you figure out this issues?
