### ISSUE TITLE
Android version of WheelPicker is broken since 5.30.0

### ISSUE THREAD

**Issue by nikelin** [wix/react-native-ui-lib#1586]
After upgrading to 6.0.0, the Android build  (i.e. `./gradle clean build` from `./android`) of the app is failing with the following error:
```
\node_modules\react-native-ui-lib\lib\android\src\main\res\layout\wheel_picker.xml:2: Error: Class refe
renced in the layout file, com.wix.reactnativeuilib.wheelpicker.ThemedNumberPicker, was not found in the project or the libraries [MissingClass] <com.wix.reactnativeuilib.wheelpicker.ThemedNumberPicker...
```

I'm assuming this is due to the typo in the layout file which is referencing non-existing `ThemedNumberPicker`.

**Comment by ethanshar** [comment]
Consider using our Incubator.WheelPicker component instead

**Comment by sapkra** [comment]
@nikelin Hi, were you able to fix this issue, because I came across the same error now?

**Comment by Svarto** [comment]
@nikelin @ethanshar @sapkra same issue for me, anyone have a solution?

@ethanshar the error comes even when the WheelPicker component is not used in the package. It is just from having 'react-native-ui-lib' installed as a package in the project.
