### ISSUE TITLE
ListItem touch effect

### ISSUE THREAD

**Issue by safindr** [wix/react-native-ui-lib#16]
After change component in ListItem from TouchableHighlight to TouchableOpacity props onHideUnderlay and onShowUnderlay not available.

**Comment by ethanshar** [comment]
Hey @safindr, 
the onHideUnderlay and onShowUnderlay were used internally. 
I don't think you could have pass this props before. 
Just to understand the issue better so I can fix/improve the component. 
What's exactly missing for you?

**Comment by safindr** [comment]
In file /src/components/listItem/index.js used onHideUnderlay and onShowUnderlay on TouchableOpacity, but this props not available in TouchableOpacity and TouchableWithoutFeedback; 
This happened after the replacement of component TouchableHightlight by component TouchableOpacity;

**Comment by ethanshar** [comment]
Yes, I saw that. 
I will remove onHideUnderlay and onShowUnderlay from the component, unless it's something you need.

**Comment by safindr** [comment]
Yes, they can be removed, but this does not solve the problem. After replacing the component, the effect was lost when pressed, I would really like you to return it using TouchableOpacity

**Comment by ethanshar** [comment]
@safindr, 
Ok instead of removing it I added a **containerElement** prop. 
You can use it to send a different Touchable wrapper, for instance TouchableHighlight and then the underlay behavior will work.
also added **underlayColor** prop to control the color

```
<ListItem height={50} containerElement={TouchableHighlight} underlayColor="red"/>
```
