### ISSUE TITLE
Can we add a keyboardVerticalOffset to KeyboardTrackingView?

### ISSUE THREAD

**Issue by bneigher** [wix/react-native-ui-lib#1600]
### Which component?
KeyboardTrackingView

### What is the new feature?
It would be nice to be able to define an offset (top of the screen to bottom of "View" so that if there is anything below a component that should NOT move to accommodate the keyboard - the avoiding components know not to move too far up the screen.

### Code snippet
```javascript
<KeyboardTrackingView
   keyboardVerticalOffset={180}
>
  {this.props.children}
</KeyboardTrackingView>
```

This behavior could be similar to KeyboardAvoidingView's [property](https://reactnative.dev/docs/keyboardavoidingview#keyboardverticaloffset).

![ezgif-7-b140f587e14b](https://user-images.githubusercontent.com/4627728/137057830-c0db9a1c-c067-4b6c-b360-0e0e1c2d7509.gif)

Perhaps this is already supported with `addBottomView` but no where is this property documented...

**Comment by pinchez254** [comment]
This issue is same in IOS for KeyboardAccessoryView component.

**Comment by ethanshar** [comment]
@Inbal-Tish 
Is the new feature solve this issue by any chance? 
If it does, can you instruct the users on how to use it

**Comment by Inbal-Tish** [comment]
@bneigher Hi. Try passing 'ususBotomTabs' prop and see if it solves the issue.
