### ISSUE TITLE
VSC does not show any props on TextField

### ISSUE THREAD

**Issue by softshipper** [wix/react-native-ui-lib#1611]
Hi all,

VSC can not find any props on TextField:
![Screenshot from 2021-10-19 10-46-32](https://user-images.githubusercontent.com/56756949/137875986-aaf11e96-c625-4733-ad57-22b8c8cd176e.png)

It seems, that the types do not work properly. 

Version:
 "react-native-ui-lib": "^6.1.2"

Best regards,
Softshipper

**Comment by kieran-osgood** [comment]
Looking at the types (if you right click on the <TextField /> and select go to definition it'll take you there) you'll see that there are some components that they're aware aren't backed with typings:

`node_modules/react-native-ui-lib/generatedTypes/index.d.ts`:
```
/* All components that are missing either manual or auto generated typings */
export const AnimatedImage;
export const AnimatedScanner;
export const DateTimePicker;
export const TextField;
```

I'm not sure the exact reasons but based on https://github.com/wix/react-native-ui-lib/issues/1603 they're deprecating the `TextField` component in favour of Incubator.TextField: https://wix.github.io/react-native-ui-lib/docs/Incubator.TextField/ which does have typings setup so I'd suggest you go forward with that one instead as I doubt typings will be added for the soon to be deprecated component.
