### ISSUE TITLE
How can i change gradientColor (left-right) of TabController.TabBar

### ISSUE THREAD

**Issue by aliburhankeskin** [wix/react-native-ui-lib#1617]
How can i change gradientColor (left-right) of TabController.TabBar.

I want to change the white gradient color formed on the right and left of TabController.TabBar.

How can I do it ? 

Thanks for helping.

`
     <TabController.TabBar
          indicatorStyle={{ backgroundColor: Color().primary }}
          indicatorInsets={0}
          selectedLabelColor={Color().primary}
          centerSelected
          enableShadow
          backgroundColor="red"
        />
`

**Comment by ethanshar** [comment]
Hi @aliburhankeskin 
When you say you want to change it, what do you mean? 
Change its color? Remove it?

**Comment by Mohamed-kassim** [comment]
@ethanshar one of the use cases for dark theme
As the tab controller support only light gradient
I passed a prop with tint color to the gradient image and changed it manually 
This applies for floating actions gradient too

**Comment by ethanshar** [comment]
@Mohamed-kassim 
Care to submit a PR? (:
