### ISSUE TITLE
are we able to pass a function as a prop to KeyboardAccessoryView via kbInitialProps ?

### ISSUE THREAD

**Issue by trtin** [wix/react-native-ui-lib#1618]
I am facing this issue when trying to pass a callback function to KeyboardAccessoryView using `kbInitialProps`. The prop will have null value while it works for numeric, string, bool...

Does anyone else face same issue? could you please share your experiences ?

Thanks in advance,

**Comment by hieuduy98** [comment]
Hi @trtin I have faced the same issue, how can you fix this?

**Comment by efstathiosntonas** [comment]
@trtin did you ever found out why we're not able to pass a function? No matter what I did i couldn't pass a function. Thanks

**Comment by efstathiosntonas** [comment]
It seems this is an iOS issue only, on Android the functions are being passed just fine.

**Comment by iamalperen** [comment]
So how can I pass a function?

**Comment by gaoxiaosong1113** [comment]
I also encountered the same problem

**Comment by GregNing** [comment]
same issue here...
