### ISSUE TITLE
FeatureHighlight throws error on android when not passing testId as parameter.

### ISSUE THREAD

**Issue by MuhammedKpln** [wix/react-native-ui-lib#1665]
### Describe the bug
FeatureHighlight throws error on android when not passing testId as parameter on the component that you want it to be highlighted. You can see error details in #1487.

### To Reproduce

1. Create a view that you want to highlight
2. Add view to targets array via ref.
3. Try to render it via feature highlight
4. You will see that it will throw an error

### Expected behavior

It should render even tho you not passing testId parameter to it.

### Code snippet

```<View ref={r => addTarget(r, 0)} style={{ opacity: 1 }} testID={'HighlightView'}>```

### Device (please complete the following information)
- Device: Android Simulator
 - OS: Android 11 / Android 10

**Comment by KushaanKapoor** [comment]
Having the same issue on iOS and android... any fix?

**Comment by Inbal-Tish** [comment]
@MuhammedKpln Hi. I can't reproduce the issue. Can you please write more about your environment and add the snippet where you're using the FeatureHighlight component?

**Comment by ivopr** [comment]
Hey, was facing the same thing here and can confirm that passing a `testID` made things work. The component rendered properly the first highlighted spot I wanted, but then, I clicked `Got It` and instead of showing me the next highlight it closed. Sometimes I got this error `animated node with tag 200 does not exists`. Again, providing the `testID` to the element to be highlighted made everything work.

**Comment by Inbal-Tish** [comment]
@ivopr Thank for the comment, but I still missing more info. Also, If you have another issue with the `confirmButtonProps.onPress` please open a different issue.

**Comment by MuhammedKpln** [comment]
> @MuhammedKpln Hi. I can't reproduce the issue. Can you please write more about your environment and add the snippet where you're using the FeatureHighlight component?

Hi @Inbal-Tish! Sorry for late answer..  

Here is the [custom hook](https://www.toptal.com/developers/hastebin/kukitihoba.typescript)
and here is the [usage](https://www.toptal.com/developers/hastebin/asalakimuf.js) in a component.

**Comment by vendramini** [comment]
Same issue here. It only works if I add testID on targets.

```typescript
<FeatureHighlight
  visible={true}
  title={'Testing title'}
  message={'Testing message'}
  getTarget={() => refTest.current}
/>
```
```<View ref={refTest} testID={'refTest'}>```

```
"expo": "~51.0.37",
"react-native-ui-lib": "^7.33.0",
"react-native": "0.74.5",
```
