### ISSUE TITLE
FeatureHighlight prompts to install react native picker

### ISSUE THREAD

**Issue by MuhammedKpln** [wix/react-native-ui-lib#1666]
### Describe the bug
Featurehighlight prompts to install react native picker module, which is not required. It does not break the application however it throws error.

### To Reproduce
1. Install react-native-ui-lib
2. Import feature highlight with react-native-ui-lib/featurehighlight
3. Configure featurehighligh as usual
4. and it will throw error.

### Expected behavior
It should not throw error as it is not required  react native picker.

### Screenshots
![Screenshot 2021-11-15 at 21 14 14](https://user-images.githubusercontent.com/17166855/141848060-69b07801-b201-480b-9c63-d53c094c5788.png)

**Comment by CyxouD** [comment]
Same here. I don't understand why it is needed

**Comment by MuhammedKpln** [comment]
> Same here. I don't understand why it is needed. @MuhammedKpln did you fix it somehow? I've checked the latest library version (6.9.0) but the issue still exists

Nah i still have same issue..

**Comment by CyxouD** [comment]
@MuhammedKpln could you reopen the issue, so I don't need to create another one?
