### ISSUE TITLE
how to use custom fonts with this library?

### ISSUE THREAD

**Issue by Yasir5247** [wix/react-native-ui-lib#1672]
```
Typography.loadTypographies({
    hotlable: { fontSize: 12 },
    lightHeading: { fontSize: 16 },
    boldHeading: { fontSize: 16, fontWeight: '600' },
    errorMessage: { fontSize: 16, fontWeight: '600', color: Colors.red10 },
    light: { fontWeight: '400' },
    bold: { fontWeight: '600' },
    h1: { fontSize: 11, fontFamily: '**Aventra-Light**' },
    h2: { fontSize: 12, fontFamily: 'Aventra-Light' },
    h3: { fontSize: 14, fontFamily: 'Aventra-Light' },
    h4: { fontSize: 16, fontFamily: 'Aventra-Light' },
    h5: { fontSize: 20, fontFamily: 'Aventra-Light' },
  });

  Spacings.loadSpacings({
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 40,
  });
```
Im just thinking about how to use the custom font inside the component. in this case everywhere i apply h3 i will get that font. but i would like to know the best practice.

**Comment by razatta** [comment]
this is the practice that i am using as well! +1 if there is any other way

**Comment by ethanshar** [comment]
That is correct, one you load typographies/spacings (or anything else_ you can use them in two ways: 

The first is passing it to a style/stylehseet like this
```
<Text style={{...Typography.h1, marginRight: Spacings.xs}} > TEXT </Text>
```

The other way, in case you are using rnuilib components that support the relevant modifiers, you can do this
```
<Text h1 marginR-xs> TEXT </Text>
```

**Comment by Yasir5247** [comment]
I can see that i can control fontSize, fontWeight etc. for instance "text90", "text70" is for different sizes. also i can make it bold and large like this "text100BL". but where is the @font-face define. i assume this is the system default font. I would like to change it to a font family of my choice where i can control the weight, size like this. Is it possible? if so how?

```
return (
    <View marginB-10>
      <View>
        {!!heading && (
          <Text text90 grey40>
            {heading}
          </Text>
        )}
      </View>
      <View row>
        <View>
          <Text text70 black>
            {replaceIdNumber(idNumber)}
          </Text>
        </View>
      </View>
    </View>
  );
```
