### ISSUE TITLE
ColorPalette does not have it's own package

### ISSUE THREAD

**Issue by MuhammedKpln** [wix/react-native-ui-lib#1679]
While you can import color picker like this:
`import ColorPicker from 'react-native-ui-lib/colorPicker`

you can not import ColorPalette on this way.

**Comment by ethanshar** [comment]
@Inbal-Tish 
I think we can fix it easily fix this by moving the ColorPalette component our of ColorPicker hierarchy 
The script that generates the packages go over each folder in the component directory, so this component is missed

**Comment by Inbal-Tish** [comment]
@ethanshar Sure. I'll move it to components directory

**Comment by Inbal-Tish** [comment]
Done. PR #1692
