### ISSUE TITLE
ActionSheet not scroll

### ISSUE THREAD

**Issue by thisroot** [wix/react-native-ui-lib#1691]
This issue does not fixed, i cant found it into releases.
After update to latest version, error still exist
- https://github.com/wix/react-native-ui-lib/issues/1505

**Comment by phuocantd** [comment]
I think using Dialog change for ActionSheet

**Comment by thisroot** [comment]
> I think using Dialog changes for ActionSheet

Dialog has other problem. If you use into Dialog component, FlatList, that need 2 touches for select item, when you open dialog first time

**Comment by ethanshar** [comment]
@thisroot 
Can you elaborate in the issue. 
If you can provide a code snippet and a video it will help a lot. 
Thanks
