### ISSUE TITLE
Change search placeholder + text color of Picker component

### ISSUE THREAD

**Issue by romanpozd-tg17** [wix/react-native-ui-lib#170]
Hey,
Can we change the placeholder and text color of Search component inside Picker?
Currently the default color is white on android devices.

Thanks

**Comment by Inbal-Tish** [comment]
@romanpozd-tg17 Hi. Please see our last update with the added 'searchStyle' and 'searchPlaceholder' props.

**Comment by romanpozd-tg17** [comment]
Great. thanks!
