### ISSUE TITLE
Picker iOS 15.1 not working properly

### ISSUE THREAD

**Issue by andrisole92** [wix/react-native-ui-lib#1710]
### Describe the bug
1. Header is overlapping with top notch
2. Can't hit cross/save button

### To Reproduce

Try running Expo app on iOS 15.1 with iPhone 11 pro Max. (basic Picker)

### Expected behavior

Picker header should not overlap top notch

### Code snippet

```
<ScrollView keyboardShouldPersistTaps='always'>
      <View margin-20>
        <Picker
          topBarProps={{ title: 'Languages' }}
          placeholder='Choose'
          value={formData.languages}
          showSearch
          onChange={(languages: string[]) =>
            setFormData((data: any) => ({ ...data, languages }))
          }
          mode={'MULTI'}
          selectionLimit={3}>
          {options.map((value) => (
            <Picker.Item key={value.label} value={value} />
          ))}
        </Picker>
      </View>
    </ScrollView>
```

### Device (please complete the following information)
iPhone 11 Pro Max iOS 15.01

**Comment by ethanshar** [comment]
Hi @andrisole92 
Can you share a screenshot of what you are getting..

**Comment by AM-colee** [comment]
You get something like below:
<img width="399" alt="Screenshot 2022-01-21 at 12 09 51" src="https://user-images.githubusercontent.com/64313596/150524918-a8b2df59-b477-452a-9310-321e24590559.png">

Seems like the modal that is created is not created inside a safe view and none of the passed parameters seem to make it to that modal. There is a "pickerModalProps" however I am unsure what the structure of this is and so cannot easily work this out, perhaps an example of this structure is required however it would only provide a "hackaround" fix.

Reviewing the modal in question:
https://github.com/wix/react-native-ui-lib/blob/251b7194eebedb7cad3bb5d1ddbe76440676b5ff/src/components/picker/PickerModal.js#L96

It seems that the modal has no way of handling notches in screens etc. Is it worth surrounding this modal in a safeview? Or creating custom logic that reimplements a safeview if you want to avoid a dependency. This feature seems basically unusable on any modern ios device without a safeview.
