### ISSUE TITLE
Getting a warning when using Picker: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?

### ISSUE THREAD

**Issue by helpse** [wix/react-native-ui-lib#1714]
### Describe the bug
I'm getting a warning when using Picker: 

`ERROR  Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?`

### To Reproduce
1. Use Picker and Picker.Item from the lib

### Expected behavior
No warnings

### Code snippet
```
<Picker
    label="Type"
    floatingPlaceholder
    enableModalBlur={false}
    topBarProps={{title: 'Type'}}
>
    {equipmentTypesFiltered.map(type => (
        <Picker.Item
            key={type.id}
            label={type.name}
            value={type.name}
        />
    ))}
</Picker>
```

### Device (please complete the following information)
 - Device: Android Simulator
 - OS: Android

### Additional context
Using the following package versions:
```
    "react-native": "0.64.3"
    "react-native-ui-lib": "^6.5.3"
```

**Comment by ethanshar** [comment]
@lidord-wix 
Seem like people are getting from other sources. 
Im starting to believe it's a general issue with our forwardRef HOC and probably many components trigger this error

**Comment by BadtzMaru** [comment]
TextFiled also has this problem @ethanshar

**Comment by b1ngx** [comment]
the same problem

**Comment by nmka55** [comment]
Same problem with Incubator.TextField. Is there any fix for now?

**Comment by kavitha57** [comment]
same issue in WheelPickerDialog

**Comment by yinshurman** [comment]
same issue after upgrade from 6.0.0 to 6.7.1

**Comment by igoramidzic** [comment]
Same issue in Dialog

**Comment by ethanshar** [comment]
As far as I know this issue is already resolved.
