### ISSUE TITLE
Toast still in use?

### ISSUE THREAD

**Issue by idmick** [wix/react-native-ui-lib#1720]
I'm looking to create a toast notification in our app. In de docs, I only see the dialog. But when I dig in the code I see there is also a Toast component, which I can't find back in the documentation. 
So my question is, is the Toast component deprecated, and should I use the dialog or can I still use the toast notification? If so can someone point me to the documentation of the toast component?

**Comment by ethanshar** [comment]
Hi @idmick 
We're working on a new and better implementation of a Toast component.
It will be available soon!

**Comment by YaoHuiJi** [comment]
> 

hi @ethanshar,  what about KeyboardAccessoryView?  I can't find it in the documentation too, is it safe to use it in production?

**Comment by ilkerceng** [comment]
@ethanshar I just created it today with Dialog. Really excited to see it. Thanks

**Comment by ethanshar** [comment]
FYI, The new Toast component has been released and accessible  through the Incubator namespace. 
You can
```
import {Incubator} from 'react-native-ui-lib';

<Incubator.Toast ...>
```

**Comment by ethanshar** [comment]
> hi @ethanshar, what about KeyboardAccessoryView? I can't find it in the documentation too, is it safe to use it in production?

Yes, it should be safe and you are right, it's missing from the docs. We'll make sure to add all keyboard components to our docs
