### ISSUE TITLE
Setting default font family for Text, Buttons, etc is impossible

### ISSUE THREAD

**Issue by aprilmintacpineda** [wix/react-native-ui-lib#1725]
### Describe the bug

We can't set a default fontFamily using ThemeManager.

### Expected behavior

All Text/Button should use the specified `fontFamily` on the `ThemeManager`.

### Code snippet

```ts
import { purple, text } from 'colors';
import { ThemeManager } from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Button', {
  backgroundColor: purple,
  fontFamily: 'Roboto',
  fontWeight: '600',
  customTypography: true
});

ThemeManager.setComponentTheme('Text', {
  fontFamily: 'Roboto', // fontFamily doesn't work
  color: 'pink' // color works
});
```

this also doesn't work:

```ts
import { purple, text } from 'colors';
import { ThemeManager } from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Button', {
  backgroundColor: purple,
  fontFamily: 'Roboto',
  fontWeight: '600',
  customTypography: true
});

ThemeManager.setComponentTheme('Text', {
  style: {
    fontFamily: 'Roboto', // will not work
    color: 'pink' // will not work
  }
});
```

Using a callback function also doesn't resolve the problem.

### Screenshots

N/A

### Device (please complete the following information)

N/A

### Additional context

This has been a problem reported by other devs and is always being closed without being resolved, if this is something that the library does not want to do, **PUT THAT ON THE DOCS**.

**Comment by kieran-osgood** [comment]
Have you tried using setComponentForcedTheme? this is a snippet which we use:

```

ThemeManager.setComponentForcedTheme("Text", (props: TextProps, _context: any) => {
  return {
    style: compileTextStyle({ ...props, textStyle: props.style }),
  }
})
ThemeManager.setComponentForcedTheme("Button", (props: BaseProps, _context: any) => {
  return {
    labelStyle: compileTextStyle({
      ...props,
      textStyle: [{ fontWeight: "500" }, styles.buttonLabelDefaultStyle, props.labelStyle],
    }),
  }
})
```

**Comment by aprilmintacpineda** [comment]
> Have you tried using setComponentForcedTheme? this is a snippet which we use:
> 
> ```
> 
> ThemeManager.setComponentForcedTheme("Text", (props: TextProps, _context: any) => {
>   return {
>     style: compileTextStyle({ ...props, textStyle: props.style }),
>   }
> })
> ThemeManager.setComponentForcedTheme("Button", (props: BaseProps, _context: any) => {
>   return {
>     labelStyle: compileTextStyle({
>       ...props,
>       textStyle: [{ fontWeight: "500" }, styles.buttonLabelDefaultStyle, props.labelStyle],
>     }),
>   }
> })
> ```

@kieran-osgood I haven't tried that but I don't think that will solve the problem, what I want to achieve is that the Texts, Buttons, etc has a DEFAULT font configuration, but I should still be able to override this when I need to, i.e., different font family and font-weight on some places.

**Comment by kieran-osgood** [comment]
@aprilmintacpineda Okay sorry let me re-wind and explain this better.

The reason your example doesn't work is because you are trying to pass in fontFamily directly to the components, the setComponentTheme allows passing default props but the fontFamily isn't a valid prop, its a property in the style prop, if you wanted to set default fonts you would be doing like this:
```js
ThemeManager.setComponentTheme('Text', {
    style: {
      fontFamily: 'Roboto',
      color: 'pink' 
    } 
});
```
however when you use the Text component if you passed in a style prop, it would override that and doesnt merge them together.

The method I showed will allow merging, albeit you will be merging the styles yourself.
In my example if you notice I have a `combineTextStyle` function which flattens and combines the styles, it spreads the default styles and then spreads in the props.style (or whatever relevant style has the text stuff, things like buttons will use `labelStyle` etc).
I use this in an app currently and it does allow overriding (the function is literally just spreading, so if you spread an object with the fontFamily key on top of the default style it will allow overriding)

**Comment by aprilmintacpineda** [comment]
> @aprilmintacpineda Okay sorry let me re-wind and explain this better.
> 
> The reason your example doesn't work is because you are trying to pass in fontFamily directly to the components, the setComponentTheme allows passing default props but the fontFamily isn't a valid prop, its a property in the style prop, if you wanted to set default fonts you would be doing like this:
> ```js
> ThemeManager.setComponentTheme('Text', {
>     style: {
>       fontFamily: 'Roboto',
>       color: 'pink' 
>     } 
> });
> ```
> however when you use the Text component if you passed in a style prop, it would override that and doesnt merge them together.
> 
> The method I showed will allow merging, albeit you will be merging the styles yourself.
> In my example if you notice I have a `combineTextStyle` function which flattens and combines the styles, it spreads the default styles and then spreads in the props.style (or whatever relevant style has the text stuff, things like buttons will use `labelStyle` etc).
> I use this in an app currently and it does allow overriding (the function is literally just spreading, so if you spread an object with the fontFamily key on top of the default style it will allow overriding) 
> 

AHA, I see, I will try this out tomorrow, it's late night here, thanks for the help!

**Comment by aprilmintacpineda** [comment]
This worked really well for us:

```ts
import {
  ButtonProps,
  TextProps,
  ThemeManager
} from 'react-native-ui-lib';
import { purple, text } from 'colors';
import { Animated, StyleProp, TextStyle } from 'react-native';
import { combineStyles } from 'utils/styles';

// Note for setting theme https://github.com/wix/react-native-ui-lib/issues/1725

ThemeManager.setComponentForcedTheme(
  'Button',
  (props: ButtonProps): ButtonProps => {
    return {
      backgroundColor: props.link ? 'transparent' : purple,
      ...props,
      labelStyle: combineStyles<TextStyle>(
        {
          fontFamily: 'Roboto',
          fontWeight: '600',
          color: props.link ? '#000' : '#fff'
        },
        props.labelStyle
      )
    };
  }
);

ThemeManager.setComponentForcedTheme('Text', (props: TextProps) => {
  return {
    color: text,
    ...props,
    style: combineStyles<
      StyleProp<TextStyle | Animated.AnimatedProps<TextStyle>>
    >({ fontFamily: 'Roboto' }, props.style)
  };
});
```

**combineStyles**:

```ts
import { StyleProp } from 'react-native';

export function combineStyles<T>(...styles: Array<StyleProp<T>>) {
  let combinedStyles: Array<StyleProp<T>> = [];

  styles.forEach(style => {
    if (style) combinedStyles = combinedStyles.concat(style);
  });

  return combinedStyles;
}
```

**Comment by built-by-as** [comment]
This doesn't work for me, used the exact snippet posted by @aprilmintacpineda and my text style doesn't change. If I set `fontFamily` directly using a style on the Text component, it works.

**Comment by kieran-osgood** [comment]
> This doesn't work for me, used the exact snippet posted by @aprilmintacpineda and my text style doesn't change. If I set `fontFamily` directly using a style on the Text component, it works.

It'd be best to share a complete snippet example, maybe on stack ovrflow (feel free to send it to me) as this issue is likely wanting closing, of how you've merged the styles because this method has worked for multiple users so it's probably a misconfiguration issue?

**Comment by built-by-as** [comment]
@kieran-osgood it started working for me randomly, not sure what was wrong before. thanks

**Comment by aprilmintacpineda** [comment]
Changes in the theme don't get reflected on HMR, you'll have to hard refresh the app via the metro bundler or dev menu.
