### ISSUE TITLE
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by yang1140511782** [wix/react-native-ui-lib#1738]

**Comment by ethanshar** [comment]
Did you follow Reanimated setup guide? 
Specifically this line 
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#babel-plugin

**Comment by huyhomie66** [comment]
that cant fixed

**Comment by Bruce-zxy** [comment]
#1221 Look at this one.
