### ISSUE TITLE
Carousel TabController doesn't work properly on swiping

### ISSUE THREAD

**Issue by sgtpsibin** [wix/react-native-ui-lib#1743]
### Describe the bug
I copied  this [TabControllerScreen demo](https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/TabControllerScreen/index.tsx) to my local. 
I found that the TabController.PageCarousel doesn't work properly on swiping.
This is fine if i click to change TabPage.

Video to reproduce:
https://streamable.com/fvb8oh

### Package.json
` "dependencies": {
    "@apollo/client": "^3.5.6",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/datetimepicker": "^5.1.0",
    "@react-native-community/netinfo": "^4.7.0",
    "@react-native-picker/picker": "^2.2.1",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@types/lodash": "^4.14.178",
    "@types/react-native-vector-icons": "^6.4.10",
    "appcenter": "4.3.0",
    "appcenter-analytics": "4.3.0",
    "appcenter-crashes": "4.3.0",
    "graphql": "^16.2.0",
    "lodash": "^4.17.21",
    "query-string": "^7.0.1",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-appstate-hook": "^1.0.6",
    "react-native-code-push": "^7.0.4",
    "react-native-encrypted-storage": "^4.0.2",
    "react-native-gesture-handler": "1.10.3",
    "react-native-inappbrowser-reborn": "^3.6.3",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-native-ui-lib": "^6.6.2",
    "react-native-vector-icons": "^7.1.0",
    "react-query": "^3.34.6"
  }`

**Comment by sgtpsibin** [comment]
downgraded to `5.0.0` and work properly.

**Comment by ethanshar** [comment]
It should also work in latest version, I wouldn't recommend going back to v5 
Our demo app's main screen is using TabController with PageCarouse and it's working properly.
