### ISSUE TITLE
For TabPage, also call renderLoading when the page is not being focused

### ISSUE THREAD

**Issue by SimonVuong** [wix/react-native-ui-lib#1745]
### Which component?
TabController.TabPage

### What is the new feature?
Currently TabPage only calls `renderLoading` when the component is `lazy`. However, it would be helpful to also call `renderLoading` when the TabPage is `!focused`. This is helpful because when a user swipes across UNLAZY tabs very quickly, there's a moment where nothing is rendered (and therefore a white screen is displayed) while `props.children` is being unfrozen.

### Code snippet
https://github.com/wix/react-native-ui-lib/blob/master/src/components/tabController/TabPage.tsx#L87

update this line to `{(!shouldLoad || !focused)&& renderLoading?.()}`

**Comment by ethanshar** [comment]
Hi @SimonVuong 
We recently reverted some of the code there. 
So at the moment this issue is not relevant. 
Closing it for now.
