### ISSUE TITLE
TabBar works incorrect after rotating screen

### ISSUE THREAD

**Issue by likeSo** [wix/react-native-ui-lib#1746]
### Describe the bug

TabPage position and tab bar item's position are wrong after rotating the screen

### To Reproduce

- A TabController
- Rotate screen
- Swipe between screens

### Expected behavior

The tab page and tab bar should work properly after screen rotating 

### Code snippet

Repro Snack: https://snack.expo.dev/@likeso/delicious-french-fries

### Screenshots

![image](https://user-images.githubusercontent.com/12247340/147723815-4564b97c-5a45-4a0a-84c8-ecd0130e0600.png)

### Device (please complete the following information)

Device: iPhone 13
OS: iOS 15

### Additional context

Anothers problem is that i cannot customize the spacing between tab bar items.
I am trying to customize the spacing between tab bar items using:`style: { paddingHorizontal: 8 },` in `TabControllerItemProps`
But i got this:
![image](https://user-images.githubusercontent.com/12247340/147724274-6f44ca63-0192-4d73-a001-4970c0a5afee.png)
Is this the correct way to customize the spacing?

**Comment by likeSo** [comment]
And now i am trying to get there by `indicatorInsets={Spacings.s10}`, look great:
![image](https://user-images.githubusercontent.com/12247340/148061254-d61e6644-b668-4d8c-a651-afec1ccc1ef5.png)
But when i try to swipe to a shorter tab: 
![image](https://user-images.githubusercontent.com/12247340/148061352-8f6d57a3-b864-40e3-9e9e-cc05c9b00a7e.png)
What the hell is that? Why can't we just set a fixed indicator width?

**Comment by likeSo** [comment]
Problem list:
- Customize indicator width: follow the tab bar item width. Or follow the label text width or just a fixed width;
- Wrong Tab Page and indicator position after screen rotating
- [Question]Customize tab bar item spacing?

**Comment by likeSo** [comment]
The problem still exists as I newly tested

**Comment by likeSo** [comment]
- Problem 1: Tab Bar indicator's position are wrong after the screen rotate.
- Problem 2: I can't control the indicator's width or padding something

**Comment by likeSo** [comment]
And... Seems like this component does not support React Native Web yet, the indicator does not appear on web

**Comment by M-i-k-e-l** [comment]
> indicatorInsets={Spacings.s10}

Will not work because the inset is from both sides and your total width is too small.

But more importantly:
> What the hell is that?

ok...
