### ISSUE TITLE
Picker - Allow disabling (Add a prop 'disable' ) 

### ISSUE THREAD

**Issue by netsmertia** [wix/react-native-ui-lib#1753]
### Which component?
Picker
### What is the new feature?
Add an option to disable the picker from opening picker list.
### Code snippet
```jsx
<Picker disabled={true} />
```
### Uses
Need to chain the picker for country > city > area and city and area should not be selected/opened before selecting country.

### Reference

#1370

**Comment by ncortesm** [comment]
There is a property to prevent editing, I hope it helps...

editable={false}

**Comment by netsmertia** [comment]
It will not work when `renderPicker` provided.

**Comment by ethanshar** [comment]
This issue is fixed.
