### ISSUE TITLE
maxHeight in textField causing crashes

### ISSUE THREAD

**Issue by dopplerDistortion** [wix/react-native-ui-lib#1754]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-ui-lib@5.30.0` for the project I'm working on.

maxHeight scaling base on platform was causing malfunction errors I had to change it like this.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-ui-lib/src/components/textField/index.js b/node_modules/react-native-ui-lib/src/components/textField/index.js
index 6622c92..c91acc9 100644
--- a/node_modules/react-native-ui-lib/src/components/textField/index.js
+++ b/node_modules/react-native-ui-lib/src/components/textField/index.js
@@ -602,7 +602,7 @@ export default class TextField extends BaseInput {
       // hideUnderline && this.styles.inputWithoutUnderline,
       {...typographyStyle},
       // Constants.isAndroid && {lineHeight},
-      expandable && {maxHeight: lineHeight * (Constants.isAndroid ? 3 : 3.3)},
+      expandable && {maxHeight: lineHeight},
       Constants.isRTL && {minHeight: lineHeight + 3},
       Constants.isIOS && shouldUseMultiline && {paddingTop: 0}, // fix for iOS topPadding in multiline TextInput
       {color: textColor},
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ethanshar** [comment]
Hi @dopplerDistortion 
Sorry for the late response. 

I suggest using our new TextField implementation, the new TextField is currently under the Incubator namespace and you can already use it. 

```
import {Incubator} from 'react-native-ui-lib';

<View>
  <Incubator.TextField placeholder={} value={}/>
</View>
```
