### ISSUE TITLE
Button label does not appear when using with low height

### ISSUE THREAD

**Issue by MuhammedKpln** [wix/react-native-ui-lib#1768]
- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

#### Expected behavior

To center label based on height/width of the button

#### Actual behavior

When giving height to button even after giving a font size, the label does not appear.

### Code snippet

```
      <Button
        outline
        label="Button"
        style={{ height: 30 }}
      />
```

### Screenshots/Video

<img width="87" alt="Screenshot 2022-01-09 at 17 09 16" src="https://user-images.githubusercontent.com/17166855/148690740-d5e4f239-4711-47ef-9f78-575c92a5f82e.png">

### Environment

- React Native: 0.66.4
- React Native UI Lib: 6.7.0

### Affected platforms

- [ ] Android
- [x ] iOS
- [ ] Web

**Comment by ethanshar** [comment]
Hi @MuhammedKpln 
Can you please try changing the text style (you can pass `labelStyle`) and set the `lineHeight` to undefined.

**Comment by MuhammedKpln** [comment]
Hello @ethanshar
The results are the same even after passing lineHeight.

**Comment by ethanshar** [comment]
Ok, I see what's the issue. 
The button comes with internal padding. When you set a custom height the content has no room because of the internal vertical padding. 
You can pass the `avoidInnerPadding` prop to remove the padding that comes with the component.

**Comment by MuhammedKpln** [comment]
> Ok, I see what's the issue. 
> 
> The button comes with internal padding. When you set a custom height the content has no room because of the internal vertical padding. 
> 
> You can pass the `avoidInnerPadding` prop to remove the padding that comes with the component. 

Oh! Thank you. But will this be neccesary for feature versions?

**Comment by ethanshar** [comment]
It's really up to you. 
We provide different sizes of buttons with all the UI styles that comes with it. 
If you want to strip these styles and have your own logic, go ahead 👍
