### ISSUE TITLE
Picker item not updating when aving translation/localization module

### ISSUE THREAD

**Issue by riamon-v** [wix/react-native-ui-lib#1796]
## Description

Hello,

I use in my app `expo-localization` and `i18n-js`packages to have multiple language supported.

It's working great when trying to change the language of my app for all my components, except for the `Picker.Item` not updating inside the `Picker` component

Any idea what can cause the Picker not to rerender ?

The data provided is actually changing like I expected to, but not visually in the picker

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

Code of my picker

``` jsx
<Picker
	title={`${props.label}Picker`}
	floatingPlaceholder
	// migrate={true}
	placeholder={props.placeholder}
	value={props.value}
	onChange={props.onValueChange}
	floatingPlaceholderStyle={{
		...Typography.normal,
		fontSize: ms(16, 0.3),
		color: Colors.placeholder,
		// marginLeft: Spacings.S - 3,
	}}
	style={[
		{
			...Typography.normal,
			color: Colors.text,
			top: props.label ? ms(-8, 0.3) : 0,
			paddingBottom: ms(15, 0.3),
			paddingTop: ms(5, 0.3),
			textAlign: props.label ? 'right' : 'left',
		},
		props.label && { width: '50%' },
	]}
	renderRightIcon={() => (
		<Feather
			name="chevron-down"
			color={Colors.placeholder}
			size={ms(28)}
			style={{ top: mvs(-6) }}
		/>
	)}
	hideUnderline
	useNativePicker={!props.search}
	showSearch={props.search}
        >
	{props.items.map((option) => (
		<Picker.Item
			key={option.key}
			value={option.value}
			label={option.label}
			inputLabel={option.inputLabel ?? undefined}
			disabled={false}
			labelStyle={{
				...Typography.title,
				color: Colors.primary,
			}}
			selectedIconColor={Colors.highlight}
		/>
	))}
</Picker>
```

```


```

### Screenshots/Video
![ezgif-5-10e75d2bc8](https://user-images.githubusercontent.com/19188004/150635451-747b4682-764a-45b2-af76-9ae27f63f118.gif)

### Environment

- React Native:
- React Native UI Lib:

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by ivopr** [comment]
You probably need to translate the `props.value`, or ensure that it has taken effect, in my app I had text sometimes not translating due to it being incapable of verifying the change in the selected language. If you used Ignite CLI to bootstrap your app, you can pass `{ locale: some-var-that-holds-the-selected-lang }` to the `translate` function, and it should work

**Comment by michaelahalim** [comment]
Are there any updates on this?

**Comment by michaelahalim** [comment]
I am experiencing sort of the same problem here. Might not be exactly the same but in my case, a workaround is to use getLabel on the picker component passing in a callback that returns the label of your selected item.

**Comment by riamon-v** [comment]
> selected item.

Awesome, can you share a small code example ?
