### ISSUE TITLE
TextInput onChange - height undefined

### ISSUE THREAD

**Issue by mitel** [wix/react-native-ui-lib#18]
- react-native-ui-lib 2.0.61
- expo 19.0.1 (RN 46)

Testing the TextInput on a Genymotion/Android, i hit a case where event.nativeEvent.contentSize returns undefined. I think it would be safer for onChange to test for contentSize before the assignment: 

```js
onChange(event) {
    if (Constants.isAndroid && event.nativeEvent && event.nativeEvent.contentSize) {
      const {height} = event.nativeEvent.contentSize;
      this.setState({height});
    }
    _.invoke(this.props, 'onChange', event);
  }
```

**Comment by ethanshar** [comment]
@mitel Can't disagree (: 
fixed!
