### ISSUE TITLE
TabBar requires react-native-linear-gradient

### ISSUE THREAD

**Issue by abn-volk** [wix/react-native-ui-lib#181]
Hello. I'm using this library with Expo and after upgrading to version 3.3.115, my app failed to compile with the following error:

`Unable to resolve "react-native-linear-gradient" from "node_modules/react-native-ui-lib/src/components/tabBar/index.js"`

As far as I can tell react-native-linear-gradient contains native code and requires ejecting, which I don't want. Furthermore, Expo already seems to contain the same `<LinearGradient>`. 

Is there a workaround for this situation? If not, could `react-native-linear-gradient` be made an optional dependency instead?

Thank you.

**Comment by ethanshar** [comment]
We still investigate this issue, for now we comment out the gradient behaviour on this component, please update to latest version
