### ISSUE TITLE
Carousel drag touch ?

### ISSUE THREAD

**Issue by ashinga48** [wix/react-native-ui-lib#186]
Can we have attribute 
`<Carousel 
     disableDrag={true} 
`

Going through I see, Scroll view has an option to disable touch via option scrollenabled.
https://facebook.github.io/react-native/docs/scrollview#scrollenabled

It would be helpful if the option is there..

**Comment by Inbal-Tish** [comment]
We're adding the ability to pass any ScrollView props to the carousel component (no overrides), so you can pass scrollEnabled={false} to disable the scroll.

**Comment by ashinga48** [comment]
Cool. Thanks @Inbal-Tish
