### ISSUE TITLE
Avatar children covered badge

### ISSUE THREAD

**Issue by xiweixiong** [wix/react-native-ui-lib#1877]
### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```


```

### Environment

- React Native:
- React Native UI Lib:

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by ethanshar** [comment]
Hi @xiweixiong 
Unfortunately the issue is not clear, please provide some code example and a screenshot
