### ISSUE TITLE
Tabcontroller does not re-render when passing custom background color via color scheme.

### ISSUE THREAD

**Issue by MuhammedKpln** [wix/react-native-ui-lib#1885]
## Description

Tabcontroller does not re-render when changing color scheme.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

#### Expected behavior

When passing custom background color via color scheme, changing color scheme with `Colors.setScheme` does not rerender Tabcontroller, which remains on older scheme 

#### Actual behavior

Tabcontroller does not re-render when changing color scheme.

### Code snippet

[Snippet](https://paste.laravel.io/6553bd11-3f07-437a-af5c-3ba333edf102)

### Screenshots/Video

https://user-images.githubusercontent.com/17166855/157345238-dd92eae4-e0f7-4ae7-883f-c95f4042f3df.mp4

### Environment

- React Native: 0.67.3
- React Native UI Lib: ^6.11.0

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by wuhao930406** [comment]
same bug
