### ISSUE TITLE
Preset Toast typescript

### ISSUE THREAD

**Issue by cyrilmarceau** [wix/react-native-ui-lib#1897]
Unable to assign type '"success" | 'failed' to type 'ToastPresets | undefined'

### Related to
- [ ] Typings

```
<Toast
        message={!isSuccess ? message : "Connexion réussie"}
        visible={isError || isSuccess ? true : false}
        position="top"
        swipeable={true}
        autoDismiss={5000}
        onDismiss={() => dispatch(clearState())}
        zIndex={2}
        preset={isSuccess ? "success" : "failure"}
        containerStyle={{ top: 0 }}
        centerMessage
/>

```

### Environment
- React Native: "0.64.3"
- React Native UI Lib: "^6.10.0"

### Affected platforms

- [ ] Android
- [ ] iOS

**Comment by lidord-wix** [comment]
@cyrilmarceau are you using the `Toast` from the `Incubator`, right? 
If so, please use the preset that way:
```
preset={isSuccess ? Incubator.ToastPresets.SUCCESS : Incubator.ToastPresets.FAILURE}
```

Please let me know if it works for you.

**Comment by cyrilmarceau** [comment]
Yes I use Toast from Incubator and it's working. Thanks
