### ISSUE TITLE
Button - cannot set icon fill color using iconStyle or iconProps

### ISSUE THREAD

**Issue by derscott** [wix/react-native-ui-lib#1952]
## Description

We want to render a `Button` component containing a SVG Icon. The icon is given by `iconSource` and I've tried to pass a `fill` or a `tintColor` for the icon using the `Button` prop `iconStyle` (I also tried `iconProps` later as it's used by the `Chip` component).

Every time I try to pass `fill` or `tintColor`, i get the following warning and the icon is not visible:
```
"function fill() {
  [native code]
}" is not a valid color or brush
```
This applies to colors given from theme like `Colors.primary` or hardcoded strings like `#FFFFFF` and it also doesn't matter if I pass it to `iconProps` or `iconStyle`, the result is always the same.

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
I've given a code snippet in the section below. Please try for yourself.

#### Expected behavior

I expect to see the Icon defined by `iconSource` and `iconStyle`.

#### Actual behavior

The icon is not displayed. There is space before the label, where the icon would actually be rendered. Also, I get the warning mentioned above.

### Code snippet

```
<Button
  backgroundColor={Colors.primary}
  iconSource={Assets.icons.search}
  // also occurrs when using iconProps instead of iconStyle
  iconStyle={{
    height: 24,
    // also occurrs when using tintColor instead of fill
    fill: '#FFFFFF',
    width: 24,
  }}
  label='I am a Button'
  labelStyle={{ color: Colors.white }}
  size={48}
/>
```

### Screenshots/Video
Not provided.

### Environment

- React Native: 0.67.4
- React Native UI Lib: 6.12.0

### Affected platforms

- [X] Android
- [X] iOS
- [ ] Web (don't know)

**Comment by mrdanielm** [comment]
I'm also getting the same, is this by design?

**Comment by mrdanielm** [comment]
For anyone else that stumbles on this in future, managed to work around it with the below: 

```
import { Camera } from "lucide-react-native";

<Button label="Hello World" iconSource={(iconStyle) => <Camera color={Colors.white} />}/>
```
