### ISSUE TITLE
set default font family

### ISSUE THREAD

**Issue by sakin** [wix/react-native-ui-lib#198]
Is it possible to set a default font family for typography, so when you just use `<Text>` or `<Button>` without other props your font family will pass through?

**Comment by Inbal-Tish** [comment]
Typography class holds text presets that are optimized for their font family. I suggest that if you want to have a default font family in your components, use the loadTypographies method to set you own typographies and pass it to some base component that extends our component.

**Comment by ethanshar** [comment]
it's possible to create theme using the `ThemeManager`
so for example if you would like to set the global default typography for text you can do the following: 
```
import {ThemeManager} from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Text', {
    text50: true,
//  customTypography: true, // if you loaded a custom typography
    dark30: true, // you can also apply a default color and basically any other default prop the Text supports 
});
```

**Comment by AlphaJuliettOmega** [comment]
@ethanshar but the snippet you provided to change the 'Typography' does not seem to change the 'Font Family'

**Comment by aprilmintacpineda** [comment]
I'm trying to do this:

```
import { purple, text } from 'colors';
import { ThemeManager } from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Button', {
  backgroundColor: purple,
  fontFamily: 'Roboto',
  fontWeight: '600'
});

ThemeManager.setComponentTheme('Text', {
  fontFamily: 'Roboto',
  color: text
});
```

But the font `fontFamily` does not work.
