### ISSUE TITLE
Unable to `yarn add` on Windows?

### ISSUE THREAD

**Issue by GollyJer** [wix/react-native-ui-lib#201]
I'm getting the following when executing `yarn add react-native-ui-lib` on Windows 10.

> [4/4] Building fresh packages...
> [1/3] ⠄ native-base
> [2/3] ⠄ @expo/traveling-fastlane-linux
> Exit code: 1
> Command: ln -sf lib/{ios,android} .
> Arguments:
> Directory: C:\dev\AwesomeLabs\burgertime\node_modules\react-native-interactable
> Output:
> 'ln' is not recognized as an internal or external command,

I haven't run into this with other packages but it does seem to be a Windows issue.  My partner installed your package on macOS without any errors.

Thanks for any help! 🙌
Jeremy

**Comment by mnlbox** [comment]
@GollyJer maybe related: #223

**Comment by Inbal-Tish** [comment]
@GollyJer 'react-native-interactable' was removed from the library. Can you check if that resolved your issue?
