### ISSUE TITLE
DateTimePicker dosen't work

### ISSUE THREAD

**Issue by yinshurman** [wix/react-native-ui-lib#2023]
## 
DateTimePicker simply not work both in your RNUIlib_snack demo and simple code like this 
```
<DateTimePicker title={'Select time'} placeholder={'Placeholder'} mode={'time'}/>
```
the Warning information is :
```
Possible Unhandled Promise  Rejection(id:7):
TypeError:Can't read property 'dismiss' of null
TypeError:Can't read property 'dismiss' of null
```

### Related to

- [x] Components
- [x] Demo
- [ ] Docs
- [ ] Typings

### step to reproduce 
1. simply check your rnuilib_snack 
2. or just this simple code:
```

import {DateTimePicker} from 'react-native-ui-lib';
export default function ScreenC({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <DateTimePicker title={'Select time'} placeholder={'Placeholder'} mode={'time'}/>
    </View>
  );
}

```

#### Expected behavior

hope it can work normally !

#### Actual behavior

can't select date and throw a warning i mentioned before .

### Code snippet

```
import {DateTimePicker} from 'react-native-ui-lib';
export default function Screen() {
  return (
    <View style={{flex: 1}}>
      <DateTimePicker title={'Select time'} placeholder={'Placeholder'} mode={'time'}/>
    </View>
  );
}

```

### Environment

- React Native: 0.68.1
- React Native UI Lib: 6.14.1

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Inbal-Tish** [comment]
@yinshurman Hi. I can't reproduce. It is working for me on our demo app on both iOS and Android. Can you add more details regarding the bug, like what exactly "doesn't work" and maybe add a video?
