### ISSUE TITLE
KeyboardAccessoryView property addBottomView does nothing

### ISSUE THREAD

**Issue by EmilScherdin** [wix/react-native-ui-lib#2034]
## Description

Hello! 

I believe there's a bug where the KeyboardAccessoryView property addBottomView does nothing when added.

It seems like adding the property passes it to the KeyboardTrackingView as a prop [here](https://github.com/wix/react-native-ui-lib/blob/master/lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx#L196) via `...other`. It passes all properties that aren't defined and `useSafeArea` property is defined earlier to be used on the `CustomKeyboardView` component which means that it isn't passed into the `KeyboardTrackingView`.

From what I can test the `useSafeArea` needs to be passed as well to the `KeyboardTrackingView` to have it respect the `addBottomView` property and that's why it isn't working today.

Happy to get some eyes on this and understand if I'm on the right track, I've just moved to this UI package from the older KeyboardAccessoryView package.

### Related to

- [x] Components

### Steps to reproduce

1. Use KeyboardAccessoryView
2. Use addBottomView property
3. Test on iPhone X

#### Expected behavior

Bottom view is added

#### Actual behavior

The bottom view is not added.

### Code snippet

<img width="754" alt="Screenshot 2022-05-04 at 19 12 26" src="https://user-images.githubusercontent.com/6998447/166742326-8a41311c-dccd-4a4e-8c12-b874f082f159.png">

```
const keyboardAccessory = () => {
    return (
      <View style={[styles.wrapper, { backgroundColor: colors.white }]}>
        <TextInput
          ref={textInputRef}
          multiline
          onChangeText={setText}
          defaultValue={text}
          onBlur={onInputBlur}
          style={[styles.textInput, textStyles.default]}
          placeholder={`${Translator.singular('Type a message')}…`}
        />
          <Pressable
            style={({ pressed }) => [
              pressed && styles.onPressIn,
            ]}
            onPress={handleSendText}
            hitSlop={10}
            accessibilityTraits="button"
          >
            <IconSend fill={colors.team} />
          </Pressable>
      </View>
    );
  };

  return (
    <KeyboardAccessoryView
      renderContent={keyboardAccessory}
      kbInputRef={textInputRef}
      kbComponent={customKeyboard}
      addBottomView
      useSafeArea
      onKeyboardResigned={() => setCustomKeyboard(undefined)}
      revealKeyboardInteractive
      requiresSameParentToManageScrollView
    />
  );

```

### Environment

- React Native: 0.66.4
- React Native UI Lib: 6.14.1

### Affected platforms

- [x] iOS

**Comment by EmilScherdin** [comment]
Hey @Inbal-Tish @lidord-wix, not sure you're the right people to mention on this. But I'm happy to throw up a PR on this if I just can get some eyes confirming it looks correct and aligned with how to work on bugs! :)

**Comment by Inbal-Tish** [comment]
@EmilScherdin Hi. Thank you for reporting. Please follow PR #2045

**Comment by EmilScherdin** [comment]
@Inbal-Tish Thank you for the quick response. Will follow it! :)

**Comment by Inbal-Tish** [comment]
@EmilScherdin Pr was merged. I'm closing this issue. Thank you for reporting!

**Comment by EmilScherdin** [comment]
@Inbal-Tish Hi again, thanks for being so quick in addressing this issue.

However, I can't seem to get the updated code, maybe I'm missing something.. You changed a .tsx file but I can only see the .js file when looking in my node_modules folder, is there some preprocessing that happens during a release that creates the .js file that isn't committed to the repo? 🤔

**Comment by Inbal-Tish** [comment]
@EmilScherdin I'll bump the native lib version to reflact the fix. See PR #2065

**Comment by EmilScherdin** [comment]
@Inbal-Tish  Okay, perfect! I'll try that, thank you! :)
