### ISSUE TITLE
Error using 'WheelPickerDialog'

### ISSUE THREAD

**Issue by CreateByCool** [wix/react-native-ui-lib#204]
Invariant Violation: Native component for "WheelPicker" does not exist

This error is located at:
    in WheelPicker (at index.js:77)
    in WheelPicker (at index.js:49)
    in RCTView (at View.js:60)
    in View (at index.js:39)
    in View (at index.js:42)
    in IGNORE (at WheelPickerDialogScreen.js:35)
    in RCTView (at View.js:60)
    in View (at index.js:39)
    in View (at WheelPickerDialogScreen.js:34)
    in WheelPickerDialogScreen (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

**Comment by barbarossusuz** [comment]
Same here ios working fine but android is buggy. @CreateByCool did you fix it ?
When clicking picker this error shows up.
Platform: Android only 
"react-native-ui-lib": "^3.3.110",
"react-native": "^0.56.0",

**Comment by ibmsoft** [comment]
same error

**Comment by Inbal-Tish** [comment]
Hi. WheelPicker is a native component. Did you link our native library?

**Comment by celineotter** [comment]
I am having this issue too.

ran `react-native link` at the root of the project as I don't see manual link instructions in the project's read-me or documentation.

I do have the react-native-toast installed and linked separately so resolved all the duplicate entries e.g.  `MainApplication.java`

**Comment by celineotter** [comment]
<img width="273" alt="screen shot 2018-12-18 at 10 02 49 am" src="https://user-images.githubusercontent.com/6541550/50173385-216e0680-02ac-11e9-965a-1b741691d37d.png">

**Comment by Inbal-Tish** [comment]
Please make sure that the native library is linked properly in Android ('react-native link' usually is not enough and you must link it manually).

**Comment by Inbal-Tish** [comment]
We added an 'Install uilib Native Components' section to the wiki: https://github.com/wix/react-native-ui-lib/wiki/SETUP
Please take a look.

**Comment by stothet** [comment]
I get this error as well. Using RN 61, which supports auto-linking. Do I need to manually link?

**Comment by Macrow** [comment]
> I get this error as well. Using RN 61, which supports auto-linking. Do I need to manually link?

I hava the same problem with native picker in Android.

RN:61
react-native-ui-lib: 5.1.1

**Comment by ethanshar** [comment]
It appear that we do have an issue with the Android auto-link. 
For now I can suggest to manually link it till we solve the issue. 
please follow our internal files to see how it should be linked 
`MainApplication.java`
`android/settings.gradle`
`android/app/build.gradle`

**Comment by leoxiaoping** [comment]
same error

**Comment by fosteruk** [comment]
Running into the same problem here.

**Comment by ethanshar** [comment]
The recent version should fix auto-link issue on Android. 
What version of `react-native-ui-lib` do u have?

**Comment by ethanshar** [comment]
@leoxiaoping @fosteruk 
Is this issue still relevant? did you try installing latest version?

**Comment by girishjjain-rh** [comment]
Still getting the error on Android with latest version of library - `"react-native-ui-lib": "^5.8.0",` and react-native 0.61: `Invariant Violation: requireNativeComponent: "WheelPicker" was not found in the UIManager.`

I am using Expo, here's Expo CLI 3.20.9 environment info:
```
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

**Comment by ethanshar** [comment]
The Android WheelPicker is part of `react-native-ui-lib` native code 
In order to use you will to make sure the your link our library on Android
