### ISSUE TITLE
SegmentControl: Value is undefined, expecting a object

### ISSUE THREAD

**Issue by Ulset** [wix/react-native-ui-lib#2061]
## Description
When trying to use the `SegmentControl` i get the following error

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
Add `<SegmentedControl segments={[{label: '1st'}, {label: '2nd'}]}/>` to your code

### Code snippet

```TypeScript
const Picker = <T extends unknown>(props: PickerProps<T>) => {
  return <SegmentedControl segments={[{label: '1st'}, {label: '2nd'}]}/>
};

```

### Screenshots/Video
![image](https://user-images.githubusercontent.com/33099664/170046365-a8168d90-0c3f-4475-be44-fb32163025f2.png)

### Environment
- React Native: 0.63
- React Native UI Lib: 6.15.1

### Affected platforms
- [ ] Android
- [X] iOS
- [ ] Web

**Comment by M-i-k-e-l** [comment]
Hi @Ulset,

Did you follow the installation guide [here](https://wix.github.io/react-native-ui-lib/docs/getting-started/setup)? 
`SegmentControl` requires the `react-native-reanimated` and `react-native-gesture-handler` libs.

**Comment by M-i-k-e-l** [comment]
Hi,

Sorry for the delay.

I have a project with these:
```
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.67.3",
    "react-native-gesture-handler": "2.5.0",
    "react-native-reanimated": "2.8.0",
    "react-native-ui-lib": "^6.20.0"
  },
```

I get no errors when adding the following to my `App.js`:
```
<SegmentedControl segments={[{label: '1st'}, {label: '2nd'}]}/>
```
