### ISSUE TITLE
Inverted behavior for disablePresses prop on StackAggregator component

### ISSUE THREAD

**Issue by siyoola** [wix/react-native-ui-lib#2071]
## Description

Inverted behavior for disablePresses on StackAggregator component, the press works when disables presses is set to true

### Related to

- [*] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

#### Expected behavior

When disablePresses is set to true the press should not work

#### Actual behavior

When disablePresses is set to true the press does work

### Code snippet

Demo App

### Affected platforms

- [ *] Android
- [ *] iOS
- [ *] Web

**Comment by Inbal-Tish** [comment]
@siyoola Hi. The `disablePresses` prop disables the press on the items (cards), not on the component. It does not prevent the component from opening. Also, any touchable elements (like buttons) in the Card's content will remain pressable.
Are you looking for a way to disable the StackAggregator from opening?
