### ISSUE TITLE
Avatar badgePosition typescript error

### ISSUE THREAD

**Issue by kockok** [wix/react-native-ui-lib#2074]
## Description

Avatar badgePosition always raising error, albeit the output looks good.

### Related to

Components

### Steps to reproduce

`import { Avatar } from 'react-native-ui-lib';//eslint-disable-line`

#### Expected behavior

No errors

#### Actual behavior

<img width="731" alt="Screenshot 2022-06-03 at 6 35 34 PM" src="https://user-images.githubusercontent.com/232541/171839648-c22955fb-a8f6-40e3-a731-fda1eea671bc.png">

### Environment

- React Native: `17.0.2`
- React Native UI Lib: `"react-native-ui-lib": "^6.16.1",`

### Affected platforms

- [ x] Android
- [x ] iOS

**Comment by Effanuel** [comment]
This is fixed in the latest version `"react-native-ui-lib": "6.21.2"`
