### ISSUE TITLE
DateTimePicker bottom sheet is not opening completly

### ISSUE THREAD

**Issue by Dey-Sumit** [wix/react-native-ui-lib#2093]
## Description
If I click on the date-time picker, it does not open fully, I can only see the cancel and save button, and that's it. I have attached the screenshot related to this bug. 
Tried seeing the code snippets in the official doc, and copied and pasted the full DateTimePicker screen code, but the issue is not resolved. Even the same issue is happening in the expo-snack attached to the docs.

### Related to

- [x] Components
- [x] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

Important the component and pass the necessary props, that's it. 
```
 <DateTimePicker
          title="Select time"
          placeholder="Placeholder"
          mode="time"
        />
```

#### Expected behavior
<img width="275" alt="image" src="https://user-images.githubusercontent.com/46570780/174445448-00a9532a-bf52-4d1b-a6c8-525719c1851e.png">

#### Actual behavior

<img width="225" alt="image" src="https://user-images.githubusercontent.com/46570780/174445221-baca1a5f-9ea1-4503-a914-b520f268df1e.png">

## More Info
The code : 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/46570780/174445286-0346a9e4-5e23-4785-90ee-4f65cd8ecb01.png">

### Environment

- React Native: `"0.68.2"`
- React Native UI Lib: `"^6.17.1"`

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by BrawnyJavier** [comment]
Is this repo dead?

**Comment by sainipray** [comment]
> ## Description
> If I click on the date-time picker, it does not open fully, I can only see the cancel and save button, and that's it. I have attached the screenshot related to this bug. Tried seeing the code snippets in the official doc, and copied and pasted the full DateTimePicker screen code, but the issue is not resolved. Even the same issue is happening in the expo-snack attached to the docs.
> 
> ### Related to
> * [x]  Components
> * [x]  Demo
> * [ ]  Docs
> * [ ]  Typings
> 
> ### Steps to reproduce
> Important the component and pass the necessary props, that's it.
> 
> ```
>  <DateTimePicker
>           title="Select time"
>           placeholder="Placeholder"
>           mode="time"
>         />
> ```
> 
> #### Expected behavior
> <img alt="image" width="275" src="https://user-images.githubusercontent.com/46570780/174445448-00a9532a-bf52-4d1b-a6c8-525719c1851e.png">
> 
> #### Actual behavior
> <img alt="image" width="225" src="https://user-images.githubusercontent.com/46570780/174445221-baca1a5f-9ea1-4503-a914-b520f268df1e.png">
> 
> ## More Info
> The code : <img alt="image" width="371" src="https://user-images.githubusercontent.com/46570780/174445286-0346a9e4-5e23-4785-90ee-4f65cd8ecb01.png">
> 
> ### Screenshots/Video
> ### Environment
> * React Native: `"0.68.2"`
> * React Native UI Lib: `"^6.17.1"`
> 
> ### Affected platforms
> * [ ]  Android
> * [x]  iOS
> * [ ]  Web

Same issue facing

**Comment by Jempan** [comment]
Same here :(
