### ISSUE TITLE
Not able to use (not able to close custom modal) renderCustomModal in Picker

### ISSUE THREAD

**Issue by saravanakumargn** [wix/react-native-ui-lib#2113]
## Description
When I use `renderCustomModal` with Picker not able to close created modal. Always modal popup is visible.

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```


```

### Environment

- React Native:
- React Native UI Lib:

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by ethanshar** [comment]
You can pass `ref` to the Picker component and close it programmatically yourself using the `closeExpandable` method
