### ISSUE TITLE
Can't get it working on RN v0.56

### ISSUE THREAD

**Issue by ziyafenn** [wix/react-native-ui-lib#212]
Hi there. I clean installed react-native v0.56 and react-native-ui-lib.

First thing to notice, i get npm warn:
`react-native-ui-lib@3.3.205 requires a peer of react-native@^0.51.0 but none is installed.`

Second, i tried to import `<View>` and `<Text>` from *the react-native-ui-lib* and this is the error i'm getting
![simulator screen shot - iphone 6 - 2018-08-15 at 10 06 01](https://user-images.githubusercontent.com/314302/44138020-d1e45574-a072-11e8-86ce-4373e88b02dc.png)

i've installed the package, run _npm install_ and even _react-native link_ (which i suppose i don't need to do as it's not in the install description)

I've tested also with and without `react-native-animatable`, same thing.

Any ideas?

Thanks.

**Comment by Inbal-Tish** [comment]
We'll be working soon to update the library to support RN 56, as of now it is supporting RN 51. We'll update soon.

**Comment by bhanuc** [comment]
The login example given in readme works for me on RN 56, I am thinking to pick up this library for a new project, are there specific components that I should avoid in the meantime?

**Comment by Inbal-Tish** [comment]
We now support RN 57 as well. Please see if your issue is resolved.
