### ISSUE TITLE
Incubator TextField - No line and cannot disable autoCapitalize

### ISSUE THREAD

**Issue by dlogvin** [wix/react-native-ui-lib#2120]
## Description

The component does not render the line under the text, and I cannot disable autoCapitalize.

### Related to

- [x] Components

### Steps to reproduce

```
<TextField
    autoCapitalize='none'
    placeholder='e-mail'
    floatingPlaceholder
    onChangeText={() => console.log('changed')}
    enableErrors
    validate={['required', 'email', (value) => value.length > 6]}
    validationMessage={['Field is required', 'Email is invalid', 'Password is too short']}
    maxLength={30}
    style={{ fontFamily: 'Manrope-SemiBold' }}
/>
```
Screenshot:
<img width="348" alt="Screenshot 2022-07-12 at 01 41 40" src="https://user-images.githubusercontent.com/62754263/178363509-e18a2a25-d728-415b-b897-daf22beb5ccf.png">

**Comment by ethanshar** [comment]
Try passing the `preset` prop with `default` value
