### ISSUE TITLE
ViewPropTypes has been removed from React Native.

### ISSUE THREAD

**Issue by abhishek-malaviya** [wix/react-native-ui-lib#2126]
## Description
ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
Try to use it Picker component with Picker.Item from the demo provided here: https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/PickerScreen.tsx

#### Expected behavior
Picker should work as shown in the documentation.

#### Actual behavior
Fails to compile the application with the error message "ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'."

## More Info
I have looked into the source code and it boils down to the BaseInput component. In the BaseInput, it uses the ViewPropTypes.

### Code snippet

```
<Picker
        placeholder="Favorite Languages (up to 3)"
        value={value}
        onChange={(item: any) => setValue(item)}
        migrateTextField>
        {_.map(
          [
            { label: 'JavaScript', value: 'js' },
            { label: 'Java', value: 'java' },
            { label: 'Python', value: 'python' },
            { label: 'C++', value: 'c++', disabled: true },
            { label: 'Perl', value: 'perl' },
          ],
          (option) => (
            <Picker.Item
              key={option.value}
              value={option}
              label={option.label}
              disabled={option.disabled}
            />
          ),
        )}
</Picker>

```

### Screenshots/Video
![picker-viewPropTypes](https://user-images.githubusercontent.com/106510933/179472071-92df6df3-3970-4470-bd3e-6493cc122a8a.png)

![picker,item error](https://user-images.githubusercontent.com/106510933/179472132-c08a9a68-ee66-489e-863c-77c1d3664b90.png)

### Environment

- React Native: 0.69.1
- React Native UI Lib: 6.18.0
- @react-native-picker/picker : 2.4.2
-  react-native-gesture-handler: 2.5.0
-  react-native-reanimated: 2.9.1

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by gran33** [comment]
That's unrelated to this lib, it's a general RN issue.

https://github.com/facebook/react-native/issues/33734
https://github.com/facebook/react-native/issues/33557
