### ISSUE TITLE
Can't declare color on android

### ISSUE THREAD

**Issue by trung2nghin** [wix/react-native-ui-lib#2128]
## Description

Can't declare color on android

### Steps to reproduce

1. Create a new application using React Native 0.69.1;
2. Install RNUILib;
3. Then create a file according to the following instructions: https://wix.github.io/react-native-ui-lib/docs/foundation/style
4. Import the color in any file and use it, but can't see that color (when declaring and using in the same file or use library default color it still works)

#### Expected behavior

Can display the declared color on android

#### Actual behavior

The app does not show error messages

### Screenshots/Video
![292426748_566488844952622_7670818282515631778_n](https://user-images.githubusercontent.com/68383200/179703839-e70029c7-7f4e-4ada-99d1-eac5053d2269.png)

### Environment

- React Native: 0.69.1
- React Native UI Lib: 6.18.1
- @react-native-community/blur: 3.6.0,
- @react-native-community/datetimepicker: 3.5.2,
- @react-native-community/netinfo": 6.0.2,
- @react-native-picker/picker: 2.1.0,

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by TranTrungDung** [comment]
I have an issue too  !!!! Someone help !!!!!!

**Comment by lidord-wix** [comment]
@trung2nghin 
You have to load the colors before you use them.
Are you loading the colors on `Colors.js`? if so, try to require this file at the top of your `App.js` file
BTW, does it work on iOS?

**Comment by trung2nghin** [comment]
@lidord-wix  
I did the same as this link https://wix.github.io/react-native-ui-lib/docs/foundation/style and then I required this file at the top of app.js file. It doesn't work on android but works properly on IOS.

**Comment by lidord-wix** [comment]
@trung2nghin 
Can you please share a project where you have this bug on?
I can't see it on our demo app (it works for me on iOS and on Android)

**Comment by trung2nghin** [comment]
@lidord-wix 
I have an example here: https://github.com/trung2nghin/RNUITest/tree/master, can you help me, thanks

**Comment by lidord-wix** [comment]
@trung2nghin 
That's because you load the colors after you use them.. 
try to use it that way in your App.js:
```
import React from 'react';
import {Text, View } from 'react-native-ui-lib';
require('./Color');

const App = () => {
  return (
    <View flex center bg-gold>
      <Text pink>Hello World</Text>
    </View>
  );
};

export default App;
```

And the same as you did in Color.js: 
```
import { Colors } from 'react-native-ui-lib';

Colors.loadColors({
  pink: '#FF69B4',
  gold: '#FFD700',
});
```

For me it works on your project, both on iOS and Android
![Screen Shot 2022-09-11 at 18 26 11](https://user-images.githubusercontent.com/66782556/189535734-9a4b58ba-0320-48b4-8f52-63705f5570f5.png)

**Comment by trung2nghin** [comment]
Thanks, I did the same as you and it worked
