### ISSUE TITLE
ActionSheet does not pass overlayBackgroundColor

### ISSUE THREAD

**Issue by aphillipo** [wix/react-native-ui-lib#2175]
## Description

```jsx
      <ActionSheet
        overlayBackgroundColor="rgba(0,0,0,0.3)"
        visible={isCreateMenuOpen}
        options={...}
      />
```

I would like be able to set the `overlayBackgroundColor` of the Dialog that Action Sheet extends. Is there a way to do this differently in the mean time?

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

See above.

#### Expected behavior

The background colour of the overlay action sheet uses should be inline with the passed overlayBackgroundColor prop.

#### Actual behavior

There is no overlayBackgroundColor prop and it's not passed to the underlying component.

**Comment by M-i-k-e-l** [comment]
Hi @aphillipo,
Once released you'll be able to send `overlayBackgroundColor` via the new `dialogProps`.
