### ISSUE TITLE
Invalid props.style key `ULIGHT` when using text10 prop

### ISSUE THREAD

**Issue by manattersa** [wix/react-native-ui-lib#218]
If i want to display a Text with text10 prop, a warning with the message "Warning: Failed prop type: Invalid props.style key `ULIGHT` supplied to `ForwardRef`" shows up.

In class Typography, the text10 property has a ULIGHT key with value of '100'. 

The fix i'm using to avoid this issue is in my index.js file:
import _ from 'lodash';
...
_.unset(Typography.text10, 'ULIGHT');

**Comment by ethanshar** [comment]
this was already resolved, please update your node_modules
