### ISSUE TITLE
Expo.io demo

### ISSUE THREAD

**Issue by veedeo** [wix/react-native-ui-lib#219]
I was searching for UI library for my side project and really liked what you did. Unfortunately I wasn't able to run the demo easily so I decided to port it to Expo so anyone can play with it directly on Exponent app.

[Expo demo](https://expo.io/@veedeo/react-native-ui-lib-expo)
[Git repo](https://github.com/veedeo/react-native-ui-lib-expo)

Limitations:
1. Since it should run in Expo all native controls aren't working.
2. I disabled Card Blur since it uses native library (It should support injecting BlurView in order to work with exponent)

Hope it helps

**Comment by Inbal-Tish** [comment]
Thanks! We didn't add any support for Expo, but I hope your comments will assist others.

**Comment by JOEAV** [comment]
@Inbal-Tish  hey :) does it means that I shouldn't add it to an expo project , or you just don't support expo issues ?

**Comment by Inbal-Tish** [comment]
You can add uilib to your project but uilib has some native dependencies, and expo doesn’t allow custom native code, only what’s inside expo sdk. At this moment we don't have a capacity to support expo-only issues
