### ISSUE TITLE
Is TabBar working?

### ISSUE THREAD

**Issue by mblodorn** [wix/react-native-ui-lib#22]
I'm trying to use TabBar in a side-project, but the text won't render. Not sure if I am doing something wrong (I already checked the component file) or if there is a problem with TabBar. Let me know if you need more info.

```

import React, { Component } from 'react';
import { TabBar, Text } from 'react-native-ui-lib';

export default class App extends Component {

  render() {
    return (
      <TabBar>
        <TabBar.Item label='Test'>
          <Text text30>HI</Text>
        </TabBar.Item>
        <TabBar.Item label='Test2'>
          <Text text30>HI</Text>
        </TabBar.Item>
      </TabBar>
    )
  }
}
```

This project was built with create-react-native-app.

**Comment by ethanshar** [comment]
The TabBar.Item doesn't render children, but the label prop provided. 
In your code it renders the labels: "Test", "Test2"

**Comment by mblodorn** [comment]
That would be great @ethanshar! Let me know how can I help you. :)

**Comment by ethanshar** [comment]
Hey @mblodorn, I added the feature. 
TabBar.Item will now render inner children. 
please see an example here:
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/TabBarScreen.js#L37

**Comment by mblodorn** [comment]
Thank you! I'll give it a try. :)
