### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by vucuongkg** [wix/react-native-ui-lib#2205]
snack.expo.dev is not working, please check it.

**Comment by salao-na-mao** [comment]
Same for me!

**Comment by alexthewilde** [comment]
This might be caused by your Expo SDK version.
@vucuongkg Try uninstalling Expo Go from your device and then running `expo start` again from within `/expoDemo`. This worked for me.

**Comment by murbanowicz** [comment]
Would be great if demo app / snack got updated to latest SDK

**Comment by ayuan-gy** [comment]
Have you solved this problem?
