### ISSUE TITLE
Card.Image syntax error

### ISSUE THREAD

**Issue by biapar** [wix/react-native-ui-lib#2219]
I try your library with RN.
I wish to try the card component with an image but the compiler give this error:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/661517/186614988-4a643a99-b86b-4887-acd2-611514e12e24.png">

Why? I follow your docs.

-----

    "@react-native-community/blur": "^4.2.0",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "galio-framework": "^0.8.0",
    "react": "18.0.0",
    "react-native": "0.69.4",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-reanimated": "^2.10.0",
    "react-native-safe-area-context": "^4.3.3",
    "react-native-screens": "^3.16.0",
    "react-native-svg": "^13.0.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-ui-lib": "^6.20.1"

**Comment by XHMM** [comment]
This is just a syntax error,  you need wrap your uri with quotes:

```
source={{uri: "https://xxx"}}
```

**Comment by biapar** [comment]
There is an error into the docs

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/661517/186897820-26f942bb-10dd-45ce-bb45-3ffc75e804a0.png">

I tried again but the image don't appear.
` <Card.Image source={{ uri: "https://github.com/wix/react-native-ui-lib/blob/master/demo/src/assets/images/card-example.jpg"}}/>`

<img width="391" alt="image" src="https://user-images.githubusercontent.com/661517/186898142-50fe3ece-fc88-4005-bcee-a482a460f437.png">

**Comment by XHMM** [comment]
you need to set `height` to `Card.Image`, try `height="100%"` or a fixed value such as `200`

**Comment by biapar** [comment]
I tried. Don't work.

**Comment by XHMM** [comment]
I tried you code and the image not showed as you said.

After searching source code ,I find `width` and `height` to `Card.Image` were used to set container size, not image actually,  you can try this code:
```jsx
<Card
  height={200}
  style={{backgroundColor: 'blue'}}
  center
  marginT-5
  onPress={() => console.log('pressed 1')}>
  <Card.Image
    source={{
      uri: 'https://images.unsplash.com/photo-1461988320302-91bde64fc8e4?ixid=2yJhcHBfaWQiOjEyMDd9&fm=jpg&q=80',
    }}
    style={{
      // add this, and remove width/height of Card.Image, set them on Card
      width: '100%',
      height: '100%',
    }}
  />
</Card>
```

By the end, the official doc really  has many issues, it's not ready to use I think.

**Comment by biapar** [comment]
You are right. The docs seems in alpha  version and then I think that this UI is not ready to use on mass.

**Comment by biapar** [comment]
It works.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/661517/187082509-23e24e67-8f60-431b-bebb-f4a370cbe7c1.png">
