### ISSUE TITLE
Can't build because of asset

### ISSUE THREAD

**Issue by mnlbox** [wix/react-native-ui-lib#224]
I try to compile release build with this package but it's return below error for me:
```
/home/myusername/myapp/android/app/build/intermediates/res/merged/release/drawable-xxhdpi/node_modules_reactnativeuilib_src_assets_icons_checksmall.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.
```

Can you guide me to fix this?

**Comment by mnlbox** [comment]
I add `android.enableAapt2=false` to my `gradle.propertise` and it's fix now. I think we need some fix for it for working with newer gradle version.

**Comment by Inbal-Tish** [comment]
We upgrade to RN 57 with the recommended gradle setting. Please check if it resolves your issue.
