### ISSUE TITLE
Picker missing props

### ISSUE THREAD

**Issue by LazyAfternoons** [wix/react-native-ui-lib#2250]
## Description
Since the last version, TypeScript shows an error regarding the Picker component:
```Type '{ children: Element[]; migrateTextField: true; showSearch: boolean; value: selecteDate; onChange: (value: selecteDate) => void; placeholder: string; placeholderTextColor: string; fieldStyle: { ...; }; containerStyle: { ...; }; }' is missing the following properties from type 'Pick<any, "value" | "onChange" | "renderExpandableInput" | "renderExpandable" | "onToggleExpandableModal" | "topBarProps" | "rightButtonProps" | "color" | "containerStyle" | ... 436 more ... | "pickerModalProps">': renderExpandableInput, renderExpandable, onToggleExpandableModal, topBarProps, and 433 more.ts(2740)```

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

### Environment

- React Native version: 0.69
- React Native UI Lib version: 6.21.0

**Comment by ScaredIbis** [comment]
also experiencing this, tried to solve by creating our own wrapped `Picker` which overwrited types with `Partial<originalProps>` but was a pain. ended up downgrading `react-native-ui-lib` to `6.20.4` to solve typescript errors for now.

Environment: 
- React Native UI Lib version: 6.21.0
- React Native version: 0.69

**Comment by LazyAfternoons** [comment]
> also experiencing this, tried to solve by creating our own wrapped `Picker` which overrode types with `Partial<originalProps>` but was a pain. ended up downgrading `react-native-ui-lib` to `6.20.4` to solve typescript errors for now.
> 
> Environment (looks like you've got yours around the wrong way btw):
> 
> * React Native UI Lib version: 6.21.0
> * React Native version: 0.69.5

Thank you for confirming this issue. 
Environment fixed, thanks.

**Comment by MiguelAraCo** [comment]
Also experiencing this. The latest version (6.23.0) doesn't seem to fix the issue.

**Comment by The-White-Fang** [comment]
6.23.1 seems broken as well.
In my case I am seeing `Dialog` infered as `const Dialog: React.ComponentClass<any, any> & typeof Dialog`.
Is there a quick fix for it?

**Comment by lewisd1996** [comment]
Also getting this error, says i need to define all 400+ props

**Comment by The-White-Fang** [comment]
Can you show some SS or error/warning text?

**Comment by lewisd1996** [comment]
@The-White-Fang sorry I should of been clearer, I have the exact same error as @LazyAfternoons. 

I have provided the usual basic props, `value`, `onChange` etc.

The TS error says I am missing the other 450+ props, same as OP

**Comment by robpearmain** [comment]
I am getting this error too

 "react-native-ui-lib": "^6.24.0",

**Comment by boonook** [comment]
I am getting this error too

"react-native-ui-lib": "^6.27.1",

**Comment by chrisdrifte** [comment]
Still getting this error
"react-native-ui-lib": "^7.2.0",
