### ISSUE TITLE
Stepper does not apply custom color to buttons.

### ISSUE THREAD

**Issue by LazyAfternoons** [wix/react-native-ui-lib#2252]
## Description
The stepper component doesn't apply any custom color style to buttons, leaving them always in purple. 

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Screenshots/Video
<img width="127" alt="Screenshot 2022-09-12 at 16 30 44" src="https://user-images.githubusercontent.com/12371664/189680775-c9f7fe16-bde2-45a3-b449-3911bc3728c3.png">

### Environment

- React Native version: 0.69
- React Native UI Lib version: 6.21.0

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by dennis3124** [comment]
I took a look at the underlying code. Stepper doesn't support any styling prop. I updated my designToken and it overwrote the stepper button colors. 
` Colors.loadDesignTokens({
    primaryColor: '$AddPrimaryColorHere',
  });`
