### ISSUE TITLE
Cards ignore modifiers if onPress is set

### ISSUE THREAD

**Issue by abn-volk** [wix/react-native-ui-lib#226]
As shown in the following screenshot, the `margin-16` modifier does not work when onPress is set, probably because `Card` extends from `TouchableOpacity` instead of `View.` To work around this problem, style attributes must be set using `styles` (as in the third item).

![Screenshot](https://user-images.githubusercontent.com/1829147/44767858-add3ac80-ab89-11e8-8a43-a7a736f9b508.png)

Expo snack: https://snack.expo.io/Ske1mhmwQ

**Comment by Inbal-Tish** [comment]
Yes. TouchableOpacity does not yet support modifiers (when passing onPress TouchableOpacity is rendered instead of a view). We are aware of the issue and planning to add this support in the future. In the meantime, you can pass padding and margins in the 'style'.
