### ISSUE TITLE
Demo fails npm install

### ISSUE THREAD

**Issue by ssk-mps** [wix/react-native-ui-lib#2271]
## Description

Following the steps from the demo app https://wix.github.io/react-native-ui-lib/docs/getting-started/setup#demo-app fails

### Related to

- [ ] Components
- [x] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

- Install Node LTS (16.17.1) + Npm LTS (8.19.2)
- Clone the project git clone git@github.com:wix/react-native-ui-lib.git
- cd react-native-ui-lib
- Install dependencies npm install

#### Expected behavior

Npm install should not fail.

#### Actual behavior

```
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-native-ui-lib@5.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR! node_modules/@react-native-community/async-storage
npm ERR!   dev @react-native-community/async-storage@"^1.12.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Code snippet

Please see above

### Environment

- React Native version: Same as git@github.com:wix/react-native-ui-lib.git
- React Native UI Lib version: Same as git@github.com:wix/react-native-ui-lib.git
- ❯ node --version
v16.17.1
- ❯ npm --version
8.19.2

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by CodingMeSwiftly** [comment]
Same issue here. `npm i --force` worked. However, that doesn't fix the issue :)

**Comment by mkizesov** [comment]
The issue still exists
