### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by nolife08021** [wix/react-native-ui-lib#2274]
## Description

Hi, can someone please help me to solve this? I keep trying for few days already , but still failed to build it.

> Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_RCTView", referenced from:
      _OBJC_METACLASS_$_SafeAreaSpacerView in SafeAreaSpacerView.o
  "_RCTScreenScale", referenced from:
      -[SafeAreaSpacerView safeAreaInsetsDidChange] in SafeAreaSpacerView.o
  "_OBJC_METACLASS_$_RCTShadowView", referenced from:
      _OBJC_METACLASS_$_SafeAreaSpacerShadowView in SafeAreaSpacerShadowView.o
  "_OBJC_CLASS_$_RCTShadowView", referenced from:
      _OBJC_CLASS_$_SafeAreaSpacerShadowView in SafeAreaSpacerShadowView.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      _OBJC_CLASS_$_RCTCustomInputControllerTemp in RCTCustomInputControllerTemp.o
      _OBJC_CLASS_$_SafeAreaManager in SafeAreaManager.o
  "_RCTRegisterModule", referenced from:
      +[HighlighterViewManager load] in HighlighterViewManager.o
      +[KeyboardTrackingViewTempManager load] in KeyboardTrackingViewTempManager.o
      +[RCTCustomInputControllerTemp load] in RCTCustomInputControllerTemp.o
      +[SafeAreaManager load] in SafeAreaManager.o
      +[SafeAreaSpacerViewManager load] in SafeAreaSpacerViewManager.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      __OBJC_$_CATEGORY_RCTConvert_$_KeyboardTrackingScrollBehavior in KeyboardTrackingViewTempManager.o
      objc-class-ref in RCTCustomInputControllerTemp.o
  "_OBJC_CLASS_$_RCTScrollView", referenced from:
      objc-class-ref in KeyboardTrackingViewTempManager.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in KeyboardTrackingViewTempManager.o
      objc-class-ref in RCTCustomInputControllerTemp.o
  "_RCTContentDidAppearNotification", referenced from:
      -[KeyboardTrackingViewTemp init] in KeyboardTrackingViewTempManager.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RCTCustomInputControllerTemp in RCTCustomInputControllerTemp.o
      _OBJC_METACLASS_$_SafeAreaManager in SafeAreaManager.o
  "__RCTLogNativeInternal", referenced from:
      ___68-[KeyboardTrackingViewTempManager getNativeProps:resolver:rejecter:]_block_invoke in KeyboardTrackingViewTempManager.o
      ___49-[KeyboardTrackingViewTempManager scrollToStart:]_block_invoke in KeyboardTrackingViewTempManager.o
  "_RCTConvertEnumValue", referenced from:
      +[RCTConvert(KeyboardTrackingScrollBehavior) KeyboardTrackingScrollBehavior:] in KeyboardTrackingViewTempManager.o
  "_OBJC_CLASS_$_RCTView", referenced from:
      _OBJC_CLASS_$_SafeAreaSpacerView in SafeAreaSpacerView.o
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_HighlighterViewManager in HighlighterViewManager.o
      _OBJC_CLASS_$_KeyboardTrackingViewTempManager in KeyboardTrackingViewTempManager.o
      _OBJC_CLASS_$_SafeAreaSpacerViewManager in SafeAreaSpacerViewManager.o
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_HighlighterViewManager in HighlighterViewManager.o
      _OBJC_METACLASS_$_KeyboardTrackingViewTempManager in KeyboardTrackingViewTempManager.o
      _OBJC_METACLASS_$_SafeAreaSpacerViewManager in SafeAreaSpacerViewManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

1. yarn add react-native-ui-lib
2. cd ios && pod install

#### Expected behavior
Build Successful.

#### Actual behavior
Failed to build in simulator and physical devices.

```


```

### Screenshots/Video
<img width="1026" alt="Screenshot 2022-10-03 at 11 52 37 AM" src="https://user-images.githubusercontent.com/49778835/193498616-38db2ff5-6733-4663-b6b0-8c692300dda5.png">

### Environment

- React Native version: 0.68.1
- React Native UI Lib version: 6.21.2

### Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by donnes** [comment]
Up, any workaround?

**Comment by nikitph** [comment]
i made it work. Clean everything 
rm -rf node_modules
cd ios pod deintegrate 
cd ..
nvm use 17.0.0
yarn i 
cd ios
pod install
and build through xcode
