### ISSUE TITLE
SkeletonView Bug with react-native-linear-gradient

### ISSUE THREAD

**Issue by ncortesm** [wix/react-native-ui-lib#2284]
## Description

I have tried to use SkeletonView component which requires react-native-shimmer-palceholder and react-native-linear-gradient.
This last library is throwing problems, since when using expo it throws an error. "BVLinearGradient" was not found in the UIManager.

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Screenshots/Video

![IMG_4708](https://user-images.githubusercontent.com/65879583/195429836-bb00f2a4-a18e-46a1-be58-b7a4e7be0d66.jpeg)

### Environment

- React Native version: 0.69.6
- React Native UI Lib version: 6.21.0

### Affected platforms

- [X] Android
- [X] iOS
- [ ] Web

**Comment by michaeldawson** [comment]
See also: https://github.com/wix/react-native-ui-lib/issues/2204 .

This PR: https://github.com/wix/react-native-ui-lib/pull/2264  was opened by charanrajtc 1 month ago, but it hasn't been merged. I've tried forking / making that update locally in this repo, but it doesn't solve the problem for me.

**Comment by ncortesm** [comment]
Thank you for the informatioin michael!!

**Comment by michaeldawson** [comment]
Not stale - see https://github.com/wix/react-native-ui-lib/issues/2204

**Comment by gioramies** [comment]
+1 I'm experiencing the same issue of the original description.

"expo": "~47.0.8",
 "react": "18.1.0",
 "react-native-ui-lib": "^6.25.0",
 "react-native": "0.70.5",
