### ISSUE TITLE
Demo App ios:Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by pravishanth** [wix/react-native-ui-lib#2342]
### Related to
Demo

###  Steps to reproduce the behaviour:
1. Go to `https://wix.github.io/react-native-ui-lib/docs/getting-started/setup#demo-app`
2. Follow the steps and run in iOS

### Expected behaviour
The App shall work in simulator

### Actual behaviour
I get this error in Xcode 
`Command PhaseScriptExecution failed with a nonzero exit code`

### Affected platforms
iOS

**Comment by imanodaysoffdotcom** [comment]
Try this, worked for me

nvm install 'lts/*'
nvm alias default node  

FROM - https://stackoverflow.com/questions/49449719/nvm-n-a-version-n-a-n-a-is-not-yet-installed
Search "Your "default" Node version is not reachable (many reasons)"
