### ISSUE TITLE
Modal and Dialog not rendering with transparent background when default background color for `View` is set by `ThemeManager`

### ISSUE THREAD

**Issue by The-White-Fang** [wix/react-native-ui-lib#2352]
## Description
If you use `ThemeManager` to set the default `backgroundColor` for your View, the transparent `Modal` background color changes to opaque. The issue is that these components are using View components that have been modified using theme manager.

### Related to

- [ x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
Use theme manager to set the detault theme for View component
```
ThemeManager.setComponentTheme('View', (props: { [key: string]: any }) => ({
    backgroundColor: Colors.bgColor,
}));
```

and now try to render the `DIalog` example or `Modal` example.

#### Expected behavior

The modal should render with transparent background.

#### Actual behavior
The modal is rendered with solid background

### Code snippet

```


```

### Environment

- React Native version: 0.70.5
- React Native UI Lib version: 6.24.0

### Affected platforms

- [ x] Android
- [ x] iOS
- [ ] Web

**Comment by phuocantd** [comment]
maybe you using style props
