### ISSUE TITLE
Incubator.WheelPicker only calls onChange every other time

### ISSUE THREAD

**Issue by sseppola** [wix/react-native-ui-lib#2356]
## Description
Incubator/WheelPicker it only calls onChange every other time.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

Render WheelPicker and scroll to multiple different values.
See video.

#### Expected behavior
onChange should be called every time the picker stops.

#### Actual behavior
The picker only calls onChange every other time

### Code snippet

```jsx
import WheelPicker from 'react-native-ui-lib/src/incubator/WheelPicker';
import {range} from 'lodash';

export const Demo = () => {
	const reminderIntervalOptions = range(30, 135, 15).map(value => ({
		value,
		label: `${value} minutes`,
	}));
	
	const [reminderIntervalInMinutes, set_reminderIntervalInMinutes] = React.useState(
		notifications.reminderIntervalInMinutes,
	);

	return (
		<WheelPicker
		  initialValue={reminderIntervalInMinutes}
		  items={reminderIntervalOptions}
		  activeTextColor={'green'}
		  inactiveTextColor={'gainsboro'}
		  onChange={(value: number) => {
		    set_reminderIntervalInMinutes(value);
		  }}
		/>
	)
}
```

### Screenshots/Video

https://user-images.githubusercontent.com/4065840/205452380-73598fa4-de13-4471-9ae6-96304b3f5c6e.mov

### Environment

- React Native version: "0.68.1"
- React Native UI Lib version: "6.25.0"

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by ckachelmeier** [comment]
We had the same issue in our application.  It was an issue with resetting the initialValue all the time.  So things along the lines of `initialValue={currentValue}` seem to cause this issue.

**Comment by asevims** [comment]
I have the same issue.
