### ISSUE TITLE
Picker missing properties error

### ISSUE THREAD

**Issue by robpearmain** [wix/react-native-ui-lib#2365]
In

"react-native-ui-lib": "^6.25.0",

TypeScript shows an error regarding the Picker component:
Type '{ children: Element[]; migrateTextField: true; showSearch: boolean; value: selecteDate; onChange: (value: selecteDate) => void; placeholder: string; placeholderTextColor: string; fieldStyle: { ...; }; containerStyle: { ...; }; }' is missing the following properties from type 'Pick<any, "value" | "onChange" | "renderExpandableInput" | "renderExpandable" | "onToggleExpandableModal" | "topBarProps" | "rightButtonProps" | "color" | "containerStyle" | ... 436 more ... | "pickerModalProps">': renderExpandableInput, renderExpandable, onToggleExpandableModal, topBarProps, and 433 more.ts(2740)

**Comment by boonook** [comment]
I am getting this error too

"react-native-ui-lib": "^6.27.1",

**Comment by robpearmain** [comment]
Just confirming Not fixed in latest release

**Comment by Milutin-P** [comment]
Any news regarding this?
I'm getting this error too on the 6.27.3 version.

**Comment by JSourianos** [comment]
Any more news? Also happening in `6.29.0` version

**Comment by harlandjp** [comment]
Same issue on `"react-native-ui-lib": "7.2.0",`. Any help?

**Comment by robpearmain** [comment]
This seems to be fixed in 7.3.0 though I didn’t see the fix mentioned in the release notes, can others confirm before I close it?
