### ISSUE TITLE
Incubator.Textfield theme not reflected in DateTimePicker

### ISSUE THREAD

**Issue by KishoreBarik** [wix/react-native-ui-lib#2372]
## Description

The properties/styles set via ` ThemeManager.setComponentTheme('Incubator.TextField', {...})` not reflecting on DateTimePicker.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

1. Set styles via ` ThemeManager.setComponentTheme('Incubator.TextField', {...})`.
2. Use DateTimePicker component

#### Expected behavior

The styles set by theme should reflected.

#### Actual behavior

The styles set by theme is not reflected.

### Screenshots/Video

![Screenshot 2022-12-13 at 4 24 11 PM](https://user-images.githubusercontent.com/13726932/207299033-2c770f42-a570-4551-8930-73ac5d234ceb.png)

The first field is a Incubator.Textfield, second one is the DateTimePicker. I expect both to look like same

### Environment

- React Native version: 0.70.2
- React Native UI Lib version: 6.25.0

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by vuhongson-01** [comment]
<DateTimePicker
              title={'Chọn ngày sinh'}
              placeholder={birthday}
              onChange={v => {
                console.log(v);
              }}
              value={new Date()}
              mode={'DATE'}
              dateFormat={'DD.MM.YYYY'}
              renderInput={() => (
                <FontAwesomeIcon
                  icon={faCalendarDay}
                  style={{marginLeft: 6, color: app_color.color1}}
                />
              )}
            />
