### ISSUE TITLE
Cannot resolve symbol 'HighlighterViewPackage'

### ISSUE THREAD

**Issue by scrapecoder** [wix/react-native-ui-lib#2380]
import com.wix.reactnativeuilib.HighlighterViewPackage; `Cannot resolve symbol 'HighlighterViewPackage'`

       public ArrayList<ReactPackage> getPackages() {
        return new ArrayList<>(Arrays.<ReactPackage>asList(
           new MainReactPackage(mConfig),
           new HighlighterViewPackage(),
      ));
    }

- React Native version: 0.70.4
- React Native UI Lib version: ^6.26.0

### Affected platforms

Android

**Comment by efstathiosntonas** [comment]
same here but on iOS 16.2 with rn 0.70.6:

`Invariant Violation: requireNativeComponent: "HighlighterView" was not found in the UIManager.`

**Comment by efstathiosntonas** [comment]
probably related: https://github.com/wix/react-native-ui-lib/issues/2204#issuecomment-1315444150
