### ISSUE TITLE
TextField in iOS is broken inside horizontally centered View since release 6.26.0

### ISSUE THREAD

**Issue by n10l** [wix/react-native-ui-lib#2389]
## Description
Thanks for this amazing library. I found a bug that started appearing after updating packages recently. I am using a horizontally centred TextField.

If parent view has center or centerH, then centered aligned TextField child is not visible since last release 6.26.0. It was working good in 6.25.0. 

Workaround:
Need to give a width on TextField. In this case as well, if there is a leadingAccessory that also needed to be handled in some hacky way to properly center align.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

Use this code with version 6.26.0:

```
<View flexG center>
  <TextField
    text70
    migrate
    height={48}
    placeholder="0"
    maxLength={6}
    value="23" />
</View>

```
<img width="342" alt="Screenshot 2022-12-23 at 11 43 52 PM" src="https://user-images.githubusercontent.com/17937997/209393776-30e23740-0b85-42e3-bf61-11a98115fc5c.png">

#### Expected behavior

TextField should display properly same as in version 6.25.0

<img width="378" alt="Screenshot 2022-12-23 at 11 36 02 PM" src="https://user-images.githubusercontent.com/17937997/209394138-12f9b1c6-968f-43f6-8457-a13ed3c7e885.png">

#### Actual behavior

 I am able to type in TextField but it doesn't display in iOS

- React Native version: 0.67.5
- React Native UI Lib version: 6.26.0

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by ethanshar** [comment]
Releasing hotfix in v6.26.2
