### ISSUE TITLE
Dialog Flickering in iOS

### ISSUE THREAD

**Issue by DedicatedDev** [wix/react-native-ui-lib#2419]
## Description
In iOS device, Dialog close flickering sometimes.

**Comment by siteassist-benjamin** [comment]
Hi, I also have this issue. It is only happening when the background is tapped rather than closed with a button

**Comment by cedric-costa** [comment]
I'm currently encountering the same weird behaviour. The whole screen flickers for a split of a second when the modal close animation finishes.

**Comment by siteassist-benjamin** [comment]
I think I actually solved it by migrating to using Incubator.Dialog instead if just Dialog. Maybe you could try that, at least in my initial testing I didn't manage to replicate the flickering

**Comment by gen02-dev** [comment]
I'm also facing this issue and the fix I made was deleting the fadeOut animation on Dialog node_module. Below is my patch file.


```
diff --git a/node_modules/react-native-ui-lib/src/components/dialog/index.js b/node_modules/react-native-ui-lib/src/components/dialog/index.js
index 0762da1..f495dd1 100644
--- a/node_modules/react-native-ui-lib/src/components/dialog/index.js
+++ b/node_modules/react-native-ui-lib/src/components/dialog/index.js
@@ -96,14 +96,7 @@ class Dialog extends Component {
     });
   };
   onDismiss = () => {
-    const fadeOut = Constants.isIOS && this.props.visible;
-    if (fadeOut) {
-      this.setState({
-        fadeOut
-      }, this._onDismiss);
-    } else {
-      this._onDismiss();
-    }
+    this._onDismiss();
   };
   hideDialogView = () => {
     this.setState({
```
