### ISSUE TITLE
missing type import in Picker types

### ISSUE THREAD

**Issue by meypod** [wix/react-native-ui-lib#2436]
currently [picker types](https://github.com/wix/react-native-ui-lib/blob/master/src/components/picker/types.tsx) is using `ThemeComponent` type, which is not imported from anywhere, and causes Typescript to say that the `PickerProps` is `any` type

~~adding import at top of the file like this fixes the problem (tested locally):
`import type { ThemeComponent } from '../../../typings/globalTypes';`
but this doesn't seem right~~ doesn't work,
replacing the type entirely inline fixes it

**Comment by mb8z** [comment]
Any chance for this to be reopened? Experiencing the same issue, where PickerProps are `any`
