### ISSUE TITLE
Props overrides not working

### ISSUE THREAD

**Issue by tsdevelopment** [wix/react-native-ui-lib#245]
I looked in your documentation and found out that we can override the global properties with the `ThemeManager`. So I wanted to display the shadow for every button:

```javascript
ThemeManager.setComponentTheme('Button', {
  enableShadow: true,
});
```

But it doesn't work. The shadow is missing. What's the trick? I have the same problem with other components and its props, too.

**Comment by Rmannn** [comment]
Not working on Card

**Comment by ethanshar** [comment]
@Rmannn 
What are you trying to do exactly that doesn't work? 
Can you please elaborate? can you add a code example. 
Thanks

**Comment by Rmannn** [comment]
Sorry i am not on my computer, the exact same issue is still present on the Card component, enableShadow: false does not remove the shadow on all Cards.
I had to apply the property on each Card to get it working.
