### ISSUE TITLE
SegmentedControl doesn't use updated callback

### ISSUE THREAD

**Issue by vanjac** [wix/react-native-ui-lib#2493]
## Description

The SegmentedControl always calls the first `onChangeIndex` function it receives. If that callback changes on a later render, it still calls the old version of the function.

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```
const [selectedIndex, setSelectedIndex] = useState(0);
const handleIndexChanged = useCallback((index: number) => {
    console.log("Old index: " + selectedIndex);
    console.log("New index: " + index);
    setSelectedIndex(index);
}, [selectedIndex, setSelectedIndex]);
const segments = [{label: '1'}, {label: '2'}, {label: '3'}, {label: '4'}, {label: '5'}];
return (
    <SegmentedControl segments={segments} initialIndex={selectedIndex}
        onChangeIndex={handleIndexChanged} />
);
```

#### Expected behavior

The "old index" logged should always reflect the previous index value, since the callback is updated every time `selectedIndex` changes.

#### Actual behavior

The "old index" logged is always 0, because the SegmentedControl always uses the first `onChangeIndex` it was given.

### Environment

React Native 0.71.1

React Native UI Lib version 6.29.1

**Comment by vanjac** [comment]
Don't close this, it hasn't been fixed.

**Comment by M-i-k-e-l** [comment]
Hi @trofima,
This should be fixed in the next version (as I assume you've noticed)
