### ISSUE TITLE
Could not find a declaration file for module 'react-native-ui-lib/keyboard'

### ISSUE THREAD

**Issue by whalemare** [wix/react-native-ui-lib#2494]
## Description

Incorrect typings in docs or library

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

### Steps to reproduce

1. Open documentation link: https://wix.github.io/react-native-ui-lib/docs/getting-started/setup#how-does-it-work
2. See usage example
```
...
import {KeyboardTrackingView, KeyboardAwareInsetsView, KeyboardRegistry, KeyboardAccessoryView, KeyboardUtils} from 'react-native-ui-lib/keyboard';
...
```
3. Try to import like docs says in some TypeScript file

#### Expected behavior

Imported without TypeScript errors

#### Actual behavior

TypeScript file has error

```
Could not find a declaration file for module 'react-native-ui-lib/keyboard'
```

## More Info

Next import is resolves without errors, but its just prop types:

```
import { KeyboardTrackingViewProps } from 'react-native-ui-lib/lib/components/Keyboard'
```

### Code snippet

```
No applicable
```

### Environment

- React Native version: 0.71
- React Native UI Lib version: 7.0.0

### Affected platforms

- [] Android
- [] iOS
- [] Web

**Comment by gentlee** [comment]
This bug is still valid, can't just export KeyboardTrackingView from /keyboard as in getting started (facepalm).
