### ISSUE TITLE
KeyboardAwareScrollView component

### ISSUE THREAD

**Issue by mblodorn** [wix/react-native-ui-lib#25]
I'm having trouble to move Views around when keyboard is open. After searching about how can I solve this problem I found the following component:

https://facebook.github.io/react-native/docs/keyboardavoidingview.html

And I think this would be great to have inside react-native-ui-lib. What do you think?

PS: I'm not sure how to implement this, just giving the idea.

**Comment by ethanshar** [comment]
I remember playing with it and it didn't work well,  but maybe it got improved.
it's part of react-native, wdym having it inside of react-native-ui-lib ?

**Comment by mblodorn** [comment]
@ethanshar to use the same properties we use at react-native-ui-lib View.
Example:

<KeyboardAvoidingView flex center>

</KeyboardAvoidingView>

**Comment by ethanshar** [comment]
Hey @mblodorn, 
sorry for the late response. 
What if you'll use the KeyboardAvoidingView component as it is and just wrap our View with it. 
this way you can still enjoy the special feature View provide and still have the KeyboardAvoidingView functionality. 

something like that: 
```
<KeyboardAvoidingView>
   <View flex bg-green10>
         ...
   </View> 
</KeyboardAvoidingView>
```
