### ISSUE TITLE
How do I extend the types of View Props when I add more props via ThemeManager?

### ISSUE THREAD

**Issue by informsharique** [wix/react-native-ui-lib#2514]
## Description
I have added some props on View component via ThemeManager which creates some styles based on those props. Now when I want to use these props in the View component ts complains that this props doesn't exist on ViewProps.

Below is the actual Error

> Type '{ children: any[]; flex: true; row: true; centerV: true; wrap: true; }' is not assignable to type 'IntrinsicAttributes & ViewProps & RefAttributes<View>'.
  Property 'wrap' does not exist on type 'IntrinsicAttributes & ViewProps & RefAttributes<View>'

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

### Steps to reproduce

1. Follow steps from the docs to set styles using custom props
2. There itself no docs is there related to ts. I have put "any" for props argument
3. Use your set prop in the component that you chose for styling. In my case, it was "View" component
4. TS will complain about that error with the error message shared above

#### Expected behavior
Should provide a way to extend the types of the component style that we set using ThemeManager

#### Actual behavior
No docs were found related to extending the types

### Code snippet

```ts
ThemeManager.setComponentTheme('View', (props: any) => {
  return {
    flexWrap: props.wrap ? 'wrap' : props['wrap-reverse'] ? 'wrap-reverse' : 'nowrap',
  };
});
```
### Environment

- React Native version: 0.71.3
- React Native UI Lib version: 7.0.2

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by thanhloc-17** [comment]
up
