### ISSUE TITLE
MaskedInput caret ahead of the value

### ISSUE THREAD

**Issue by haseebnaseem** [wix/react-native-ui-lib#253]
React-Native Version: 0.49.5
react-native-ui-lib version: 3.3.252

Issue: The cursor(caret) is moving a head of the value of text

Here is a gif to explain what is happening
MaskedInput:

![demo](https://user-images.githubusercontent.com/10306624/46655379-e91fbd00-cbc4-11e8-9abc-7f6e5f33c140.gif)

and here is an example of react-native TextInput:
![demo2](https://user-images.githubusercontent.com/10306624/46655429-0b193f80-cbc5-11e8-817a-44637347a490.gif)

**Comment by Inbal-Tish** [comment]
@haseebnaseem Hi. Can you please add your MaskedInput code here?

**Comment by haseebnaseem** [comment]
@Inbal-Tish Hello. Although I fixed the problem,  here is the code: 
```
<MaskedInput
                        onKeyPress={(event)=>console.log(event.nativeEvent)}
                        value={this.state.thisComment.comment}
                        onChangeText={(text)=>this.changeText(text)}
                        ref={r => (this.minput = r)}
                        renderMaskedText={this.renderMaskedText}
                        multiline={true}
                        onContentSizeChange={(event)=>this.updateHeight(event)}
                        underlineColorAndroid='transparent'
                        containerStyle={{justifyContent:'center',height:this.state.height + 20,borderWidth:1,borderRadius:25,borderColor:'#c21f2b',flex:0.95}}
                    />
```
(I apologize for the poor formatting)
The problem was that the TextInput, which is the base of MaskedInput, uses a kind of typography which the user is unaware of. Due to which the text rendered in the `renderMaskedInput` function is of a different size than the invisible TextInput type. Removing `typography` from the styles fixes the issue.

**Comment by haseebnaseem** [comment]
Also while we're at it, maybe the documentation should mention that events like `onKeyPress` can not be consumed since they are overridden.

**Comment by ethanshar** [comment]
Hey @haseebnaseem, why are you using MaskedInput in this case? 
It looks like a simple input will do the work

**Comment by haseebnaseem** [comment]
@ethanshar Hi. The case demonstrated is the simple because I wanted to highlight the problem. The actual use case is of conditional styles (e.g. tagging people in facebook comments)

**Comment by ethanshar** [comment]
@haseebnaseem What about passing true to caretHidden. this way you can hide the caret? 
unless you do want to show the caret.

**Comment by Inbal-Tish** [comment]
@haseebnaseem Can you please send the code for your 'renderMaskedText'? What component are you rendering there?

**Comment by haseebnaseem** [comment]
It's just a normal Text component.

**Comment by Inbal-Tish** [comment]
@haseebnaseem MaskedInput should not have a caret at all as the TextInput is hidden in order to get the input's events, but to to display any ui. We will remove it. All ui adjestements are up to you, passed in the renderMaskedText prop.

**Comment by haseebnaseem** [comment]
That would be one solution, although in my opinion, or maybe just in my use
case, typography could be optional as well.

>

**Comment by Inbal-Tish** [comment]
@haseebnaseem  For a quick fix you can remove your 'multiline={true}' and add 'caretHidden'.

**Comment by haseebnaseem** [comment]
@Inbal-Tish there is significant lag as well between the appearance of the text and the keyboard events. What do you think could be the reason for this ?
