### ISSUE TITLE
Toast with actions not using backgroundColor

### ISSUE THREAD

**Issue by veb** [wix/react-native-ui-lib#255]
Hi,

Thanks for your hard working maintaining this, I love it. 👍 

I'm using: `"react-native-ui-lib": "^3.3.253",`

I've been using the Toast component and I added a custom action to it with:

```
      {
        label: 'Verify',
        color: Colors.wispPink,
        backgroundColor: 'darkred',
      },
```

![image](https://user-images.githubusercontent.com/376245/46699295-dc0ed680-cc75-11e8-812b-dff4efa66ff6.png)

Which works nicely, except the backgroundColor of the button inside the toast doesn't change (as seen in the image). So I had a wee look into the source, and I noticed in `node_modules/react-native-ui-lib/src/components/toast/index.js` that `oneActionStyle` is:

```
    oneActionStyle: {
      borderRadius: BorderRadiuses.br0,
      minWidth: undefined,
      height: '100%',
      backgroundColor: Colors.rgba(ThemeManager.primaryColor, 0.7),
    },
```

I _believe_ the backgroundColor here overrides whatever we pass through in the prop? I tested that by commenting it out and it worked nicely.

My fix was to remove it from the style, and inside `renderOneAction()` do something like:

```
  renderOneAction() {
    const action = _.first(this.props.actions);
    const {contentAnimation} = this.state;

    if (action) {
      return (
        <Animatable.View {...contentAnimation}>
          <Button 
            style={[this.styles.oneActionStyle, { backgroundColor: action.backgroundColor || Colors.rgba(ThemeManager.primaryColor, 0.7) }]} 
            size="medium" 
            {...action} 
          />
        </Animatable.View>
      );
    }
  }
```

![image](https://user-images.githubusercontent.com/376245/46699436-4889d580-cc76-11e8-8a3d-7a5609b144f9.png)

Perhaps I missed something super easy, and I didn't even need to do all of this! I'd be happy to do a PR if it's required.

**Comment by Inbal-Tish** [comment]
@veb Hi. Thanks for the find. I pushed a fix for the action's backgroundColor. Let me know if that solves your issue.

**Comment by veb** [comment]
It works perfectly! Thank you very much @Inbal-Tish :)
