### ISSUE TITLE
Scheme color change when app back from background [iOS]

### ISSUE THREAD

**Issue by tdvuanh** [wix/react-native-ui-lib#2552]
## Description

Hello there, we are using Colors.setScheme to enable dark mode on our application. Unfortunately, when we set `Colors.setSchema('default')`, the colors of the text component will change from the color of the light scheme to the dark scheme every time we put the app in the background and bring it to the foreground again. If we set `Colors.setScheme('light')` or `Colors.setScheme('dark'), everything is fine.

This issue happens on both the simulator and the real device also. 

### Environment

- React Native version: 0.70.6
- React Native UI Lib version: 7.2.4

### Affected platforms

- [ ] Android
- [x] iOS

**Comment by lidord-wix** [comment]
Can you please try to add the following line somewhere at the beginning of your app?
```
require('react-native-ui-lib/config').setConfig({appScheme: 'default'});
```

**Comment by janoslc** [comment]
Hey @lidord-wix and @tdvuanh!

I can confirm the current situation. I already have this line (you mentioned) added in my project but still, the problem is present when putting the app in the background and focus again.

**Comment by tdvuanh** [comment]
we found this issue belong the lib. Just now just use pacth-package to fix the problem.

**Comment by lidord-wix** [comment]
@tdvuanh can you please elaborate on your fix?
