### ISSUE TITLE
setComponentTheme not working

### ISSUE THREAD

**Issue by vendramini** [wix/react-native-ui-lib#2553]
## Description

I've created a new expo project to test and learn. I'm doing this simple line of code and it is not working as expected:
```typescript
ThemeManager.setComponentTheme('TextField', {color: 'red'});
```
However, this is working:
```typescript
ThemeManager.setComponentTheme('Text', {color: 'red'});
```
The full file `index.ts`:
```typescript
import "expo-router/entry";
import {ThemeManager} from 'react-native-ui-lib';

ThemeManager.setComponentTheme('TextField', {color: 'red'});
```
Am I missing something? The `TextField` was supposed to be red but it isn't.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Environment

- React Native version: 0.71.6
- React Native UI Lib version: ^7.2.4

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by halenur** [comment]
I have found a solution for the textfield component theme management. You must  use **'Incubator.TextField'** instead of **'TextField'**.

```jsx
import {ThemeManager} from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Incubator.TextField', () => {
  return {
     fieldStyle: {
        borderWidth: 1,
        borderColor: 'blue',
        borderRadius: 8,
     },
     labelColor: 'red',
     placeholderTextColor: 'purple'
     ...
  }
});
```

**Comment by vendramini** [comment]
You are right @halenur. Where did you find that? I couldn't find it on docs.
Thank you!

**Comment by ilkerceng** [comment]
The Button also didn't work for me.
