### ISSUE TITLE
NumberInput text.replaceAll is not a function error

### ISSUE THREAD

**Issue by halenur** [wix/react-native-ui-lib#2567]
## Description

I've have react native cli app. When I try to use NumberInput component, component gives error when typing.

```jsx
import { NumberInput } from 'react-native-ui-lib';

function MyComp() {
   return (
         <NumberInput
            label="price"
            placeholder="placeholder"
            onChangeNumber={(e) => console.log('onChangeNumber', e)}
          />
   )
}
```

Error is:

```js
TypeError: text.replaceAll is not a function. (In 'text.replaceAll(options.localeOptions.thousandSeparator, '')', 'text.replaceAll' is undefined)
```

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

1. Click to NumberInput component
2. Type something
3. See error

### Screenshots/Video

![Screenshot_1681808446 | 10](https://user-images.githubusercontent.com/13517726/232731188-32c9162c-5c63-424f-b9ea-68e690226575.png)

### Environment

- React Native version: "0.71.4"
- React Native UI Lib version: "^7.2.3"

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by trofima** [comment]
Hi. I can't reproduce it. Can you please check if it still reproduces on the latest version?
