### ISSUE TITLE
TextField with leadingAccessory lets text go over the field border

### ISSUE THREAD

**Issue by Nodirbek3d** [wix/react-native-ui-lib#2578]
## Description

When a leadingAccessory is added to text field, it does not keep text inside the border of field
![IMG_01DA40C0160E-1](https://user-images.githubusercontent.com/10587602/236417887-295470c7-358c-499a-a6c3-e56bf4744739.jpeg)

Code:
```
function TextFieldIcon(props) {
  const {Icon} = props;
  return (
    <View marginR-2>
      <Icon fill={Colors.grey50} height={24} width={24}/>
    </View>
  );
}
```

Using leadingAccessory:

```
        <TextField
          $outlineDanger
          enableErrors={enableAddressErrors}
          leadingAccessory={<TextFieldIcon Icon={LocationSvg}/>}
          onChangeText={(value) => onChange(value, 'location.address')}
          onChangeValidity={(isValid) => setEnableAddressErrors(!isValid)}
          onSubmitEditing={() => refToLandmark.current.focus()}
          placeholder='Address'
          returnKeyType='next'
          value={address}
        />
```

Text field styling:

```
export const tfStyles = StyleSheet.create({
  fieldStyle: {
    fontWeight: 'bold',
    fontSize: 20,
    borderColor: 'red',
    borderWidth: 1,
  },
  container: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    padding: 6,
    marginBottom: 10,
    marginTop: 10,
    justifyContent: 'center'
  }
});
```
If I remove leadingAccessory, text stays within textfield border
### Related to

- [ x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

#### Expected behavior

Text field's text should stay within border

#### Actual behavior

text overflows text field's border

### Code snippet

```


```

### Environment

- React Native version:
- React Native UI Lib version:

### Affected platforms

- [ x] Android
- [ x] iOS
- [ ] Web

**Comment by afdza3** [comment]
I am also facing this issue with trailingAccesory. Kinda made it work like this, but I think it's hacky and letters will be cut off.

```
trailingAccessory={
    <View style={{ position: 'absolute', right: 0, top: 0, bottom: 0, justifyContent: 'center' }}>
        <Ionicons name="chevron-down-outline" size={24} color={Colors.neutral400} style={{ backgroundColor: Colors.$backgroundDefault }} />
    </View>
}
```
