### ISSUE TITLE
Carousel does not fire onChangePage when scrolling on Expo Web

### ISSUE THREAD

**Issue by Bengejd** [wix/react-native-ui-lib#2603]
## Description

RNUI Carousel does not fire onChangePage when scrolling on Web.

### Related to

- [x] Components

### Steps to reproduce

Add Carousel to React-native web project, attempt to access onChangePage

#### Expected behavior

onChangePage should fire, especially when pagingEnabled is set to true.

#### Actual behavior

Nothing happens.

This seems to be because onMomentumScrollEnd is never called (if my testing is correct).

### Code snippet

```
<Carousel onChangePage={() => console.log('page changed')}>
 {_.map(items, item => (
  return renderItem(item, index);
 ))}
</Carousel>


```

### Environment

- React Native version: 0.71.8
- React Native UI Lib version: 6.29.0

### Affected platforms

- [x] Web

**Comment by mdecrocemovson** [comment]
this should be re-opened!

**Comment by Nitzahon** [comment]
Please reopen
