### ISSUE TITLE
Expo Snack Demo is Broken

### ISSUE THREAD

**Issue by eznix86** [wix/react-native-ui-lib#2632]
## Description
The demo from https://wix.github.io/react-native-ui-lib/ seems to be broken.

### Related to

- [ ] Components
- [x] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
1. Go on website mentionned above
2. Click on Expo-Snack Demo
3. Click on tap to play on iOS/Android or Scan QR on the phone.

#### Expected behavior
The demo should be working

#### Actual behavior
Demo is broken

### Screenshots/Video

<img width="270" alt="Screenshot 2023-06-21 at 23 10 56" src="https://github.com/wix/react-native-ui-lib/assets/26553194/80760bcf-4af9-44c2-8397-11a63ab9e81f">

### Environment
Online and On Device

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jderose9** [comment]
Experiencing the same...

**Comment by huix9527** [comment]
Looks this lib is not maintained anymore
