### ISSUE TITLE
ThemeManager doesn't work with Card.Section, etc.

### ISSUE THREAD

**Issue by fhaque** [wix/react-native-ui-lib#264]
When I simply do:

```
ThemeManager.setComponentTheme('Card.Section', (props, context) => {
    console.log('Card.Section', props, context);
    return {};
  });
```

I don't get any logs even when a Card.Section component has been rendered. I also tried `'CardSection'` as an argument. When I put `'Card'` as an argument, I see the logs of the rendered `<Card>` component but not the Card Sections.

**Comment by ethanshar** [comment]
the reason for this is actually because `Card.Section` component is missing a static `displayName`.
anyway,  we plan to depreciate `Card.Section` so there's no need to support it. 
You can use `View` instead.
