### ISSUE TITLE
[Typings] PickerProps is "any"

### ISSUE THREAD

**Issue by mb8z** [wix/react-native-ui-lib#2654]
## Description

`PickerProps` is resolved to `any`

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

### Steps to reproduce

1. This is the line in the github repo: https://github.com/wix/react-native-ui-lib/blob/630cf4633f008b309cf0ca379f79694ef79a2286/src/components/picker/types.tsx#L50
2. This is the actual screenshot from the installed library 
![Screenshot 2023-07-03 at 22 36 27](https://github.com/wix/react-native-ui-lib/assets/16444141/2b96ee7b-6cc2-4dc6-b3d4-74a12b622677)

For some reason `PickerProps` is equal to `any`. Is this because of the `ThemeComponent`?

#### Expected behavior

`PickerProps` should be resolved correctly

#### Actual behavior

`PickerProps` resolved to `any`

### Environment

- React Native version: 0.72
- React Native UI Lib version: 7.5.2

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by ethanshar** [comment]
Should be resolved in our next version
