### ISSUE TITLE
Expo snack preview is broken

### ISSUE THREAD

**Issue by 0xAsimetriq** [wix/react-native-ui-lib#2662]
## Description

Both iOS and Android snack previews are throwing an error for https://snack.expo.dev/@ethanshar/rnuilib_snack something related to ranimated's worklets not being defined.

### Related to

- [ ] Components
- [ ] Demo
- [x] Docs
- [ ] Typings

### Steps to reproduce

Visit https://snack.expo.dev/@ethanshar/rnuilib_snack 

#### Expected behavior

Snack should work

#### Actual behavior

Throws error

## More Info

N/A

### Screenshots/Video

<img width="325" alt="Screenshot 2023-07-08 at 11 52 30" src="https://github.com/wix/react-native-ui-lib/assets/3154053/40f93f68-da39-4959-a04c-5329ec314aca">

### Environment

N/A

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by gastonmorixe** [comment]
still crashing for me in the web emulator and in my iPhone 15 Pro Max
