### ISSUE TITLE
FeatureHighlight functionality

### ISSUE THREAD

**Issue by jontacky** [wix/react-native-ui-lib#268]
Hi, I chanced on this library whiles learning react native and I am loving it. I however am having trouble configuring the native library for the featurehighlight component to work as per your instructions on the docs: https://wix.github.io/react-native-ui-lib/docs/FeatureHighlight/

any help is appreciated

**Comment by jontacky** [comment]
I've finally got this working in iOS but seems to fail in Android, Any help is appreciated:
![screenshot_1541069445](https://user-images.githubusercontent.com/4824373/47850057-d2d3de00-ddcb-11e8-8d5f-b9425af787aa.png)

**Comment by Inbal-Tish** [comment]
@jontacky Please check if you linked the native properly.

**Comment by jontacky** [comment]
Thanks @Inbal-Tish , I failed to link up react-native-ui-lib to android

**Comment by andriinegustorov** [comment]
Hi there. I have problem with FeatureHighlight in React Native 0.60.5 version. Have the same error "Invariant Violation: requireNativeComponent: "HighlighterView" was not found in the UIManager." Can you please help me?

**Comment by Inbal-Tish** [comment]
@andriinegustorov Make sure you linked the native library properly. HighlighterView is a native component from our native library.

**Comment by andriinegustorov** [comment]
no linking needs in RN 0.60+ version or this lib need to be linked?

**Comment by ethanshar** [comment]
@andriinegustorov 
Are you working on iOS or Android? 
Unfortunately the auto-link works great on iOS while Android you still need to manually link the specific component you want. 
We plan to fix it in the near future

**Comment by andriinegustorov** [comment]
It's happening on iOS. I will try to init a new project and add lib to it, maybe problem in my project...
