### ISSUE TITLE
"Slider value is not in range" triggering falsely when useRange is true

### ISSUE THREAD

**Issue by sebastianjung** [wix/react-native-ui-lib#2706]
## Description
console spits out a warning of "Slider value is not in range" in cases when useRange is used and the initialMinimumValue and initialMaximumValue is definitely in the range.

checkProps function checks for props.value which is not used when useRange is true. This is probably the reason for the bug.

```js
checkProps(props) {
    if (props.minimumValue >= props.maximumValue) {
      console.warn('Slider minimumValue must be lower than maximumValue');
    }
    if (props.value < props.minimumValue || props.value > props.maximumValue) {
      console.warn('Slider value is not in range');
    }
  }
```

### Steps to reproduce

using the component like this should trigger the bug:
```jsx
<Slider
                minimumValue={1}
                initialMinimumValue={3}
                initialMaximumValue={6}
                maximumValue={8}
                step={1}
                thumbTintColor={Colors.primary}
                maximumTrackTintColor={Colors.gray5}
                minimumTrackTintColor={Colors.primary}
                useRange
                onRangeChange={({ min, max }) => {
                  console.log('range changed')
                }}
              />
```

**Comment by Inbal-Tish** [comment]
@sebastianjung Hi. The 'value' and 'initialValue' props default is 0. When you set only 'minValue' to 1, 'value' is not in the range.

**Comment by sebastianjung** [comment]
@Inbal-Tish Thank you for your comment.

When using 'useRange' prop the value and initialValue Prop should not be used, right? Only for sliders with one Thumb, right?

I'm probably just confused here.

**Comment by Inbal-Tish** [comment]
Sure. But you are passing initial value... I'll add the check but I suggest not passing initialvalue without value

**Comment by Inbal-Tish** [comment]
@sebastianjung 'nimimumValue' prop should be considered in both cases, but I see your point regarding the 'value' prop. I'll add the check. Thanks
