### ISSUE TITLE
TextField value push trailingAccessory outside of the container if value is too long

### ISSUE THREAD

**Issue by MrSquaare** [wix/react-native-ui-lib#2722]
## Description

Already reported by #2336 with a fix PR #2337. The two of them are closed because of the Stale bot. This is still a problem.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```


```

### Environment

- React Native version: 0.71.8
- React Native UI Lib version: 7.7.0

### Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by nubwang** [comment]
这个问题解决了么？

**Comment by ethanshar** [comment]
Hi @MrSquaare 
Consider passing the `innerFlexBehavior` prop
See [docs](https://wix.github.io/react-native-ui-lib/docs/components/form/TextField#innerflexbehavior)
