### ISSUE TITLE
Card and Button Shadow is disabled

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [wix/react-native-ui-lib#2780]
## Description

Button and Card shadow is not visible

### Related to

- Components

### Code snippet

```
          <Card enableShadow={true}>
            <Text>
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups. Lorem ipsum is placeholder text commonly used in the
              graphic, print, and publishing industries for previewing layouts
              and visual mockups.
            </Text>
          </Card>

```

### Screenshots/Video

![image](https://github.com/wix/react-native-ui-lib/assets/95462949/1be2da82-4440-4359-baab-354c52083f01)

### Environment

- Expo version: ^49.0.7,
- React Native version: 0.72.3
- React Native UI Lib version: ^7.8.0

### Affected platforms

- Android
- iOS

**Comment by SupriyaPKalghatgi** [comment]
@NitzanWix

**Comment by SupriyaPKalghatgi** [comment]
@NitzanWix Is there a work around for this?

**Comment by NitzanWix** [comment]
Hi @SupriyaPKalghatgi, I think it because your background is grey and the shadow is not strong enough. A workaround for now can be using the elevation prop.

**Comment by NitzanWix** [comment]
Hi @SupriyaPKalghatgi, Currently a work around would be by adding shadow using the style prop. We also have some shadow presets of our own. Refer to https://github.com/wix/react-native-ui-lib/blob/master/src/style/shadows.ts.
