### ISSUE TITLE
Dynamic fonts added on v7.9.0+ causes bundling for Expo Web with Metro and react-native-web to break

### ISSUE THREAD

**Issue by brianangulo** [wix/react-native-ui-lib#2788]
## Description

After v7.9.0 and when not using Dynamic Fonts at all when building a react native app for web using Expo, Metro, and react-native-web I encounter a bundling error where the bundler is unable to resolve `PermissonsAndroid`. Please refer to the screenshot found in the sections below. Downgrading to v7.8.0 resolves the issue.

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
Easiest way to repro:

1.  Scaffold an expo-router project using a template: `npx create-expo-app@latest --template tabs@49`
2. Install `react-native-ui-lib`: `npm i react-native-ui-lib`
3. Replace any component with a ui lib component:
```javascript
// import { View } from 'react-native'; // comment this out
import { View } from 'react-native-ui-lib';
```
4. Bundle for web: `npx expo start --web`
5. See error

#### Expected behavior

It should bundle for web without any issues in projects where Dynamic fonts are not being used

#### Actual behavior

Fails to bundle for web

### Code snippet

```javascript
// import { View } from 'react-native'; // comment this out
import { View } from 'react-native-ui-lib';
```

### Screenshots/Video

<img width="1461" alt="Screenshot 2023-10-31 at 1 35 17 PM" src="https://github.com/wix/react-native-ui-lib/assets/59832188/84de0c6d-e238-4c8f-86ec-d322b2ac0aa7">

### Environment

v7.9.0+ failures 🔴 
v7.8.0 works ✅ 

- react-native-web: ~v0.19.6
- React Native version: v0.72.6
- React Native UI Lib version: v7.9.1

### Affected platforms

- [ ] Android
- [ ] iOS
- [X] Web

**Comment by brianangulo** [comment]
Possibly related to: #2736 ?

**Comment by brianangulo** [comment]
Cc: @M-i-k-e-l

**Comment by M-i-k-e-l** [comment]
Hi @brianangulo,
Thanks for the feedback
