### ISSUE TITLE
Card with grey background in the shadow for a white background

### ISSUE THREAD

**Issue by mkharibalaji** [wix/react-native-ui-lib#28]
Hi
     Card is producing a grey background along the border with some width,please find the code and image attached.

Env :
   "react-native-ui-lib": "2.0.70"
    React Native : 0.47.1

style 
`cardContainer:{
		marginRight: 10,
		marginLeft:10,
		marginTop:10,
		borderWidth: 1,
		borderColor: '#D3D3D3',
		...Platform.select({
			ios: {
				backgroundColor : 'transparent'
			},
			android: {
				backgroundColor : 'white'
			}
		})
	},`

`<Card borderRadius={12}
				  containerStyle={styles.cardContainer}
				  enableShadows={false}
				  onPress={viewBlogDetails.bind(this, `${_id}`,`${title}`)}>
              <Card.Section body>
                <Card.Section header>
                  <Text text40 orange40>{title}</Text>
                </Card.Section>
                <Card.Section right>
                  <Card.Item>
                    <Text text90 color={Colors.orange20}>{createdby}</Text>
                    <Text text90> | {moment(createddate).format("YYYY-MM-DD HH:mm")}</Text>
                  </Card.Item>
                </Card.Section>
                <Card.Image style={{marginBottom:10,marginTop:10}} height={120} imageSource={picture} />
                <Card.Section>
                  <Text text70 color={Colors.dark10}>{overview}</Text>
                </Card.Section>
                <Card.Section footer>
                  <Text text90 color={Colors.dark50}>{likes} Likes</Text>
                  <Card.Item>
                  	<Icon name="share-alt" size={20} color={Colors.orange20} />
                  </Card.Item>
                </Card.Section>
              </Card.Section>
				</Card>`

![cardbacgroundgrey](https://user-images.githubusercontent.com/5992474/30895112-b2508580-a365-11e7-9393-3f456bfdb1b7.jpeg)

**Comment by ethanshar** [comment]
hey @mkharibalaji, 
You're using `enableShadows={false}` and it should be `enableShadow` (singular)

**Comment by mkharibalaji** [comment]
@ethanshar Even after removing the enableShadows  i am able to see the grey background and the important thing that i forgot to tell you is i am rendering this items within a Flatlist and when i do it,i am getting a greay bckgroundaround the border of the item.When i give my Flatlist a background colour of white even then it has no effect.

**Comment by ethanshar** [comment]
hey @mkharibalaji,
Sorry for late response, but I meant you should use enableShadow with the value false in order to get rid of the shadow
like this:
```
<Card enableShadow={false} >
```

Now regarding the container, can you paste here a snippet of how the flatlist with its style.
