### ISSUE TITLE
React Native 0.73 - Android does not compile anymore

### ISSUE THREAD

**Issue by santhosh-umapathi-appymango** [wix/react-native-ui-lib#2857]
## Description
After upgrading to RN 0.73, Android does not compile anymore, and throws the following error,
`com.android.tools.r8.internal.Ub: Invalid empty classfile`

### Related to
Android

### Steps to reproduce
1. Upgrade RN to the latest version 0.73
2. Compile the Android app

#### Expected behavior

Android to build the app

#### Actual behavior
Fails due to latest changes from RN upgrade, which has made changes to .jar file

### Code snippet

```
Transform classes.jar (project :react-native-ui-lib) with DexingNoClasspathTransform AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.Ub: Invalid empty classfile","sources":[{"file":"/Users/username/project-name/node_modules/react-native-ui-lib/lib/android/build/intermediates/runtime_library_classes_jar/debug/classes.jar"}],"tool":"D8"}

```

### Environment

- React Native version: 0.73.0
- React Native UI Lib version: 7.12.2

### Affected platforms

- [ X ] Android
- [ ] iOS
- [ ] Web

**Comment by ethanshar** [comment]
Hi @santhosh-umapathi-appymango 
Can you please try again, I have testes react-native-ui-lib on RN73 recently and both iOS and Android build have passed. 
We made some fixes that still weren't released yet, so consider checking on react-native-ui-lib@snapshot version 

Please reopen if you still encounter any issue
