### ISSUE TITLE
NumberInput doesn't support TextField props

### ISSUE THREAD

**Issue by adamzolyak** [wix/react-native-ui-lib#2933]
## Description

For some reason, I can't add `TextField` props to `NumberInput`.

Example
```
Type '{ initialNumber: number; onChangeNumber: (value: NumberInputData) => void; placeholder: string; enableErrors: true; validate: string[]; validationMessage: string[]; showCharCounter: true; maxLength: number; }' is not assignable to type 'IntrinsicAttributes & _NumberInputProps & RefAttributes<TextFieldProps>'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & _NumberInputProps & RefAttributes<TextFieldProps>'.ts(2322)
```

The [docs](https://wix.github.io/react-native-ui-lib/docs/components/form/NumberInput) indicate `NumberInput` should support `TextField` props. 

I also see `TextFieldProps` defined in the type for `NumberInput`

```
const NumberInput: React.ForwardRefExoticComponent<_NumberInputProps & React.RefAttributes<TextFieldProps>>
```

So not sure why it's not working.

Perhaps related to https://github.com/wix/react-native-ui-lib/issues/2515 RE https://github.com/wix/react-native-ui-lib/issues/2515#issuecomment-1476351208?

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

### Steps to reproduce

1. Add a `NumberInput`
2. Try adding a `placeholder` prop
3. Obseve the error (see above)

#### Expected behavior

1. Add a `NumberInput`
2. Try adding a `placeholder` prop without error 
3. Add additional `TextFieldProps` props

#### Actual behavior

See steps to reproduce.

### Code snippet

```
 <NumberInput
          initialNumber={weightValue}
          onChangeNumber={(value) => {
                //TODO:
          }}
          placeholder={'weight value in LBS'}
/>

```

### Environment

- React Native version: 18.2.0
- React Native UI Lib version: 7.16.0
- VS Code Version: 1.85.1 (Universal)

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by M-i-k-e-l** [comment]
Hi @adamzolyak,

That was a bug in the docs (now fixed), `NumberInput` does not actually extend `TextField` but has a `textFieldProps` prop where you can send most of the relevant props (the ones you cannot send directly to `NumberInput` itself).
