### ISSUE TITLE
Missing default check Icon in checkmark after build

### ISSUE THREAD

**Issue by chris-hud** [wix/react-native-ui-lib#2981]
## Description
Weird problem. When I build using Expo for Preview or Production, the the checkmark inside the checkbox does not load. This does not occur if I build on expo for simulator or development. Also, if i send up an OTA update through expo to the preview branch it's fine. This seems like an asset load issue in expo builds however all the other assets that the app uses, from the same locations, load correctly all the time. I'm not doing anything novel with expo builds, using the standard eas build with nothing custom.

### Related to

- Checkbox 

### Steps to reproduce

Build a preview build for ios on expo, use the checkbox. The icon does not appear. 

#### Expected behavior

The checkbox to have a check.

#### Actual behavior

The checkbox does not have an icon for the check.

### Environment

"expo": "^50.0.7",
"react-native-ui-lib": "~7.18.0", also tried "react-native-ui-lib": "~7.10.0",
"react-native": "0.73.4",

### Affected platforms
- [X] iOS

**Comment by chris-hud** [comment]
Discovered this has to do with how image size variants (@2x, @3x, etc) are being bundled. I don't know what is going on, but any assets that are being compiled in expo for me are lost if they have size variants, but not otherwise. This appears to trickle down into libs. Closing this issue as it is unrelated to this library.

**Comment by chunghn** [comment]
Same issue, how to fix it?
