### ISSUE TITLE
Support `bg` for background

### ISSUE THREAD

**Issue by gran33** [wix/react-native-ui-lib#3]
Plz wish me a dream, support `bg-green` like `background-green`.
bg = 2 char count
background = 9 char counts

Thanks yo dream wisher!
<3

**Comment by ethanshar** [comment]
Done!
notice that right now the color constant key comes from the color presets in the UILib, meaning you can't use bg-green but bg-green10 will work (: 
see the list of color constants [here](https://github.com/wix/react-native-ui-lib/blob/master/src/style/colors.js). 

also you can alway define your own colors constants using [this](https://github.com/wix/react-native-ui-lib/blob/master/src/style/colors.js#L94) method
