### ISSUE TITLE
Toast problem

### ISSUE THREAD

**Issue by hanhuhe321321** [wix/react-native-ui-lib#301]
The Toast component dynamically sets the background color, and the color changes instantly after clicking.
For example, the error is red, normal is blue, when the error is shown in red, then click close, the color will first turn blue, and then close.

**Comment by Inbal-Tish** [comment]
@hadadyaniv I'm not sure I understand the issue. Toast component doesn't provide dynamic background by state. Can you explain what are you doing to achieve that?

**Comment by ethanshar** [comment]
@hanhuhe321321 
better even to paste a snippet code of what you're trying to accomplish.

**Comment by ethanshar** [comment]
closing due inactivity
