### ISSUE TITLE
If I do not change the position of the separators and set separatorsStyle={{backgroundColor:'green',}}, the text will be obscured.

### ISSUE THREAD

**Issue by yinminqian** [wix/react-native-ui-lib#3028]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-ui-lib@7.20.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-ui-lib/src/components/WheelPicker/index.js b/node_modules/react-native-ui-lib/src/components/WheelPicker/index.js
index eb17b63..d7fdbe2 100644
--- a/node_modules/react-native-ui-lib/src/components/WheelPicker/index.js
+++ b/node_modules/react-native-ui-lib/src/components/WheelPicker/index.js
@@ -204,6 +204,7 @@ const WheelPicker = props => {
   }, []);
   const offsets = useMemo(() => items.map((_, i) => i * itemHeight), [items, itemHeight]);
   return <View testID={testID} bg-$backgroundDefault style={style}>
+      {separators}
       <View row centerH>
         <View flexG>
           <AnimatedFlatList {...androidFlatListProps} {...flatListProps} testID={`${testID}.list`} listKey={`${testID}.flatList`} height={height} data={items}
@@ -219,7 +220,7 @@ const WheelPicker = props => {
       {label && labelContainer}
       {fader(FaderPosition.BOTTOM)}
       {fader(FaderPosition.TOP)}
-      {separators}
+
     </View>;
 };
 WheelPicker.alignments = WheelPickerAlign;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

<img width="435" alt="image" src="https://github.com/wix/react-native-ui-lib/assets/28828271/f933c7a7-2213-4802-84b9-769206c41940">
<img width="457" alt="image" src="https://github.com/wix/react-native-ui-lib/assets/28828271/6a58e290-a2b2-4a6b-81d2-b27dbb76cdcb">

**Comment by d-moreira** [comment]
Facing the same issue. Imo the default behaviour should be the one described here.

**Comment by adids1221** [comment]
Hi @yinminqian,
The issue is fixed, it will be out in the next release.

**Comment by yinminqian** [comment]
Thank you, great work！！！

**Comment by yinminqian** [comment]
> Hi @yinminqian, The issue is fixed, it will be out in the next release.

Thank you, great work
