### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [wix/react-native-ui-lib#3063]
## Description

Upgrading to latest of react native and expo, I get this with RNUI ActionSheet

### Related to

- [ ] Components

### Screenshots/Video

![image](https://github.com/wix/react-native-ui-lib/assets/95462949/9de74136-c7a8-408f-be33-dfcc09ee7be7)

### Environment

- React Native version: 0.74.1
- React Native UI Lib version: 7.21.2
- Expo version: 51.0.0

### Affected platforms

- [ ] Android
- [ ] iOS

**Comment by Eliost** [comment]
Same warning for me

**Comment by Ryan-Durling** [comment]
Same

**Comment by ronnioliveira** [comment]
same

**Comment by SwanHub** [comment]
here too

**Comment by thanhmati** [comment]
![image](https://github.com/wix/react-native-ui-lib/assets/163371270/a672f6e0-9374-4992-8319-09d7d055d9d8)
same too

**Comment by Arnoldnuo** [comment]
same too

**Comment by alexattt** [comment]
same warning, after updating expo sdk and react native. for now, I see it when using Dash component, which uses defaultProps. 
hope this will be resolved soon!

**Comment by crazyshakalaka** [comment]
Warning: TabController.TabBar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.


me tooooo

I hope to solve this problem as soon as possible

**Comment by crazyshakalaka** [comment]
I can bring up a PR myself to fix this

**Comment by hcweb** [comment]
when i use picker ame

**Comment by adids1221** [comment]
#3285
