### ISSUE TITLE
In Dialog Text Input needs to be clicked twice when keyboard is open.

### ISSUE THREAD

**Issue by ArjunRajesh** [wix/react-native-ui-lib#308]
I have two text input fields in dialog. I clicked the first text input keyboard comes with no problem but on clicking second text field keyboard closes then needs to be tapped again to reopen the keyboard.

**Comment by ArjunRajesh** [comment]
Tried with modal also same effect

**Comment by Inbal-Tish** [comment]
Hi. I can't reproduce the issue. It seem to work fine when I place two TextField components in a modal or in a Dialog. Can you elaborate or send a code snippet?

**Comment by ethanshar** [comment]
closing due inactivity
