### ISSUE TITLE
useSafeArea is not working on Android

### ISSUE THREAD

**Issue by robinclaes** [wix/react-native-ui-lib#3109]
## Description
When using <Incubator.Toast>, it uses `<View useSafeArea>`, but our toast still appears behind notch/camera on Android

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

Render a Toast (from Incubator) on the root View on an Android device with a notch
_or_
Render a `<View useSafeArea></View>` on the root View of an Android device with a notch

#### Expected behavior

It renders under the notch

#### Actual behavior

It renders behind the notch

## More Info

What works for us is this, but feels hacky.

```typescript
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Toast as RNUIToast, ToastProps } from 'react-native-ui-lib/src/incubator';
import { isAndroid } from '../util/general';

export function Toast(props: ToastProps) {
  const insets = useSafeAreaInsets();
  // ? We add the style because the useSafeArea is not working on Android
  return <RNUIToast {...props} style={isAndroid && { marginTop: insets.top }} />;
}
```

### Environment

- React Native version: 0.73.6
- React Native UI Lib version: 7.23.2

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by adids1221** [comment]
Hi @robinclaes, the issue seems stale.
I'm closing the issue due to inactivity.
If you have another question please open a new issue, note that as I mentioned:

> useSafeArea is working only in IOS by default.
