### ISSUE TITLE
use TabController.TabBar is error, the err message is Error: TabController.TabBar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. 

### ISSUE THREAD

**Issue by crazyshakalaka** [wix/react-native-ui-lib#3154]
### Related to

- [✅] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```


```

### Environment

- React Native version: 0.74.2
- React Native UI Lib version: ^7.23.5

### Affected platforms

- [✅] Android
- [✅] iOS
- [ ] Web

**Comment by crazyshakalaka** [comment]
I will submit a PR for repair

**Comment by adids1221** [comment]
@crazyshakalaka Hi, please fill the issue with the necessary data.
Currently the issue only described in the title, make sure to fill all the fields thank you.
