### ISSUE TITLE
ProgressiveImage did not be exported but it's in doc

### ISSUE THREAD

**Issue by zxh-994** [wix/react-native-ui-lib#3172]
### Related to

- [x] Components
- [ ] Demo
- [x] Docs
- [ ] Typings

### Code snippet

```


```

### Environment

- React Native version:
- React Native UI Lib version:

### Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by zxh-994** [comment]
https://wix.github.io/react-native-ui-lib/docs/components/media/ProgressiveImage

**Comment by adids1221** [comment]
The ProgressiveImage is now exported.
