### ISSUE TITLE
ActionSheet onDismiss() call before onPress in each option call

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-ui-lib#32]
Dear all,
For ActionSheet on iOS (not Android), when we touch the option, onDismiss() is called before the onPress() in each option call. Therefore, if we use options in redux or state, after onDismiss, we clear the options, the ActionSheet re-render again and no options. So, the onPress is never called.
We can work around by no clear options after onDismiss()

**Comment by ethanshar** [comment]
Hey @moonjava2005, 
Sorry for late response, I fixed the order of invocation so that the option handler is being called before the onDismissModal callback.
