### ISSUE TITLE
"white is invalid text color" on update to 3.9

### ISSUE THREAD

**Issue by juddey** [wix/react-native-ui-lib#327]
Hello, I've just upgraded to 3.9 from 3.2 on a project and I have found this when I add the LoaderScreen Component to a page, like so:
`<LoaderScreen color={'#1500cc'} />`

![image](https://user-images.githubusercontent.com/7445602/50119600-1de07c80-02b8-11e9-8286-1b14ca68aa11.png)

Running on an android 6.0 emulator. Reinstalled app, deleted node_modules and reset cache.

When I roll back to 3.2.18 I don't get the same issue. Strange. A bug? :bug:

**Comment by ethanshar** [comment]
I couldn't reproduce it on Google Nexus 5 (6.0)

**Comment by juddey** [comment]
Thanks Ethan! I'll close this for now then, and see if I can do a little more isolation to narrow it down.
