### ISSUE TITLE
Dialog Component  Warning: IGNORE: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by aklkbqx** [wix/react-native-ui-lib#3285]
## Description
I ran into a problem. Warning: IGNORE: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. To use Dialog 

### Related to

- [✔️] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```
<Dialog
visible={dialoglVisible}
        panDirection={PanningProvider.Directions.DOWN}
        onDismiss={() => setDialoglVisible(false)}
        containerStyle={{}}
        overlayBackgroundColor="rgba(0, 0, 0, 0.5)"
        width="100%"
        height={null}
        useSafeArea={true}
        ignoreBackgroundPress={false}
      >
```

### Screenshots/Video

![Screenshot 2567-10-01 at 18 47 04](https://github.com/user-attachments/assets/6c211455-b869-4e81-a402-90246bb9d629)

### Environment

- React Native version: 0.74.5
- React Native UI Lib version: 7.32.0

### Affected platforms

- [✔️] Android
- [✔️] iOS
- [✔️] Web

**Comment by emiliogaines** [comment]
Experiencing the same issue.

`<Dialog visible={true} />`

**Comment by iSued** [comment]
This is not completed @ethanshar
