### ISSUE TITLE
Library does not work with React Native version 0.76.0

### ISSUE THREAD

**Issue by cagataykapuagasi** [wix/react-native-ui-lib#3320]
## Description

The `react-native-ui-lib` library does not work as expected with React Native version 0.76.0. (New arch enabled by default)

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

1. Install `react-native-ui-lib` in a React Native project with version 0.76.0.
2. Import a component from `react-native-ui-lib` in your code.
3. Attempt to render the component.
4. Observe that the component does not render or throws an error.

#### Expected behavior

The component from `react-native-ui-lib` should render correctly without any errors.

#### Actual behavior

The component fails to render, and an error message is displayed indicating compatibility issues with React Native version 0.76.0.

### Environment

- React Native version: 0.76.0
- React Native UI Lib version: 7.32.0

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

## Screenshots/Video
![image](https://github.com/user-attachments/assets/9dbdcebc-5e09-4140-97b2-48a498085e6e)

**Comment by Lemon-Hero** [comment]
I am very anxious about this because my project is not progressing

**Comment by cagataykapuagasi** [comment]
it's not about the #3329. It's about the bridge and new arc. None of the components are working.

**Comment by sivantha96** [comment]
I was able to get the project up and running with fabric with #3329 fixes

**Comment by brycelund** [comment]
This library is completely unusable currently for apps running Fabric

**Comment by brycelund** [comment]
@sivantha96 This is a noob question, but how do you use your fork in the project?
Adding this to my package.json and installing doesn't seem to work.
```"react-native-ui-lib": "github:sivantha96/react-native-ui-lib"```

**Comment by nitzanyiz** [comment]
Hi! we've merged a fix for this (#3425). It will be available next version.

**Comment by nitzanyiz** [comment]
Hi! we've merged a fix for this (#3425). It will be available next version.
