### ISSUE TITLE
 ERROR: Cannot read property 'bubblingEventTypes' of null

### ISSUE THREAD

**Issue by minhnc** [wix/react-native-ui-lib#3393]
## Description
Hi there, Im trying to run demo app, it all works perfectly on iOS but got error in Android

`Cannot read property 'bubblingEventTypes' of null
`

Error is related to https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/FeatureHighlightScreen.tsx

### Related to

- [x] Components
- [x] Demo
- [x] Docs
- [ ] Typings

### Steps to reproduce

- pull sample code and run with latest React Native 0.76

### Screenshots/Video

![Screenshot_1731646696](https://github.com/user-attachments/assets/14b67d1a-ba1a-4728-abee-4be7fb1a8f60)

### Environment

- React Native version: 0.76.2
- React Native UI Lib version: 7.34.0

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by adids1221** [comment]
Hi @minhnc does this issue reproduced on RN `0.73`?

**Comment by minhnc** [comment]
Hi @adids1221, it happens on RN 0.76 with legacy architecture. I tried with 0.73 and got the same. Thanks!

**Comment by adids1221** [comment]
Hi @minhnc , since `HighlighterView` is an native component you should check your native "side".
Try to `gradle` clean before running the android app: ([StackOverflow](https://stackoverflow.com/a/34027482))
```
./gradlew clean build (Mac and Linux) -With ./

gradlew clean build (Windows) -Without ./
```

I'm running RN `0.73` on Pixel 6 API 33 and I didn't managed to reproduce the issue.

**Comment by minhnc** [comment]
Thanks @adids1221. I pretty sure did clean cache/gradle many times. Will try again.
But curious any timeline when this lib can support latest RN 0.76? Thanks!

**Comment by adids1221** [comment]
You welcome mate @minhnc 😃 .
We don't have an ETA at the moment.

Please update after you try again, if we can close the ticket.

**Comment by adids1221** [comment]
We will update soon as we will upgrade the RN version.
You welcome, thank you @minhnc.

**Comment by M-i-k-e-l** [comment]
Hello,

We have a version that supports new-arch (RN77), you can use the `next` tag for now.
Please make sure to go over the [v8 doc](https://github.com/wix/react-native-ui-lib/blob/v8/docs/getting-started/v8.md), it includes breaking changes and some known issues.
