### ISSUE TITLE
Toast should not be transparent by default

### ISSUE THREAD

**Issue by overengineered** [wix/react-native-ui-lib#34]
At the moment Toast without customisation has transparency. This creates usability problems, since it appears over other components in the app.

**Comment by ethanshar** [comment]
Hey @overengineered,
You can easily custom it by sending the backgroundColor you wish to have, this will override the default transparent background. 

If you like, you can set the default value for the Toast background **once** using the _ThemeManager_ as follows
```
import {ThemeManager} from 'react-native-ui-lib';

ThemeManager.setComponentTheme('Toast', {
  backgroundColor: 'blue',
});
```

Make sure to do so at a startup point of the app.
