### ISSUE TITLE
Reset a Picker with floating placeholder

### ISSUE THREAD

**Issue by LaszloDev** [wix/react-native-ui-lib#340]
Problem:
The placeholder is displayed twice after resetting the value of the Picker to null, when `floatingPlaceholder=true`

Expected behavior:
The placeholder should only be displayed once.

Package version: 3.11.0

Code sample:
```javascript
<Picker
    placeholder="Pick a player"
    placeholderTextColor="rgba(236, 235, 235, 0.5)"
    floatingPlaceholder
    floatingPlaceholderColor="rgba(236, 235, 235, 0.5)"
    value={value}
    onChange={onChange}
    topBarProps={{ title: 'Players' }}
    text70
    white
    showSearch
    style={{ backgroundColor: 'transparent' }}
>
    {items}
</Picker>
```

See "Team 1" first selection (the 3D effect for the other picker placeholder text is another issue, see https://github.com/wix/react-native-ui-lib/issues/304)

![img_0788](https://user-images.githubusercontent.com/10655255/50527391-3cc8e500-0ae8-11e9-8c4b-3a71804ebbb1.PNG)

**Comment by ethanshar** [comment]
Hey @LaszloDev, 
You're right there's a bug, try removing `floatingPlaceholder`
Since the Picker opens a modal with options, the effect of the floating placeholder isn't really shown, so you can just remove it.
