### ISSUE TITLE
TypeError: Cannot read property 'getHeight' of null

### ISSUE THREAD

**Issue by philymurph** [wix/react-native-ui-lib#3430]
Hi,

I have an issue running my app on iOS with new architecture enabled:

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

"react-native": "0.76.3",
"react-native-ui-lib": "7.34.2",

The following error happens when starting the application:

 (NOBRIDGE) LOG  Bridgeless mode is enabled
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'getHeight' of null
 INFO  

Has anybody seen a similar issue

![Simulator Screenshot - iPhone 16 - 2024-12-01 at 20 34 37](https://github.com/user-attachments/assets/e0c788db-88e5-4fb7-99ee-e65aab0e6d5b)

**Comment by Fireclunge** [comment]
Got the same thing and it only happens when the application has been built. The error doesn't seem to appear in expo go

**Comment by philymurph** [comment]
> Got the same thing and it only happens when the application has been built. The error doesn't seem to appear in expo go

Thanks @Fireclunge , good to know. I'm not using the Exo Framework within my project

**Comment by Fireclunge** [comment]
> I have the same issue did you get any solution @philymurph

It should be fixed next release https://github.com/wix/react-native-ui-lib/pull/3425

**Comment by philymurph** [comment]
> > I have the same issue did you get any solution @philymurph
> 
> It should be fixed next release #3425

Great! Thanks @Fireclunge

**Comment by ybaioumy** [comment]
> > I have the same issue did you get any solution @philymurph
> 
> It should be fixed next release #3425

Hello @Fireclunge 

when is the next release and is there is a work around? 

Thanks!

**Comment by adids1221** [comment]
Hi, #3425 as been released on version `7.34.6`.
Closing this Issue, fixed by this Pr.

**Comment by adids1221** [comment]
Hi, #3425 as been released on version `7.34.6`.
Closing this Issue, fixed by this Pr.
