### ISSUE TITLE
typescript error: BaseInput.d.ts does not exist

### ISSUE THREAD

**Issue by arolson101** [wix/react-native-ui-lib#363]
There is no BaseInput.d.ts in the npm package, resulting in this error when trying to use e.g. TextInput:
```
JSX element type 'TextInput' is not a constructor function for JSX elements.
  Type 'TextInput' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more. [2605]
```

it also looks like typings are missing for featureHighlight, switch, tabBar

**Comment by Epick362** [comment]
A lot of components are missing their Typescript definitions unfortunately. Related issue #44 is very old. Is there any update on this @ethanshar ?

**Comment by ethanshar** [comment]
Hey @Epick362, 
We were working on a process that generates d.ts file automatically out of our JS code. 
Unfortunately, it was a work in progress and got lowered in priority. 
I had recently removed the typing files since they were incomplete and not up-to-date. 

I do hope we'll return to work on supporting d.ts soon.

**Comment by altruisticsoftware** [comment]
@ethanshar Please bring it back 🥇I imagine that would be the only resistance one could have switching over from a lib such as Nativebase. Love what you're doing with this!

**Comment by dungnguyen10989** [comment]
@ethanshar : I really like your repositories, I used many your repositories in our projects, but except react-native-navigation, almost other repositories don't exists type defination. We're using TS for our project, so a lot of restrictions occur when using your repositories. Can you tell me when you bring TS support back to these repositories?

**Comment by ethanshar** [comment]
We've recently added type definition to all of our components, please update you version and check again.
