### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mnlbox** [wix/react-native-ui-lib#365]
Hi,
I can't find any docs about how to install this. Can you guide me?

**Comment by Inbal-Tish** [comment]
`npm install react-native-ui-lib'

**Comment by mnlbox** [comment]
Thanks, Please add this to `ReadMe.md` or `docs`.

**Comment by ethanshar** [comment]
have updated our Wiki
https://github.com/wix/react-native-ui-lib/wiki/SETUP

**Comment by helenamcfreire** [comment]
"choose the native component you want to use".

Which are the possibilities here? I wanna use TagsInput and Picker

**Comment by ethanshar** [comment]
hey @helenamcfreire,
regarding TagsInput, see this - https://github.com/wix/react-native-ui-lib/wiki/TagsInput, you will need the `TextInputDelKeyHandlerPackage` 
Picker is mostly JS code, but if you want to use the native picker mode (for Android) you'll have to add the `WheelPickerPackage` as well.
