### ISSUE TITLE
RN 0.50.3 Error by React.PropTypes

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-ui-lib#39]
Dear all,
I found there're some "React.PropTypes.string,React.PropTypes.xxx" in the module
Therefore, with React 0.50.3, the error will occur
undefined is not object (evealuating '_react2.default.PropTypes.string')
because React.PropTypes is not existing. Should change to PropTypes only

**Comment by cheuk3** [comment]
I got the same error with expo v22 and react-native 0.50.3 also
really hope this awesome library will work on expo :D

**Comment by gsaandy** [comment]
I'm also facing the same issue with react-native@0.51.0

**Comment by ethanshar** [comment]
@moonjava2005 @gsaandy @cheuk3  
please try now with version 2.0.131. 
Apparently I missed some old React.PropTypes usages in the code. 
keep me posted

**Comment by gsaandy** [comment]
@ethanshar working with 2.0.131 👍

**Comment by acomito** [comment]
@cheuk3 did you ever try this working with expo? It has those native dependencies, so...

**Comment by cheuk3** [comment]
@acomito yes its working fine with expo
