### ISSUE TITLE
How to disable dismissSwipe in Dialog component

### ISSUE THREAD

**Issue by mnlbox** [wix/react-native-ui-lib#428]
Hi guys,
now Dialog component has a dismissSwipe feature and when user swipe dialog component to down dialog closed.
How we can disable this dismissSwipe behaviour?
Is it possible now?

**Comment by Inbal-Tish** [comment]
@mnlbox Dialog component now comes with pan gesture by default. If you wish to disable it just pass `disablePan` prop.

**Comment by mnlbox** [comment]
I also set `disablePan={true}` but still it's pan gesture working for me :thinking:

**Comment by mnlbox** [comment]
@Inbal-Tish Any guide?
I think it's a bug. :thinking:

**Comment by ethanshar** [comment]
@mnlbox 
Which version of uilib do you have installed?

**Comment by mnlbox** [comment]
@ethanshar This issue still happens also in latest version.

**Comment by M-i-k-e-l** [comment]
Hi @mnlbox,
There's an example for disabling the pan gesture here: https://github.com/wix/react-native-ui-lib/blob/6a6c51f82292074c5d34cf5e4772c18987f89368/demo/src/screens/componentScreens/DialogScreen.js#L192
I've just tested and it is working correctly.
Please let us know if this helped you.
