### ISSUE TITLE
Install on windows fails

### ISSUE THREAD

**Issue by andrew-a-hall** [wix/react-native-ui-lib#436]
While installing latest (current) version on windows, postinstall script fails:

C:\DEV_local\Development\minfosMobile>npm install --save react-native-ui-lib

> react-native-interactable@0.1.10 postinstall C:\DEV_local\Development\minfosMobile\node_modules\react-native-interactable
> ln -sf lib/{ios,android} .

'ln' is not recognized as an internal or external command,
operable program or batch file.

"dependencies": {
    "@react-native-community/async-storage": "^1.3.4",
    "@react-native-community/netinfo": "^2.0.8",
    "babel-plugin-module-resolver": "^3.2.0",
    "core-decorators": "^0.20.0",
    "lodash": "^4.17.11",
    "mobx": "^5.9.4",
    "mobx-devtools": "^0.9.21",
    "mobx-devtools-mst": "^0.9.21",
    "mobx-react": "^5.4.3",
    "mobx-state-tree": "^3.14.0",
    "react": "16.8.6",
    "react-native": "^0.59.5",
    "react-native-config": "^0.11.7",
    "react-native-git-upgrade": "^0.2.7",
    "react-native-navigation": "^2.18.4",
    "react-native-version-number": "^0.3.5",
    "xmldom": "^0.1.27",
    "jsc-android": "241213.x.x"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-typescript": "^7.3.3",
    "@types/react-native": "^0.57.51",
    "babel-jest": "24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.54.0",
    "react-test-renderer": "^16.8.6",
    "tslint": "^5.16.0",
    "tslint-config-airbnb": "^5.11.1",
    "tslint-react": "^4.0.0",
    "typescript": "^3.4.5"
  },

**Comment by vadsaaa** [comment]
+1 same problem

**Comment by ntha79** [comment]
+1 Me too. Please help!!!

**Comment by andrew-a-hall** [comment]
Use Git Bash to install on Windows. Works well.


________________________________

**Comment by chppeng** [comment]
Try this. It's work well on Windows.

npm install --ignore-scripts --save  react-native-ui-lib

**Comment by vadsaaa** [comment]
> Try this. It's work well on Windows.
> 
> npm install --ignore-scripts --save react-native-ui-lib


cool, this works well. thank you

I use yarn ...

> yarn add --ignore-scripts --dev react-native-ui-lib

**Comment by hao896259037** [comment]
@chppeng Thank you very much! Solved my problem!
