### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ericwooley** [wix/react-native-ui-lib#44]
I don't have time to write, them, but it would be great if someone did. As far as I can tell, there is not typescript support for this.

**Comment by mechabyte** [comment]
I can take a look at it once I've got some spare time this weekend

**Comment by jlawrencecfm** [comment]
+1 for this, my IDE is very unhappy!

**Comment by Alain00** [comment]
Any progress on this?

**Comment by ethanshar** [comment]
typings were updated and published on v4.2.1
