### ISSUE TITLE
TextInput onBlur function not working

### ISSUE THREAD

**Issue by cheuk3** [wix/react-native-ui-lib#45]
I found that it passes this.onBlur to RNTextInput but this.onBlur is undefined

**Comment by ethanshar** [comment]
Hey @cheuk3 
Why do you think this.onBlur is undefined? 
this.onBlur arrives from BaseInput which TextInput Component extends.

**Comment by cheuk3** [comment]
oh sorry i found the issue why the onblue function not work which is not related to this library
Thanks :D
