### ISSUE TITLE
Ellipse Button

### ISSUE THREAD

**Issue by VanMen** [wix/react-native-ui-lib#48]
A sample code that I use in my code somehow ends up with complete ellipse for the button like below:

![image](https://user-images.githubusercontent.com/11056366/33789679-ec2442da-dcac-11e7-8777-d8e7a8d009ba.png)

Is there any parameter in button tag that can be use to make a better button shape ?

Windows 7
Android Emulator SDK 16

**Comment by ethanshar** [comment]
Hey @VanMen 
Sorry for the late response, can you tell me which Android device are you running on here? (device model and everything..)
Thanks

**Comment by VanMen** [comment]
Hey @ethanshar,

I'm using AVD (Android Virtual Device) from Android Studio 2.3.3
Screen size: 5.2 (1080 x 1920)
API version: 16
Target Android 4.1 (Google APIs)
CPU: x86
Emulated Performance, Graphics: Software - GLES 2.0


Thanks

**Comment by inbalwix** [comment]
Seems this issue is related to API 4.1 (Google APIs).
You can set the Button's borderRadius prop to change the shape of the button (value of 26 will generate a shape similar to the default button shape in other Android versions).

**Comment by ethanshar** [comment]
resolved
