### ISSUE TITLE
Error with Picker

### ISSUE THREAD

**Issue by JanosSarkezi** [wix/react-native-ui-lib#482]
Error while updating property 'data" of a view managed by: Wheelpicker

null

text cannot be null

"react-native": "~0.59.8"
"react-native-ui-lib": "~3.32.0"

```
<Picker
	onChange={(value: number) => this.props.onChange(value)}
	useNativePicker={true}
>
	{
		options.allIds.map((id: number) => (
			<Picker.Item
				key={options.byIds[id].id}
				value={{value: options.byIds[id].id, label: options.byIds[id].name}}
				disabled={!options.byIds[id].available}
				isSelected={this.props.selectedId === id}
			/>
		))
	}
</Picker>
```

No value provided here is "null", there is no "text" property anywhere in the docus

**Comment by JanosSarkezi** [comment]
Update: this issue is only on Android

on iOS i DO see a select, bu the labels are not displayed

**Comment by Inbal-Tish** [comment]
@JanosSarkezi  Hi. Please move `label: options.byIds[id].name` out of the `value` prop's object and pass it as a prop: label: {options.byIds[id].name}

**Comment by JanosSarkezi** [comment]
![Screenshot (Jul 24, 2019 14_38_14)](https://user-images.githubusercontent.com/22571765/61794113-cd6a6800-ae20-11e9-91e3-53549897d547.png)

after removing param "useNativePicker"

**Comment by JanosSarkezi** [comment]
@Inbal-Tish  that seem to have worked ... in the Doc it stated that "label" is deprecated ...

https://z448401921.github.io/react-native-ui-lib/uilib-docs/public/docs/Picker.Item/
