### ISSUE TITLE
Swipeable Incubator Tabs

### ISSUE THREAD

**Issue by kabus202** [wix/react-native-ui-lib#492]
Is it possible to make the Incubator Tabs swipeable?

**Comment by ethanshar** [comment]
Do you mean so you can scroll between tabs?

**Comment by kabus202** [comment]
@ethanshar  yes indeed

**Comment by ethanshar** [comment]
Well this is a planned feature, hopefully will be added in the near future (:

**Comment by kabus202** [comment]
Nice to hear that this is on scope! :)

**Comment by kabus202** [comment]
@ethanshar any updates on this?

**Comment by ethanshar** [comment]
Hey @kabus202 
See update example screen using the new `TabController.PageCarousel`
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/incubatorScreens/TabControllerScreen/tab3.js
