### ISSUE TITLE
react-native-ui-lib is incompatible with react native 0.60.4 - ANDROID X

### ISSUE THREAD

**Issue by isaacp0310** [wix/react-native-ui-lib#497]
Im, trying to install react-native-ui-lib on **react native 0.60.4** but it seems that react-native-ui-lib
is incompatible with it. 
I have tried to search solutions other forums but i do not get any solution.

```
react-native-cli: 2.0.1 
react-native: 0.60.4 
"react-native-ui-lib": "^3.34.0-snapshot.381"
```

**Comment by ethanshar** [comment]
At the moment we didn't move ourselves to react-native `0.60.X` so I can't tell if we fully-support this version.
We will update once this happen

**Comment by isaacp0310** [comment]
ok, i get it

**Comment by ethanshar** [comment]
please use react-native-ui-lib@rn61 tag till will release it officially.
