### ISSUE TITLE
Provide components into Button label

### ISSUE THREAD

**Issue by igor-lemon** [wix/react-native-ui-lib#533]
Hi guys!
Please add a possibility to pass component into label props.
I want to pass ActivityIndicator into button label while processing some request but I can't do it because I can pass only text.

**Comment by ethanshar** [comment]
Hello @igor-lemon,

you can pass children like in a regular TouchableOpacity component
```
<Button>
  <ActivityIndicator../>
</Button>
```

**Comment by igor-lemon** [comment]
Oh. Ok, thanks. 👍
