### ISSUE TITLE
Invariant Violation issue/Malformed calls from JS

### ISSUE THREAD

**Issue by vdino96** [wix/react-native-ui-lib#536]
Hello,

upon upgrading my react-native project to 0.59.10, I have received the following error when opening Picker:

![rnuilib1](https://user-images.githubusercontent.com/51232663/65022773-dca5f780-d931-11e9-850d-721a7c277351.png)

Debugger: 
![rnuilib2](https://user-images.githubusercontent.com/51232663/65024109-7c648500-d934-11e9-87c4-c16cbe3a73d6.png)

I have searched the other answers from different libraries and it seems that this is the common error when setting the height according to StatusBar height, somehow. 

I have searched through the code and found that the issue is in "Constants.statausBarHeight" that is set in "TopBar.js". When I comment out that part of code, the Picker starts working again.

![rnuilib3](https://user-images.githubusercontent.com/51232663/65023209-a5841600-d932-11e9-9ee8-54244e860d7d.png)

I am not sure if anyone else is having the same problem and I am sure this is not a solution that would be accepted, just pointing out the issue.

**Comment by Epick362** [comment]
Having the same problem. Only seems to happen after I reload the app, though. When I re-run `react-native run-android` the picker modal works again until the next reload.
