### ISSUE TITLE
Picker - Invariant Violation: [1347,"RCTView",51,{"flexDirection":"row","height":"<<NaN>>"}]

### ISSUE THREAD

**Issue by francopetra** [wix/react-native-ui-lib#539]
I upgraded to the latest version and this isssue started to happen in Android (works fine in iOS).

<img width="310" alt="Screen Shot 2019-09-20 at 12 48 44 PM" src="https://user-images.githubusercontent.com/20055787/65349509-f0638f00-dbb9-11e9-9a6a-a6380418fdc0.png">

**Comment by mouthzipper** [comment]
got the same issue

**Comment by vdino96** [comment]
I have the same problem, addressed it in an issue https://github.com/wix/react-native-ui-lib/issues/536, still waiting for response. So tune in at that issue, too.

**Comment by schieck0** [comment]
I have the same problem on all my projects

**Comment by grrrgpratik** [comment]
I have the same problem when updating my react-native to 0.60.4
