### ISSUE TITLE
Dialog  property "useModal" does not work

### ISSUE THREAD

**Issue by jiaozhouzhou** [wix/react-native-ui-lib#564]
I want Cancel the Modal
`<Dialog  migrate  useSafeArea
                bottom={true}
                position="bottom"
                panDirection={PanningProvider.Directions.DOWN}
                visible={show}
                onDismiss={this.toggleDialog}
                containerStyle={style.DialogConent}
                width="100%"
                height="50%"
                //overlayBackgroundColor="transparent"
                useModal={false}
  ><Text>.....</Text></Dialog>`

**Comment by ethanshar** [comment]
@M-i-k-e-l can you take a look please

**Comment by M-i-k-e-l** [comment]
Hi @jiaozhouzhou, 
By using `migrate` you are using the [new Dialog](https://wix.github.io/react-native-ui-lib/docs/public/Dialog/), it does not have a `useModal` property (unlike the [old Dialog](https://wix.github.io/react-native-ui-lib/docs/Dialog/))
