### ISSUE TITLE
Module not found: Can't resolve './PickerDialog' in '/node_modules/react-native-ui-lib/src/components/picker'

### ISSUE THREAD

**Issue by obiwankenoobi** [wix/react-native-ui-lib#571]
When using in expo web I am getting this error when trying to import `AnimatedImage` from the library.

**Comment by tandacedric** [comment]
I have de same problem

 "dependencies": {
    "@react-native-community/blur": "^3.3.1",
    "expo": "^35.0.0",
    "expo-font": "^7.0.0",
    "firebase": "^7.5.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-interactable": "~2.0.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-text-size": "^4.0.0-rc.1",
    "react-native-ui-lib": "^4.0.0",
    "react-native-unimodules": "0.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10"
  },
![image](https://user-images.githubusercontent.com/13773515/70267609-15ba6f00-179f-11ea-823b-6019003a9a09.png)

**Comment by yomi05** [comment]
I also experience the same problem, any solution?

/Users/mac/reactnative/node_modules/react-native-ui-lib/src/components/picker/NativePicker.js
Module not found: Can't resolve './PickerDialog' in '/Users/mac/reactnative/node_modules/react-native-ui-lib/src/components/picker'

**Comment by ethanshar** [comment]
@obiwankenoobi  @yomi05 
Does this issue still occur on latest version of uilib?

**Comment by mbretter** [comment]
just installed 5.1.3 (fresh installation) and I encountered the same problem.
```
"dependencies": {
    "@expo/samples": "~36.0.0",
    "@expo/vector-icons": "~10.0.0",
    "@react-native-community/blur": "^3.4.1",
    "@react-native-community/datetimepicker": "2.1.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-ui-lib": "^5.1.3",
    "react-native-web": "~0.11.7",
    "react-navigation": "~4.0.10",
    "react-navigation-stack": "~1.10.3",
    "react-navigation-tabs": "~2.6.2"
  },
```

**Comment by mbretter** [comment]
ok, probably found the issue, there is no PickerDialog.web.js, so it fails if it is running on the web, android and ios should be fine, though I have not tested it
