### ISSUE TITLE
TextInput component with Jest

### ISSUE THREAD

**Issue by romanpozd-tg17** [wix/react-native-ui-lib#59]
Hey,
There is some prop errors when testing component that includes TextInput.  

    console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed prop type: Invalid prop `cancelIcon` supplied to `Moda.TopBar`.
          in Moda.TopBar (created by TextInput)

    console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed prop type: Invalid prop `iconSource` supplied to `Button`.
          in Button (created by Moda.TopBar)
          in Moda.TopBar (created by TextInput)

    console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed prop type: Invalid prop `source` supplied to `Image`.
          in Image (created by Button)
          in Button (created by Moda.TopBar)

**Comment by inbalwix** [comment]
Hi. Please check why you have 'Moda.TopBar' instead of 'Modal.TopBar' (typo in the word 'Modal').

**Comment by Inbal-Tish** [comment]
Hi. Can we close this issue?
