### ISSUE TITLE
Add RN 0.6x autolink support

### ISSUE THREAD

**Issue by konclave** [wix/react-native-ui-lib#592]
use_native_modules script can't find podspec because it located in lib directory:

`[!] use_native_modules! skipped the react-native dependency 'react-native-ui-lib'. No podspec file was found.`

**Comment by ethanshar** [comment]
I think it just throws the warning but still install the library. 
can u please make sure if `ReactNativeUiLib` pod is installed..  after running `pod install`

**Comment by konclave** [comment]
Seems like pod was not installed after running `pod install`. Only if I manually add link to podspec in Podfile

**Comment by joakimbeng** [comment]
Somehow the symlinked .podspec file does not show up in my `node_modules/react-native-ui-lib` so by creating that symlink manually I got it to work.

**Comment by ethanshar** [comment]
Fixed in v4.2.2
