### ISSUE TITLE
RNUILIB 4.1.0 - RN Blur & RN Interactable are made as mandatory install

### ISSUE THREAD

**Issue by mkharibalaji** [wix/react-native-ui-lib#596]
Hi Team ,
          These packages (RN Blur & RN Interactable) are made mandatory to be installed after upgrading to 4.1.0.Aren't they optional ? As of now they are throwing error "Module not found"

**Comment by ethanshar** [comment]
Before this and other native dependencies were installed by uilib (as part of uilib dependencies).
 
on v4, we moved them to be peer dependencies so you can have better control on their version. 
but unfortunately you will still need those dependencies for uilib to run.

**Comment by mkharibalaji** [comment]
That explains !. Thanks.
