### ISSUE TITLE
Stepper CRASH on iOS

### ISSUE THREAD

**Issue by 7laria** [wix/react-native-ui-lib#608]
Hi, i'm using rn 0.60.5 and when i try to use Stepper on iOS i have:
JSON value 'decrement' of type NSString cannot be converted to NSDictionary
JSON value 'increment' of type NSString cannot be converted to NSDictionary
someone know how to solve?

**Comment by 7laria** [comment]
WORKAROUND: remove all accessibility option from stepper.

**Comment by ethanshar** [comment]
Hey @7laria 
can you check with react-native v0.61.5
it works in our demo app
