### ISSUE TITLE
Cannot install on Windows platform because of  ‘ln’ cmd

### ISSUE THREAD

**Issue by leoxiaoping** [wix/react-native-ui-lib#672]
Cannot install on Windows platform because of  ‘ln’ cmd

**Comment by ahuseyn** [comment]
Looks like I'm getting same error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-ui-lib@5.3.0 postinstall: `ln -s -f lib/ReactNativeUiLib.podspec ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-ui-lib@5.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by ethanshar** [comment]
Hey, 
see these issues 
https://github.com/wix/react-native-ui-lib/issues/436
https://github.com/wix/react-native-ui-lib/issues/628

**Comment by leoxiaoping** [comment]
> Hey,
> see these issues
> #436
> #628

Thanks!
npm install --ignore-scripts --save react-native-ui-lib  
Can work well！

But **ignore-scripts** seems cause  a new problem, native components  can not be setup.
![企业微信截图_20200225165252](https://user-images.githubusercontent.com/9739133/75230950-96619800-57ef-11ea-8ac3-48199af7b3c0.png)

**Comment by ethanshar** [comment]
Unfortunately you will need to manually add native deps for Android.
We're working on making the auto-link work on Android as well (currently works only on iOS)

you can see a ref here 
https://github.com/wix/react-native-ui-lib/blob/master/android/app/src/main/java/com/rnuilib/MainApplication.java
https://github.com/wix/react-native-ui-lib/blob/master/android/settings.gradle#L8
https://github.com/wix/react-native-ui-lib/blob/master/android/app/build.gradle#L80

**Comment by leoxiaoping** [comment]
Good!
It is really a  powerful and beautiful library for react native.

**Comment by leoxiaoping** [comment]
> Unfortunately you will need to manually add native deps for Android.
> We're working on making the auto-link work on Android as well (currently works only on iOS)
> 
> you can see a ref here
> https://github.com/wix/react-native-ui-lib/blob/master/android/app/src/main/java/com/rnuilib/MainApplication.java
> https://github.com/wix/react-native-ui-lib/blob/master/android/settings.gradle#L8
> https://github.com/wix/react-native-ui-lib/blob/master/android/app/build.gradle#L80

Good! Helpful! 
It is really a powerful and beautiful library for react native.

**Comment by ethanshar** [comment]
this issue has been fixed. we have removed the `postinstall` script. 
Install should work fine on a windows machine
