### ISSUE TITLE
document demo 404

### ISSUE THREAD

**Issue by DungBuiDeveloper** [wix/react-native-ui-lib#678]
please check 

https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/InputsScreen.js

**Comment by ethanshar** [comment]
Hey @DungBuiDeveloper 
Is the link broken on the TextField page I assume?

**Comment by DungBuiDeveloper** [comment]
yes ! i read document on your website but when i click some link left bar 404 page is showing on github page

**Comment by ethanshar** [comment]
looking into it..

**Comment by DungBuiDeveloper** [comment]
for save your time
https://prnt.sc/r9v5az

but let check all link please

**Comment by ethanshar** [comment]
Fix the link. 
It happens rarely when we restructure our files.. 
please check again
