### ISSUE TITLE
Do you accept svg for assets?

### ISSUE THREAD

**Issue by jamesjara** [wix/react-native-ui-lib#683]
Hi guys,

do you support SVG for assets?

```
Assets.loadAssetsGroup('logo', {
  color: require('@assets/logo/color.svg'),
  white: require('@assets/logo/blanco.svg'),
  gray: require('@assets/logo/gris.svg'),
});
```

**Comment by ethanshar** [comment]
Should work, Assets basically keeps the map of requires you load. 
But it won't work with the Image component. you need a way to render the SVG. 
technically you should be able to access the assets like this
`Assets.logo.color`
