### ISSUE TITLE
MaskedInput fails to load for Android...

### ISSUE THREAD

**Issue by juddey** [wix/react-native-ui-lib#684]
Using  `"react-native-ui-lib": "^5.3",`

```
        <View style={{ maxHeight: 48 }}>
          <MaskedInput
            renderMaskedText={renderPrice}
            keyboardType={'number-pad'}
            maxLength={3}
          />
```
Simply adding this component to a screen in Android gives:

![Screenshot_1583390045](https://user-images.githubusercontent.com/7445602/75954317-4a61d200-5f18-11ea-9ef1-3d6272bef1c4.png)

Once I remove this line:
https://github.com/wix/react-native-ui-lib/blob/a59fa060136457475300a6129e554c73f8b5c90f/src/components/inputs/MaskedInput.js#L24

Things are rosy again. Not sure what it was meant to be?

**Comment by ethanshar** [comment]
Hey @juddey 
Unfortunately I don't experience this issue when running on an Android emulator locally.
Can you please provide more details. 
What are u passing for `renderMaskedText`

Which device are u testing on?

**Comment by juddey** [comment]
Oh - thats interesting! I'm away from my desk now but I'll get you some details next week.

**Comment by juddey** [comment]
Closed as no longer presenting in current version,
