### ISSUE TITLE
Cannot build iOS on simulator

### ISSUE THREAD

**Issue by VladRDV** [wix/react-native-ui-lib#691]
```
Unable to resolve module `./dialogDeprecated` from `node_modules/react-native-ui-lib/src/components/dialog/index.js`: 

None of these files exist:
  * node_modules/react-native-ui-lib/src/components/dialog/dialogDeprecated(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native-ui-lib/src/components/dialog/dialogDeprecated/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

error appeared after upgrading to version 5.4.1, vestion 5.3.1 works fine

I've also tried commentong out all Dialog components used in my app, result is the same

**Comment by ethanshar** [comment]
consider resetting cache.
`react-native start --resetCache`

**Comment by VladRDV** [comment]
> `react-native start --resetCache`

tried it, nothing changed

**Comment by ethanshar** [comment]
I almost certain it's a cache issue. 
We removed old files of `dialogDeprecated` in the recent version, that's why you're getting this error. 

Also, I just created a new project using 
`npx react-native init NewApp`
Built it and ran it and it worked.

Then I added rnuilib and its peer dependencies
pod install, rebuilt ios  and it works with no errors

**Comment by VladRDV** [comment]
if you are on `"react-native": "0.61.5"`, go `npm start -- --reset-cache`, then it works fine

@ethanshar  thanks for your help :)
