### ISSUE TITLE
react-native-svg  support

### ISSUE THREAD

**Issue by boxcc** [wix/react-native-ui-lib#693]
I use react-native-svg like: 
```
import React, { FunctionComponent } from 'react';
import { ViewProps } from 'react-native';
import { Svg, GProps, Path } from 'react-native-svg';
import { getIconColor } from './helper';

interface Props extends GProps, ViewProps {
  size?: number;
  color?: string | string[];
}

// If you don't like lots of icon files in your project,
// try to set generate_mode to "all-in-one" in root file "iconfont.json".
// And then regenerate icons by using cli command.
export const Add: FunctionComponent<Props> = ({ size, color, ...rest }) => {
  return (
    <Svg viewBox="0 0 1024 1024" width={size} height={size} {...rest}>
      <Path
        d="M503 195c-9.8 3.4-18 12.4-20.8 22.4-1.4 5-2.2 51.8-2.2 135V480h-127.4c-86.4 0-130.2 0.8-135.6 2.2-16.6 4.6-27.2 22.8-22.8 38.8 2.8 10 12.8 20 22.8 22.8 5.4 1.4 49.2 2.2 135.6 2.2H480v127.4c0 86.4 0.8 130.2 2.2 135.6 2.8 10 12.8 20 22.8 22.8 16 4.4 34.2-6.2 38.8-22.8 1.4-5.4 2.2-49.2 2.2-135.6V546h127.6c86.2 0 130-0.8 135.4-2.2 16.6-4.6 27.2-22.8 22.8-38.8-2.8-10-12.8-20-22.8-22.8-5.4-1.4-49.2-2.2-135.4-2.2H546v-128.6c-0.2-135.4-0.4-137.8-9.4-147.8-8.4-9.2-22-12.8-33.6-8.6z"
        fill={getIconColor(color, 0, '#333333')}
      />
    </Svg>
  );
};

Add.defaultProps = {
  size: 14,
};

export default Add;
```
Is there any way for Assets to support svg instead of displaying them with Images?

**Comment by boxcc** [comment]
I suggest icon supports both Image.source and ReactElement

**Comment by ethanshar** [comment]
@boxcc 
Do you mind proposing a PR I can go over?

**Comment by boxcc** [comment]
Let me try @ethanshar

**Comment by vikasg603** [comment]
> Let me try @ethanshar

@boxcc did you able to find out the solution for it ?
I want to add SVG icons in UILIB but not be able to do this.

**Comment by lander854** [comment]
any progress on this?

**Comment by ethanshar** [comment]
This is something we plan to work on for next Q. 
I'll reopen this

**Comment by M-i-k-e-l** [comment]
Hi all (@boxcc, @vikasg603 & @lander854),
Please see if this helps you out: #1226, you can now send an xml or an SVG file to Image's source.
You'll need to add `react-native-svg` and `react-native-svg-transformer` and also configure them (see `metro.config.js`).

**Comment by vishal38-isharani** [comment]
@M-i-k-e-l @ethanshar great work guys, I was waiting for this fix from last couple weeks.
When you guys planning to release this feature ?

**Comment by M-i-k-e-l** [comment]
This should be out in our next release, I'm assuming it's in a week or two.

**Comment by dalley8626** [comment]
Any update on this?

**Comment by dalley8626** [comment]
I am trying to use svg inside the <Button source /> but i got an error

**Comment by M-i-k-e-l** [comment]
@dalley8626, this was released already.
It's hard to help without any information such as code sample or the error you are getting...
Did you install the dependencies? Is that the error?

**Comment by dalley8626** [comment]
I would like to do something like this 
`import { Feather } from '@expo/vector-icons';
 <Picker
                placeholder="Please select your jacket size"
                useNativePicker
                value={selectedLanguage}
                containerStyle={{ marginBottom: -24 }}
                rightIconSource={<Feather name="navigation" />}
                onChange={(language: string) => setSelectedLanguage(language)}>
                {options.map(option => (
                  <Picker.Item
                    key={option.value}
                    value={option.value}
                    label={option.label}
                  />
                ))}
              </Picker>`

But I do get this error 
![simulator_screenshot_21F447E1-2250-4EED-BAA9-EC3B9573064D](https://user-images.githubusercontent.com/28380930/146088658-1120e3d1-8b00-4502-a4fb-8a98edd873d6.png)

**Comment by M-i-k-e-l** [comment]
I'm not sure how `@expo/vector-icons` are used, but our SVG support is only when sending the SVG to our `Image` component, see [this screen](https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/ImageScreen.tsx) for example.
