### ISSUE TITLE
 Can't resolve ../KeyboardTracking/KeyboardTrackingView in lib/components/Keyboard/KeyboardInput

### ISSUE THREAD

**Issue by colshacol** [wix/react-native-ui-lib#702]
## Steps to reproduce:

_Inside of a boilerplate or application set up of some sort..._

- `yarn add react-native-ui-lib`
- `yarn add react-native-gesture-handler react-native-reanimated @react-native-community/blur react-native-interactable @react-native-community/datetimepicker @react-native-community/netinfo`
- `yarn start` (Whatever command to build the app.)

## Issue: 
![rnuierr1](https://user-images.githubusercontent.com/19484365/76818878-bc69cf00-67d4-11ea-979b-5d7458e2d9c5.png)

## Discovery:

I see that inside of the `KeyboardTracking` directory there exist the files `KeyboardTrackingView.android.js` and `KeyboardTrackingView.ios.js`. There is no `KeyboardTrackingView.js`, though, and I am not sure how Node is expected to resolve them. (Veteran React developer here, new to React Native, though, so I am not familiar if it is supposed to cover this or something.)

![rnuierr](https://user-images.githubusercontent.com/19484365/76818901-ca1f5480-67d4-11ea-8d87-308cf375dde9.png)

**EDIT**: I created a `KeyboardTrackingView.js` and pasted in the source from the `android` file, as it seemed like it would work for web just fine. This allowed me to get past this error, but revealed another file resolution error that fits the same description.

I can't find any note that web is not supported, but I am thinking that maybe the solution to this problem is not code change, but to add this disclaimer to the documentation.

## Environment:

_This issue happens when I use Expo to open the application in the browser._

- Windows 10
- Expo 3.13.1
- Node 12.9.1

![image](https://user-images.githubusercontent.com/19484365/76819355-e5d72a80-67d5-11ea-871a-293742290f7c.png)

**Comment by ethanshar** [comment]
@M-i-k-e-l  Can you take a look please

**Comment by M-i-k-e-l** [comment]
Hi @colshacol,

Thank you for your feedback.

You are indeed correct, this component is not supported on web. It is a native component, which we usually implement for Android and iOS, and in this case it is only for iOS.

You are also correct that this is a documentation problem, the component should appear in our [docs](https://wix.github.io/react-native-ui-lib/docs/), but it doesn't (its doc states this fact) - I'll open a ticket to fix it.

**Comment by soniaisiganporia** [comment]
How did you resolve this issue? I am running into the exact same issue and am not able to move forward.

**Comment by M-i-k-e-l** [comment]
Hi @soniaisiganporia,
If you are you trying to use this component on web, then you'll get this error.
We did fix our docs ([link](https://wix.github.io/react-native-ui-lib/docs/KeyboardTrackingView/)): `This view is useful only for iOS.`

**Comment by soniaisiganporia** [comment]
I'm not trying to use the component -- I am using Expo and trying to utilize the RNUI library but keep getting this message -- my end goal is to use the Card component. 

<img width="1042" alt="Screen Shot 2021-08-04 at 1 00 41 AM" src="https://user-images.githubusercontent.com/82838476/128144479-f0260aa6-0013-448f-8ee9-4690e6bd076c.png">

**Comment by M-i-k-e-l** [comment]
Oh, I see, it seems like a different issue; what version of our lib and RN are you using?

If you are only looking to use a few components, I suggest you import them specifically I think that for `Card` it should be:
```
import Card from 'react-native-ui-lib/card`;
```

You can also open a new ticket, make sure to add the steps you took installing (mentioning it's Expo is important).

**Comment by Surfield** [comment]
Hey team, this is happening to me as well and I'm not even using a keyboard component in my project

**Comment by Surfield** [comment]
`Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

./node_modules/react-native-ui-lib/lib/components/Keyboard/index.js
Cannot find module: './KeyboardTracking/KeyboardTrackingView'. Make sure this package is installed.

You can install this package by running: npm install ./KeyboardTracking/KeyboardTrackingView.
(base) surfthomas@Surfs-MacBook-Pro-2 orchestraMobile % expo build:web       Web Bundling JavaScript [====                                     ] 10%Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

./node_modules/react-native-ui-lib/lib/components/Keyboard/index.js
Cannot find module: './KeyboardTracking/KeyboardTrackingView'. Make sure this package is installed.

You can install this package by running: npm install ./KeyboardTracking/KeyboardTrackingView.
(base) surfthomas@Surfs-MacBook-Pro-2 orchestraMobile % expo build:web         Failed to compile.
./node_modules/react-native-ui-lib/lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.js
Cannot find module: './CustomKeyboardView'. Make sure this package is installed.

You can install this package by running: npm install ./CustomKeyboardView.
(base) surfthomas@Surfs-MacBook-Pro-2 orchestraMobile % expo build:web
Failed to compile.

./node_modules/react-native-ui-lib/src/components/picker/NativePicker.js
Cannot find module: './PickerDialog'. Make sure this package is installed.

You can install this package by running: npm install ./PickerDialog.`

**Comment by M-i-k-e-l** [comment]
Hi @Surfield,
It looks like you're building for the web, we're not officially supporting web.
However you might be able to use specific components by importing them separately, for example:
```
import Card from 'react-native-ui-lib/card`;
```
