### ISSUE TITLE
PanDismissibleView alternative?

### ISSUE THREAD

**Issue by mehrdad-shokri** [wix/react-native-ui-lib#703]
The [docs](https://wix.github.io/react-native-ui-lib/docs/PanDismissibleView/) says PanDismissibleView is deprecated. What should be used for swipe to dismiss views?

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Is `PanDismissibleView` is actually deprecated? 
I believe we've un-deprecated it, no?

**Comment by M-i-k-e-l** [comment]
@mehrdad-shokri thank you for your input! Indeed, we decided to un-deprecate it and forgot the comment.

@ethanshar created the following PR to remove it: https://github.com/wix/react-native-ui-lib/pull/704

**Comment by mehrdad-shokri** [comment]
Great! thank you

**Comment by mehrdad-shokri** [comment]
Also, https://wix.github.io/react-native-ui-lib/docs/PanResponderView/ is 404
Is there a good example of using these components? Seems like they are used in conjunction with each other

**Comment by mehrdad-shokri** [comment]
Also homepage says this library supports rtl but the docs doesnt suggest how to. I gues with ``ThemeManager``?

**Comment by ethanshar** [comment]
Hey @mehrdad-shokri 
Here's the example screen for https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/PanResponderScreen.js
The entry for this component on the docs are broken, we will fix that. 

Regarding RTL. 
The library does support RTL. 
But turning RTL in your App is done using react-native API. 

```
import {I18nManager} from 'react-native';
I18nManager.forceRTL(true);
```

You can read more about RTL in general in RN docs
http://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps.html#maintaining-your-rtl-ready-app
