### ISSUE TITLE
Chip component

### ISSUE THREAD

**Issue by mehrdad-shokri** [wix/react-native-ui-lib#705]
Chip has become a common component among ui libraries, any plan to add it?

**Comment by mehrdad-shokri** [comment]
FABs are another component I'm missing :(

**Comment by ethanshar** [comment]
We do have a chip component in our App (the Wix app) and we plan to out source it eventually..
We don't have Fab on the other hand. 
You can technically create a `round` Button for a FAB

**Comment by ethanshar** [comment]
Hi @mehrdad-shokri 
A new `Chip` component will be available in our next release
