### ISSUE TITLE
Using indidividual components impact on app size and performance

### ISSUE THREAD

**Issue by mehrdad-shokri** [wix/react-native-ui-lib#706]
Sorry for opening multiple issues for questions.
I really love some components of your library but intend to use it alongside another UI library(react-native-paper)
Are you aware of the expected impact of using 2 UI libraries in one app regarding the app size and performance? 
For example, if I only use the PanResponderView components or ActionSheet, should the whole theme manager be bootstrapped?

**Comment by ethanshar** [comment]
Hey @mehrdad-shokri, 
That's a good question and I'm aware of this issue.
Adding to that my personal concern of forcing consumers installing too many peer dependencies when all they want is to use a simple button component.

My goal is to somehow publish submodules of this library so you can install smaller, specific parts relevant to your need. Similar to how `lodash` works. 

Unfortunately with react-native, with the way the metro bundler works you can't load the library without having all the relevant dependencies installed. 

I hope soon we'll come up with a solution for that. Ideas are welcomed (:

**Comment by ethanshar** [comment]
@mehrdad-shokri 
Next version we'll release **UILIb packages**.
You'll be able to import specific components

```
import View from 'react-native-ui-lib/view`;
import Text from 'react-native-ui-lib/text`
....
```

**Comment by mehrdad-shokri** [comment]
@ethanshar very good, but I chose to develop with Flutter I've found it very performant and convenient to develop an app with it!
