### ISSUE TITLE
Drawer not working in IOS React Native 0.61

### ISSUE THREAD

**Issue by MuhammadAbdullah555** [wix/react-native-ui-lib#710]
![drawer issue](https://user-images.githubusercontent.com/48431848/77059756-41cdc900-69f9-11ea-9221-edd0c109f272.JPG)
Drawer is not working in IOS , can someone please check 
Thanks

**Comment by MuhammadAbdullah555** [comment]
The error only occurs if using left and right items both in drawer , otherwise it works in IOS

**Comment by ethanshar** [comment]
Hey @MuhammadAbdullah555,
can you send add a code snippet of how you use `Drawer`

**Comment by MuhammadAbdullah555** [comment]
<Drawer
leftItem={{ icon: <TextRN>A</TextRN>, background: Colors.blue10, width: 100 }}
rightItems={[
  { text : "abdullah" , width : 100 , background: Colors.dark60 }
]}
style={{
  margin : 0
}}
itemsIconSize={30}
>
<CardRN >
  <TextRN>
    Open Drawer
</TextRN>
</CardRN>
</Drawer>

**Comment by ethanshar** [comment]
Hey @MuhammadAbdullah555 
I just ran the following snippet of code and the Drawer works as expected. 
This component is based on the native `react-native-gesture-handler` library. 
You will need to go into `ios` folder and install pods (`pod install`) and then re-build the app. 
```
        <Drawer
          leftItem={{icon: Assets.icons.check, background: Colors.blue10, width: 100}}
          rightItems={[{text: 'abdullah', width: 100, background: Colors.dark60}]}
          style={{
            margin: 0
          }}
          itemsIconSize={30}
        >
          <View height={80} bg-red40 padding-20>
            <Text text60>Item</Text>
          </View>
        </Drawer>
````

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1780255/77163964-e9113580-6ab7-11ea-80e8-17f454bd95c4.gif)

**Comment by ethanshar** [comment]
I assume this one resolved. Closing it.
