### ISSUE TITLE
Expo link is broken

### ISSUE THREAD

**Issue by adtm** [wix/react-native-ui-lib#713]
I tried to look at the app trough Expo but it showed 

```
Could not load exp://exp.host/@ethanshar/rnuilib
```

**Comment by ethanshar** [comment]
Hey @adtm, 
I just scanned the QR from here https://wix.github.io/react-native-ui-lib/
on both an Android and iOS device and it works. 
Do you the Expo app installed on your device?

**Comment by noelsp** [comment]
Hi @adtm and @ethanshar!
I have the same problem scanning the QR Code from here https://wix.github.io/react-native-ui-lib/
![IMG_23F0D07C6806-1](https://user-images.githubusercontent.com/5714538/77329042-2d8d1300-6cfc-11ea-894e-3f7c11e31316.jpeg)

My expo client version is: 2.14.1.107621
Supported SDKs: 33, 34, 35, 36

Thanks!

**Comment by adtm** [comment]
Yes, I have iOS Expo client, same as @noelsp

**Comment by ethanshar** [comment]
Checking.. I'll update

**Comment by ethanshar** [comment]
@noelsp @adtm 
Are you trying by any chance to load the App using iPhone? 
It appears to be some limitations with iOS devices.

**Comment by adtm** [comment]
I'm using an iPhone, for other Expo Apps it always worked fine.

**Comment by ethanshar** [comment]
TBH, I'm new to the whole Expo experience. 
I just read somewhere that there are limitations when trying to run Expo on iOS. 

When I try to open rnuilib app **with a different account** on my iPhone I get:
> Note that Expo Client on iOS can no longer open published projects that don't belong to the signed in user...

I will try to look more into it. 
If you are more familiar with Expo and have an idea on how to solve this please share here.

**Comment by ethanshar** [comment]
For now I created an expo snack based on the same demo app 
Please try it out
https://snack.expo.io/@ethanshar/rnuilib_snack

**Comment by murbanowicz** [comment]
> For now I created an expo snack based on the same demo app
> Please try it out
> https://snack.expo.io/@ethanshar/rnuilib_snack

It does not work anymore :(

**Comment by apoorvans** [comment]
I just tried to do this and got exactly this again: [https://github.com/wix/react-native-ui-lib/issues/713#issuecomment-602646185](https://github.com/wix/react-native-ui-lib/issues/713#issuecomment-602646185) like @noelsp a year back
