### ISSUE TITLE
Change color of Picker "Save" button and tick mark?

### ISSUE THREAD

**Issue by fosteruk** [wix/react-native-ui-lib#733]
Hi, 

Can anyone tell me how to change the color of the "Save" button and tick mark in the Picker component? Currently the default is light blue, I need them to be black.

I have searched the documentation, example code and also here in git-hub issues but I cant find any hint of a solution.

Thanks

**Comment by fosteruk** [comment]
OK. I worked it out.

`topBarProps={{doneButtonProps: {color: '#000000'}}}`

**Comment by fosteruk** [comment]
Actually thats only half a solution. I still dont know how to change the select item tick color.

**Comment by ethanshar** [comment]
Hey @fosteruk 
Can you explain. What do you mean the selected item tick color? 
(can u please attach a screenshot). 
Thanks.

**Comment by fosteruk** [comment]
Hey @ethanshar,

I mean the tick that indicates which item(s) has been selected.

<img width="252" alt="Screenshot 2020-04-05 at 21 48 59" src="https://user-images.githubusercontent.com/2025743/78509678-c2295380-7787-11ea-8298-d50e036c5ca0.png">

**Comment by ethanshar** [comment]
Hey @fosteruk 
A fix will be released in the next version (1-2 weeks) 
If you want to try it out, you can install our `snapshot` version

**Comment by ethanshar** [comment]
feature was released in v5.6.0
