### ISSUE TITLE
Set style of TextField placeholder/floatingPlaceholder

### ISSUE THREAD

**Issue by shierro** [wix/react-native-ui-lib#735]
Hi! Could you please advice us how to achieve what is on the title?
We've tried to return a function placeholder, set TextField theme via ThemeManager but placeholder doesn't inherit the style, particularly fontFamily.. We've been able to style the TextField, helperText, but not the placeholder

**Comment by ethanshar** [comment]
At the moment you can only pass color for placeholder using the `floatingPlaceholderColor` prop. 
I will mark this as a "feature request" and hopefully support it in our next version.

**Comment by shierro** [comment]
thanks @ethanshar , that was quick! are we expecting a new release soon?

**Comment by ethanshar** [comment]
We usually aim for a release every 2 weeks. (and we released a version last week). 
If u want to experiment with the new feature you can install `snapshot` version (just be aware it might contain issues)

**Comment by ethanshar** [comment]
feature was released in v5.6.0
