### ISSUE TITLE
Warning: AccessibilityInfo.fetch is deprecated, call Accessibility.isScreenReaderEnabled instead

### ISSUE THREAD

**Issue by Abisar** [wix/react-native-ui-lib#736]
Hello. I get this warning when I use the components:
`AccessibilityInfo.fetch is deprecated, call Accessibility.isScreenReaderEnabled instead`

Seems like in the previous update [they added a warning](https://reactnative.dev/blog/#deprecations) for it's usage.

**Comment by ethanshar** [comment]
Was already fixed, will be released in our next version
