### ISSUE TITLE
typescript definition for Switch

### ISSUE THREAD

**Issue by pietgk** [wix/react-native-ui-lib#741]
Is there a reason why the Switch.d.ts is not there?

**Comment by ethanshar** [comment]
Hey @pietgk 
Most of our typings files were created manually so it's possible some were missed. 
Having said that, we're in the process of migrating to Typescript which mean all components will auto generate d.ts files

**Comment by ethanshar** [comment]
Hey @pietgk ,
We release a HF (v5.6.1) for all missing components entries. 
Some still don't have full typings but at least you won't get any TS error.

**Comment by pietgk** [comment]
ok, thx 
is there a rough idea on when the move to typescript will be/planned-to-be completed?
this to get to the point that we can stop using //@ts-ignore's?

**Comment by ethanshar** [comment]
Hey @pietgk 
Unfortunately,  I don't have an exact estimation on when the typescript migration will be completed, But I can say it is one of our main goal in this quarter. 

Migrating an existing big library as uilib to TS is quite a challenge and through your feedbacks we keep improving it and fixing issues. 
If you have anything specific that still doesn't work (that requires you //@ts-ignore) please let us know so we can address it accordingly.

**Comment by pietgk** [comment]
Hey @ethanshar i will ask the team to keep sending out @ts-ignore cases as issues.
thx for the update
