### ISSUE TITLE
Typescript definitions error

### ISSUE THREAD

**Issue by victorvarenic** [wix/react-native-ui-lib#752]
I've started new rn project. There no specials config, or modules. I tried use react-native-ui-lib button but there simple button emit errors.
![Снимок экрана 2020-04-23 в 17 51 39](https://user-images.githubusercontent.com/45688357/80113884-882fbe00-858b-11ea-942e-4c0bdb7c1ec1.png)

**Comment by victorvarenic** [comment]
I tried reduce typescript from 3.8 to 3.7. It doesn't help

**Comment by victorvarenic** [comment]
tsconfig almost default 
{
  "compilerOptions": {
    "target": "esnext",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": ["es6"],                           /* Specify library files to be included in the compilation. */
    "allowJs": true,                          /* Allow javascript files to be compiled. */
    "jsx": "react-native",                    /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "removeComments": true,                   /* Do not emit comments to output. */
    "noEmit": true,                           /* Do not emit outputs. */
    "incremental": true,                      /* Enable incremental compilation */
    "isolatedModules": true,                  /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
    "moduleResolution": "node",               /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./",                          /* Base directory to resolve non-absolute module names. */
    "allowSyntheticDefaultImports": true,     /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "experimentalDecorators": true,         /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true           /* Enables experimental support for emitting type metadata for decorators. */
  },
  "exclude": [
    "node_modules", "babel.config.js", "metro.config.js", "jest.config.js"
  ]
}

**Comment by ethanshar** [comment]
Hey @victorvarenic 
Thank you for the feedback. 
We're in the process of migrating uilib completely to typescript till then we're facing some typescript issues. please keep updating us with issues. 
Having said that, this specific issue should be fixed in the upcoming version.
