### ISSUE TITLE
Add useNativeDriver.

### ISSUE THREAD

**Issue by Mulanir** [wix/react-native-ui-lib#753]
![image](https://user-images.githubusercontent.com/54661854/80213009-3184bb80-8641-11ea-9f0b-0257f15d5e90.png)
It would be great if you use native driver for animations.
In my case, this alert raised when using RadioButton.

**Comment by ethanshar** [comment]
Hey @Mulanir 
This fix will be released in our next version.
Thanks for letting us know 🙏
