### ISSUE TITLE
How can you make components responsive for different devices (different IPhone models, IPads, etc..)?

### ISSUE THREAD

**Issue by LukasZvikas** [wix/react-native-ui-lib#760]
Not a bug report, just a question. What would be your advice on making components adjust the sizes for different devices? Do you have any examples of that? Would appreciate suggestions, thanks.

**Comment by ethanshar** [comment]
Consider using the `ThemeManager` to create dynamic defaults to your components.
This way you can pass different values for each case. 

You can read more about `ThemeManager` [here](https://wix.github.io/react-native-ui-lib/foundation/theme-manager)

Here's a quick example
We had a use case where we wanted to limit the width of our `Dialog` when running on Tablets 
a simple solution for that will be

```
ThemeManager.setComponentTheme('Dialog', (props) => {
  if (Constants.isTablet) {
    return {
      width: 600
    };
  }
});
```
You can do many things with it, you can use other props for your calculations and maybe define some of your own 

 ```
ThemeManager.setComponentTheme('Dialog', (props) => {
  if (Constants.isTablet && props.beResponsive) {
    return {
      width: 600
    };
  }
});
```

**Comment by LukasZvikas** [comment]
Thanks for the reply and for the example! Do you think it would be a good solution to define sizes on the component level without using ThemeManager? For example, for a card component, just have different sizes specified based on the device type and do this for every component?

**Comment by ethanshar** [comment]
The idea of the ThemeManager is to give you control over your components in a more generic way. 
Defining specific size props is not relevant to each component and also will require different solution for each user. 
That's why we prefer to keep the components generic.
