### ISSUE TITLE
Support for newer RN versions? 

### ISSUE THREAD

**Issue by xenburn** [wix/react-native-ui-lib#773]
The docs say the latest supported is 59
It was commented on your native keyboard repo that it's being added to RNUI, so is that going to be part of a larger update?

**Comment by ethanshar** [comment]
Hey @xenburn 
Where in the docs exactly it says we support only rn59? 
RNUI supports latest RN version.

**Comment by xenburn** [comment]
https://github.com/wix/react-native-ui-lib/wiki
i didn't reread the main page. After upgrading react-native and reinstalling node_packages i  got the usual peer dependency warnings but also couldn't use <View> with the ubiquitous Super expression must either be null or a function. A bit of googling indicated it was likely a version mismatch issue. I'm pretty sure this is an error on my end and i'm closing the issue.
