### ISSUE TITLE
TextArea and TextField change of state not updating the value

### ISSUE THREAD

**Issue by vikasg603** [wix/react-native-ui-lib#786]
Changing the state of the TextArea or TextField not updating the value inside input.

The issue which causing this error may be this https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

As i saw the code, the thing is developer used a uncontrolled state inside component due to which we can't update it from parent view.

If possible resolve this issue.

**Comment by ethanshar** [comment]
Hey @vikasg603 
Can you describe the scenario you're trying to implement. 
Also if you can add a code snippet so we can investigate further..

**Comment by vikasg603** [comment]
Basically what i am trying to do is to reset the text input inside TextArea component.

The code is simple

Which i am doing using
this.setSate({
value : '')}

But issue is component is not responding to the change in the state.

Actually what i am able to find out is that your BaseInput class is using state inside the TextArea component ( as TextArea extended BaseInput )

And this causing the derived state issue.

**Comment by vikasg603** [comment]
**FileName** : /node_modules/react-native-ui-lib/src/components/inputs/BaseInput.js
https://pastebin.com/QVYc335T
You can see here, This solved my issue.

I have changed the dependency of all the functions from the state to props.
I am not sure the validation is working or not after this.

I am quite sure you can find out if any issue with my code :)

**Comment by ethanshar** [comment]
Hey @vikasg603 
Sorry for the late response. 

Changing an uncontrolled component to a controlled one might be risky move at this point and could introduce some unexpected breaking changes. 

I do agree we should aim to change this component to be a controlled component and I will examine it for our next major release. 

Till them I can recommend changing the `key` prop you pass to this component whenever u want to reset it (this is also the recommendation from react docs regarding uncontrolled components)

something like that could do the trick

```
export default class PlaygroundScreen extends Component {
  state = {
    value: '',
    textAreaKey: Date.now()
  };

  render() {
    return (
      <View flex padding-20>
        <TextArea
          key={this.state.textAreaKey}
          placeholder="Enter text"
          value={this.state.value}
          onChangeText={(value) => this.setState({value})}
        />

        <View center flex>
          <Text>{this.state.value}</Text>
          <Button label="Clear" onPress={() => this.setState({value: '', textAreaKey: Date.now()})}/>
        </View>
      </View>
    );
  }
}

```

**Comment by vikasg603** [comment]
Thanks for this, But my doubt is using key and then changing it, can cause the memory issue ?

**Comment by ethanshar** [comment]
Well technically what happens is that the component is being reconstructed. 
I would recommend doing it often, not necessarily because of memory issues but maybe performance issues. 
How many TextArea do you render in a screen? how often do you reset its value?

**Comment by vikasg603** [comment]
it's 5 text area actually

**Comment by FinnGu** [comment]
Hey :)

I am currently considering moving to this library, because I already use wix's react-native-navigation and am very pleased by the quality of your work! Do I understand this issue correctly, that the TextField and TextArea components of this library are uncontrolled components? This would be quite important for me as I already have trouble with another uncontrolled TextInput :/

**Comment by ethanshar** [comment]
At the moment TextField is an uncontrolled component. 

We do consider changing it to be controlled in the future, but it's not top priority at the moment and would require some time on our end because it will be a breaking change.

As suggested before, using the `key` prop can solve issues related to using uncontrolled components.

I still encourage you using this library just because it offers so many components and tools that can benefit greatly to you development process. (: 
You can always use react-native's original TextInput till we will come up with a solution that fits you.

**Comment by vikasg603** [comment]
it's true that UI lib is really good compare to all other UI libraries reason being simple that it has almost all the components which we need and also we don't need to write styles on each page without making any custom component.

**Comment by ethanshar** [comment]
Updated the docs

**Comment by ethanshar** [comment]
Hey, 
We recently released our next TextField under Incubator, that means it's still experimental. 
The component is completely controlled and even support some missing features. 

Please try it out and feel free to post some feedback before we officially replace it with our current TextField. 

you can use it like this: 
```
import {Incubator} from 'react-native-ui-lib`
const {TextField} = Incubator; 

return <TextField ... /> ;
```
