### ISSUE TITLE
Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from @react-native-community/picker instead of 'react-native'.

### ISSUE THREAD

**Issue by vikasg603** [wix/react-native-ui-lib#788]
Relative Path from where the warning is coming
path : /node_modules/react-native-ui-lib/lib/components/WheelPicker/index.js

Here for IOS you have used React Native core Picker which will be deprecated in the future release.

If possible replace it with @react-native-community/picker
(The warning is coming for IOS device only as for IOS only you have used Core Picker )

**Comment by ethanshar** [comment]
Hey @vikasg603, 
We aware of this warning. No worries we'll update the import of this component. 
For now you can ignore the warning.

**Comment by vikasg603** [comment]
Thanks for update
