### ISSUE TITLE
Badge on tabBar.Item not working

### ISSUE THREAD

**Issue by bcgarcia** [wix/react-native-ui-lib#800]
Hello. 

I'm using "react-native-ui-lib": "^3.25.0", and "react-native": "0.59.9". Reading the docs the (https://wix.github.io/react-native-ui-lib/docs/TabBar.Item/) tabBar.Item component is able to accept a badge. I'm using the example code (https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/BadgesScreen.js) but in my case badges are not displayed.

![image](https://user-images.githubusercontent.com/1266125/83531528-64965680-a4ed-11ea-8039-3d911c2baf52.png)

Thanks for the responses and for this awesome library.

**Comment by ethanshar** [comment]
Hey @bcgarcia 
You're using a very old version of react-native-ui-lib
Our latest version is 5.8.2
It might introduce breaking changes (since you have two major version back)
