### ISSUE TITLE
TypeError:Cannot call a class as a function

### ISSUE THREAD

**Issue by webMagicX** [wix/react-native-ui-lib#811]
react native 0.6.2
react-native-ui-lib 5.9.1

yarn add react-native-ui-lib
yarn add react-native-gesture-handler react-native-reanimated @react-native-community/blur @react-native-community/datetimepicker @react-native-community/netinfo
cd ios && pod install

The installation is successful, but an error is reported after startup
TypeError: Cannot call a class as a function

Toast({
    message: 'hello'
})

**Comment by ethanshar** [comment]
Hi @webMagicX, 

The components were meant to be rendered as JSX

```
<Toast visible message={'Message!'} />
```

**Comment by webMagicX** [comment]
Thank you!
