### ISSUE TITLE
Toast isn't working on Android

### ISSUE THREAD

**Issue by lucasfalcaoo** [wix/react-native-ui-lib#816]
Hey, folks! First of all thanks for the incredible lib! 

I'm having some issues with Toast component on Android (Samsung Galaxy A20). It just doesn't show up, even if I set the visible parameter hardcoded true. Could you please give some help?

This is a snippet of the code that I'm using Toast:

```
import { View, Text, Colors, Toast } from 'react-native-ui-lib

  return (
    <Toast visible backgroundColor={Colors.secondaryColor}>
      <Text center text70 white>
        Time to expire ticket:
      </Text>
      {loading ? (
        <View marginV-9>
          <ActivityIndicator color="white" size={18} />
        </View>
      ) : (
        <Text marginB-12 center text60 white>
          {formatSecsToFullTime(time)}
        </Text>
      )}
    </Toast>
  );

**Comment by ethanshar** [comment]
Hi @lucasfalcaojump 
It's a little difficult to read the snippet, can you please fix the formatting (use triple tick format instead of a single one)

**Comment by lucasfalcaojump** [comment]
@ethanshar my bad, I didn't know this Github trick to format code, but I dont think this snippet will help to solve the problem, is there any way to show you more info? The Toast on this device just doesn't show up (Samsung Galaxy A20)

**Comment by ethanshar** [comment]
HI @lucasfalcaojump, 
Did you try running your example on others Android devices or maybe Android emulator?
What about iOS? 
I'm curious if it's a specific device issue.. 

Also, can you please run our demo app and check if the Toast example screen works for you?
