### ISSUE TITLE
Toast, child component error?

### ISSUE THREAD

**Issue by webMagicX** [wix/react-native-ui-lib#817]
Hey, folks! First of all thanks for the incredible lib!
When I use `Toast`, I have the following questions. Can you see it for me?

react-native-ui-lib  5.9.1

`<Toast visible message={'Message!'} />`
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

`<Toast visible}><Text>Message!</Text></Toast>`
No error is reported, but some parameters cannot be used.

**Comment by ethanshar** [comment]
Hi @webMagicX 
This warning will be fixed in our next release

**Comment by webMagicX** [comment]
OK, thank you!
