### ISSUE TITLE
Typography combine styles

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-ui-lib#826]
Dear all,
I built typo with header and subtitle. However, I would like to use in many case as headline-bold or headline-italic, headline-bold-italic
I'm wondering that could we define header, italic, and bolder separately and then combine as "header-bold-italic" or not
We cannot define all cases because the combination will be so big
Best regards,

**Comment by ethanshar** [comment]
Hi @moonjava2005 
Not sure I completely understand your question. 
This is how we build our internal typography presets. 
https://github.com/wix/react-native-ui-lib/blob/master/src/style/typographyPresets.ts
I think it's similar to what you're asking

**Comment by moonjava2005** [comment]
> Hi @moonjava2005
> Not sure I completely understand your question.
> This is how we build our internal typography presets.
> https://github.com/wix/react-native-ui-lib/blob/master/src/style/typographyPresets.ts
> 
> I think it's similar to what you're asking
> For example we have text70, but also text70BO (for Bold), text70R ( for Regular), text70M (for Medium), etc..

Hi @ethanshar 
For example, we have text70 is
`myRegularStyle:{fontSize:30, lineHeight:40}`
Then, if we want to use 'myRegularStyle' as bold or italic, we have to define 
`myRegularStyle:{fontSize:30, lineHeight:40},myRegularBoldStyle:{fontSize:30, lineHeight:40, fontWeight:'bold'},myRegularItalicStyle:{fontSize:30, lineHeight:40, fontStyle:'italic'}`
And so on, we have to define to much
As my opinion, there anyway to use like this 
`<Text myRegularStyle bold/>`
or `<Text myRegularStyle bold italic/>`
We just define 2 more styles is `boldStyle:{fontWeight:'bold'}` and `italicStyle:{fontStyle:'italic'}`
That's my question

**Comment by ethanshar** [comment]
So basically what you need is us to support passing multiple typography modifiers and to merge them all together into one style. right?

**Comment by moonjava2005** [comment]
> So basically what you need is us to support passing multiple typography modifiers and to merge them all together into one style. right?

Yeap! We can do that for easier to combine typography styles
