### ISSUE TITLE
react-native-interactable requirement

### ISSUE THREAD

**Issue by birkir** [wix/react-native-ui-lib#83]
It seems that react-native-interactable is required.

When compiling for android in CI, everything breaks.

```bash
Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Could not list contents of '/home/travis/build/ueno-llc/react-native-starter/node_modules/react-native-interactable/{ios,android}'. Couldn't follow symbolic link.
```

When looking at the android setup, it is added in  `./android/settings.gradle` but has no project dependency in `./android/app/build.gradle`.

**Comment by birkir** [comment]
Seems to be issue with react-native-interactable itself.

**Comment by markhu** [comment]
Looking a little closer reveals that node_modules/react-native-interactable/ had a problem with assuming that `bash` was the default shell, so it tried a bash-specific shortcut. Sad thing that trying something clever to save just one line of a simple shell script, has caused problems for so many people. Hope this helps: https://github.com/wix/react-native-interactable/pull/209
