### ISSUE TITLE
Picker does not support mode MULTI with getItemValue

### ISSUE THREAD

**Issue by Epick362** [wix/react-native-ui-lib#848]
Picker multi-select doesn't seem to work when using custom selected items format. With one item selected, clicking on another one just deselects all items instead of "appending" to selection.

Is anyone else experiencing this issue?

**Comment by ethanshar** [comment]
Hi @Epick362 
It would be really helpful if you can add a code example. 

Thanks

**Comment by Epick362** [comment]
Yes, sorry for not including it in the first place @ethanshar 

Minimal replication demo:
```
 const [languages, setLanguages] = React.useState<string[]>([])
  const options = [
    {myLabel: 'JavaScript', myValue: 'js'},
    {myLabel: 'Java', myValue: 'java'},
    {myLabel: 'Python', myValue: 'python'},
    {myLabel: 'C++', myValue: 'c++', disabled: true},
    {myLabel: 'Perl', myValue: 'perl'},
  ]

<Picker
        placeholder="Favorite Language"
        value={languages}
        enableModalBlur={false}
        onChange={item => setLanguages(item)}
        style={{color: Colors.red20}}
        mode="MULTI"
        getItemValue={lang => lang.myValue}>
        {options.map(option => (
          <Picker.Item
            key={option.myValue}
            value={option}
            getItemLabel={lang => lang.myLabel}
            disabled={option.disabled}
          />
        ))}
      </Picker>
```

I might just be doing something wrong but I can't figure out what

**Comment by ethanshar** [comment]
Hi @Epick362, 
Once the fix will be merged you will need to pass the `getItemLabel` callback to the `Picker` component (instead of the `Picker.Item`). 
This should fix the issue.

**Comment by Epick362** [comment]
Thank you @ethanshar! I'm looking forward to release.

**Comment by braianj** [comment]
is this released?

**Comment by ethanshar** [comment]
@braianj Yes.
