### ISSUE TITLE
Does dialog have a zindex property?

### ISSUE THREAD

**Issue by webMagicX** [wix/react-native-ui-lib#849]
Hello! 
I want to pop up a `Loading` on the top of `Dialog`, but no matter how I set it, the `Dialog` level is the highest. Can I adjust the `zIndex` of `Dialog`?
Can you help me? thank you！

**Comment by ethanshar** [comment]
Hi @webMagicX 
The dialog component is being rendered on top of a react-native  [Modal](https://reactnative.dev/docs/modal). 
Therefor it will always be on top of the screen (and its content) that opened it. 

Maybe you can elaborate more on what you're trying to accomplish and we can offer an alternative solution.

**Comment by webMagicX** [comment]
I want to load the "loading" control on "dialog". For example, click OK to request the interface. In this process, I need the 'loading' effect.
How should this be done?
Thank you for your help.

**Comment by ethanshar** [comment]
It's a little difficult to envision how it should look. 
Do you have any reference or design I can see ?

**Comment by webMagicX** [comment]
Thank you for your warm reply, I think the design needs to be adjusted. 
Thank you!
