### ISSUE TITLE
Invariant Violation: requireNativeComponent: "HighlighterView" was not found in the UIManager.

### ISSUE THREAD

**Issue by sinafbd** [wix/react-native-ui-lib#852]
hi I am using "react-native-ui-lib": "^5.10.2" with expo sdk 38.
i want to use FeatureHighlight and it gives me the error: Invariant Violation: requireNativeComponent: "HighlighterView" was not found in the UIManager.

Is it possible to use this feature with expo?

**Comment by ethanshar** [comment]
Hi @sinafbd 
Expo doesn't include RNUILIB native modules and the `FeatureHighlight` component is based on a native module, therefore it won't work on an Expo environment.

**Comment by thisisadithk** [comment]
@ethanshar I'm using bare native project still I get this error when running ios. Works fine with android. What could be the solution to this issue?
