### ISSUE TITLE
can typography  support other components or other api support custom define modifiers?

### ISSUE THREAD

**Issue by morelearn1990** [wix/react-native-ui-lib#857]
can typography  support other components or other api support custom define modifiers?

**Comment by ethanshar** [comment]
Hi @morelearn1990 
Not sure I understand the question. What do you mean exactly?

**Comment by morelearn1990** [comment]
Next is what i want:
```
Typography.loadTypographies({
    border: { borderColor: "#aaa", borderWidth: 1, borderStyle: "solid" },
});
```
```
<View border></View>
<TouchableOpacity border></TouchableOpacity>
```
Typography.loadTypographies only support on `Text` components now.

**Comment by ethanshar** [comment]
I see what you mean, we don't support custom modifiers at the moment. 
And yes, Typography modifiers are meant to be used on Components that contain text (Text, Button, TextField, etc...)
