### ISSUE TITLE
Animated: `useNativeDriver` was not specified.

### ISSUE THREAD

**Issue by vikasg603** [wix/react-native-ui-lib#862]
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
AnimatedScanner.

On ./node_modules/react-native-ui-lib/src/components/animatedScanner/index.js I am getting error on Animated.timing about native driver issue.

If possible resolve it.

**Comment by ethanshar** [comment]
Fixed in v5.11.0
