### ISSUE TITLE
Not picked pre-filled value in Picker Component

### ISSUE THREAD

**Issue by gulsher7** [wix/react-native-ui-lib#868]
Hey Developer. I'm trying to show pre-selected value in Picker Component but its dosen't work. It shows empty Picker. So how can i show pre-selected value in Picker Component..?

![Screenshot 2020-07-27 at 8 07 07 PM](https://user-images.githubusercontent.com/56266123/88555011-da79f280-d044-11ea-920c-49cf3cb46916.png)

**Comment by ethanshar** [comment]
@gulsher7 
Do you mean to set an initial value to the picker?

**Comment by gulsher7** [comment]
yes

**Comment by gulsher7** [comment]
> @gulsher7
> Do you mean to set an initial value to the picker?

yes

**Comment by ethanshar** [comment]
@gulsher7 
What are you passing to the `value` prop? 
It should be in the format of an object `{value, label}`
