### ISSUE TITLE
Hot reload doesn't work

### ISSUE THREAD

**Issue by birkir** [wix/react-native-ui-lib#87]
It seems that HMR is not working when changing attributes on Views or Texts.

Is this a known issue?

**Comment by ethanshar** [comment]
@birkir are you using modifiers to style your Views/Texts ?

**Comment by ethanshar** [comment]
modifiers values are being loaded once at the component initialization. 
That's why hot reloading doesn't work for you.
I did this in order to avoid calculation of all modifiers on each render.
I guess I can add a prop to enable re-calculation of modifiers anytime it renders.

**Comment by birkir** [comment]
Is there any reason why it isn't evaluated in `componentWillReceiveProps`? Other than a large number of properties needed for shallow compare, it seems like the only sane solution.

```js
class Demo extends React.Component {

  state = {
    dark: false,
  };

  onPress = () => {
    this.setState({ dark: !this.state.dark });
  }

  // This will not work
  render() {
    const { dark } = this.state;
    return (
      <View bg-black={dark} bg-white={!dark}>
        <Button onPress={this.onPress}>
          Toggle dark mode
        </Button>
      </View>
    );
  }

  // Workaround (re-renders the whole tree)
  render() {
    const Light = props => (<View bg-white {...props} />);
    const Dark = props => (<View bg-black {...props} />);
    const { dark } = this.state;
    const BackgroundView = dark ? Dark : Light;
    return (
      <BackgroundView>
        <Button onPress={this.onPress}>
          Toggle dark mode
        </Button>
      </BackgroundView>
    );
  }
}
```

**Comment by Inbal-Tish** [comment]
Hi. Can we close this issue?

**Comment by LaszloDev** [comment]
Can we have some note in the readme about this? I experienced the same and was confused if whats the problem was.
