### ISSUE TITLE
Submit wireframe

### ISSUE THREAD

**Issue by anhtuank7c** [wix/react-native-ui-lib#879]
I think that we should share the wireframe design file through `Figma/Sketch/Adobe XD` that allowed the designer could develop more UI base on this one.

**Comment by ethanshar** [comment]
Hi @anhtuank7c 
I'm checking with our UX on exporting the wireframe and design. 
I'll update when I know more..

**Comment by anhtuank7c** [comment]
Is there any update @ethanshar

**Comment by ethanshar** [comment]
Hi @anhtuank7c 
There are plan to meet with legal team in our company and to check if releasing our UX design is possible. 
I will update when I know more.

**Comment by anhtuank7c** [comment]
@ethanshar Thank you a lot

**Comment by URVL** [comment]
Hi, the question is relevant, I am still waiting for an answer

**Comment by maraisr** [comment]
> Hi @anhtuank7c
> There are plan to meet with legal team in our company and to check if releasing our UX design is possible.
> I will update when I know more.

Do you know more?

**Comment by anhtuank7c** [comment]
That's enough I think.
Thanks @maraisr

**Comment by ninobc** [comment]
Any update regarding this topic would be greatly appreciated 🙏

**Comment by URVL** [comment]
@ethanshar Hi, anything new about this question?

**Comment by ethanshar** [comment]
Unfortunately no.
This is something handled by our UX group and at the moment it's not in my hands. 
I'll try to update when I have news.

**Comment by serezhaorlov** [comment]
@ethanshar

Hello! 
Is there any chances to get figma project?

It will be useful a lot

**Comment by anhtuank7c** [comment]
@serezhaorlov I don't remember where do I get this wireframe but I could share with you.
![Overview Image](https://user-images.githubusercontent.com/3163410/152273376-30d97909-d313-4281-9db5-a237002244bb.png)

Please click to the broken image below to download to your computer, then replace the `.png` extension by `.sketch` to revert it back to Sketch file. Use [Sketch](https://www.sketch.com/) to open it. (GitHub doesn't support .sketch file extension so I need to do a neat trick)

![makeapp-wireframe-kit-demo-singlayn sketch](https://user-images.githubusercontent.com/3163410/152273590-71006118-8da2-484e-a35c-a585f14de9a6.png)

**Comment by serezhaorlov** [comment]
@anhtuank7c thanks a lot!

**Comment by MaxInMoon** [comment]
The lack of Figma/Sketch/Adobe XD design is a high entry barrier.
We can't show a prototype to a customer to validate the UI..
Too bad

**Comment by danshou** [comment]
Is there any news about this?

It is clearly a problem not to be able to create UI in Figma/Sketch to validate concepts with real users. It would be amazing to have a Figma kit

**Comment by AndreasGalster2** [comment]
Very relevant. I'm evaluating RNUI right now... It really looks like a great library but there's not even an easy way to get an overview of all available components. For considering this to be used in a project, a designer/product manager needs to be able to examine the depth of components. Was hoping for a Figma file as well to do a wireframe and evaluate feasibility of the library.

**Comment by d3thomas** [comment]
@ethanshar would be much appreciated by frontend devs if you could make a design file through Figma/Sketch/Adobe XD. Would save a lot of time with the designer and allows us to visualise a more realistic design to our clients.

**Comment by ethanshar** [comment]
For now I'm sharing here 
https://www.figma.com/community/file/1379775092983284111/rnui-library

Soon I'll update our docs and readme
