### ISSUE TITLE
[5.12.2]TextField import problem

### ISSUE THREAD

**Issue by billel-boudchicha** [wix/react-native-ui-lib#881]
Updating RNUI to 5.12.2, struggling with the import of TextField.
none of these imports work,
`
import { TextField } from 'react-native-ui-lib/core';
import { TextField } from 'react-native-ui-lib/inputs';
import TextField  from 'react-native-ui-lib/textField';
`
Can anyone please help in this one
thank You

**Comment by ethanshar** [comment]
Hi @billel-boudchicha 
Sure, we'll take a look. 
Thanks for the feedback.

**Comment by ethanshar** [comment]
This will be released in v5.13.0
