### ISSUE TITLE
Your document cannot be opened. Can you fix it?

### ISSUE THREAD

**Issue by Jackie-Web** [wix/react-native-ui-lib#884]
Hello, the author
The document you provided could not be opened. Can you fix it?
The document address [](https://wix.github.io/react-native-ui-lib/)

**Comment by Jackie-Web** [comment]
[https://wix.github.io/react-native-ui-lib/](url)

**Comment by ethanshar** [comment]
it works perfectly fine for me (: 
https://wix.github.io/react-native-ui-lib/

The url you pasted is mapped to an empty url
