### ISSUE TITLE
Support icon as component instead of only image

### ISSUE THREAD

**Issue by thebergamo** [wix/react-native-ui-lib#895]
Hi,

First of all, after getting know this lib I fall in love, so cheers guys!

Would you be open to support passing icon in those components as component instead of supporting only images.

For example when we've the Chip component we would use it like this:

```javascript
import { Chip } from 'react-native-ui-lib';
import Icon from 'react-native-vector-icons/MaterialIcons';

export default (props) => 
<Chip label="3km" icon={<Icon name="map" />} />
```

I believe it's quite standard using `react-native-vector-icons`, so we could have a more connected ecosystem.

If you're open to have it as an option into those components, I would create a PR for it :)

**Comment by dhcmega** [comment]
Hi, is there any change to have this? thanks!

**Comment by ethanshar** [comment]
Added to our board

**Comment by lidord-wix** [comment]
Hey @thebergamo and @dhcmega,
We can add it to our `Chip` component, there are other components you would like to have this support in?

**Comment by thebergamo** [comment]
I believe all components that have option to pass a image could benefit from being able to pass a component to it :)

**Comment by dhcmega** [comment]
@lidord-wix hi! Out of the top of my head, I think I would use it as transparent back button for the header, regular buttons, lists and custom touchable buttons for the "home/desktop" of my app. Thanks!

**Comment by richardrobberse** [comment]
@lidord-wix @ethanshar I think I'm facing a similar issue - trying to pass an icon coming from `@expo/vector-icons` to the `rightIconSource` prop of the `Picker` component. Kind of expected the render function to work no matter where the icon is coming from? Any ideas?

**Comment by lidord-wix** [comment]
Hey @richardrobberse,
We're working on a new TextField component with `trailingAccessory` and `leadingAccessory` props that doing the functionality you described, this TextField will be used by our Picker component so you'll be able to use it there soon :)

**Comment by mlabrum** [comment]
TabBar.Item is another candidate for this.

I've even tried using the react-native-vector-icons getImageSource to pass the image directly to it
```
<TabBar.Item key={label} label={label} onPress={onPress} icon={Icon.getImageSourceSync("account-arrow-left", 20, "red")}/>
```

**Comment by lidord-wix** [comment]
@thebergamo, @dhcmega, @richardrobberse, @mlabrum,
I'm closing this issue since we added the required support to most of our main components.
If there's a specific need, please open an issue for that and we'll address it.

**Comment by ConnorLanglois** [comment]
Hi, can we get support for this for the Toast component "icon" prop?

**Comment by lidord-wix** [comment]
Hi @ConnorLanglois,
You can pass your custom content as the Toast children.
Please let me know if it doesn't work for you :)

**Comment by MLaidlawScott** [comment]
Hello. Firstly, thanks for this library and the docs and examples. Really enjoying using it.

I’m wondering if there is support or plans to add support for using icons from `@expo/vector-icons` in the iconSource prop of Button components.

Or, if it is possible to load specific icons using Assets.loadAssetGroup that would allow them to be used in iconSource. 

Thanks

**Comment by lidord-wix** [comment]
Hello @MLaidlawScott,
You can pass any component you wish as a child of our `<Button />` component, to have a custom button ([example](https://github.com/wix/react-native-ui-lib/blob/ac434d5096c6f04d09b5ed8d04bd05dd754281f8/demo/src/screens/componentScreens/ButtonsScreen.tsx#L327)). 
Also, you can see [here](https://github.com/wix/react-native-ui-lib/blob/ac434d5096c6f04d09b5ed8d04bd05dd754281f8/demo/src/configurations.js#L4) an example for how to use the loadAssetsGroup
