### ISSUE TITLE
Feature request - More theme customization

### ISSUE THREAD

**Issue by Dellybro** [wix/react-native-ui-lib#911]
I can't seem to change the color for errors on text fields.

**Comment by ethanshar** [comment]
@Inbal-Tish I already discussed with @Dellybro in on our discord channel. 
If I'm not wrong, he wants us to support coloring the error validation message with a custom color. 
I guess we can add a similar prop like the one we have for placeholder and title, where you can pass either a string or a map of colors.

**Comment by Inbal-Tish** [comment]
@ethanshar Sure, no problem.

**Comment by Inbal-Tish** [comment]
@ethanshar What is the use of a map of colors here? Is there another use for an error message? I thought about a string, like 'disabledColor' prop, since it serves just for error it needs only one color. What do you think?

**Comment by ethanshar** [comment]
Yea. that makes sense. let's have a single color..

**Comment by Inbal-Tish** [comment]
PR is ready: https://github.com/wix/react-native-ui-lib/pull/915
