### ISSUE TITLE
ThemeManager.setTheme() not working

### ISSUE THREAD

**Issue by fosteruk** [wix/react-native-ui-lib#933]
**Describe the bug**
ThemeManager.setTheme() does not appear to work.

**To Reproduce**
```
ThemeManager.setTheme({
  primaryColor: Colors.dark30
});
```

**Expected behavior**
The above code should change the primary color from blue to grey but the primary color remains blue

**Code snippet**
```
ThemeManager.setTheme({
  primaryColor: Colors.dark30
});
```

**Screenshots**
<img width="152" alt="Screenshot 2020-09-11 at 15 26 01" src="https://user-images.githubusercontent.com/2025743/92937652-820b8280-f443-11ea-8db9-8d9e94d27227.png">

**Device (please complete the following information):**
Android and iOS

**Comment by ethanshar** [comment]
Hi @fosteruk 
There are plans to deprecate `ThemeManager.setTheme`
Instead there's a way of setting component theme using `ThemeManager.setComponentTheme`

Having said that, there is still an issue specifically with the WheelPicker component that it doesn't support theme. 
This is something we'll have to fix first before you can use `ThemeManager.setComponentTheme`
