### ISSUE TITLE
Demo of List Item will show 404 not found page.

### ISSUE THREAD

**Issue by sta-vanger** [wix/react-native-ui-lib#934]
**Describe the bug**
A clear and concise description of what the issue with the docs is.
Demo of List Item will show 404 not found page.

**Component?**
Are there missing docs for a component? Which component? 
https://wix.github.io/react-native-ui-lib/docs/ListItem/

**Is there a general issue with the docs site?**

https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/listScreens/BasicListScreen.js

**Is there an issue with the Expo snack app?**
Yes, Expo will not load in my phone

**Comment by ethanshar** [comment]
Hi @sta-vanger, 
Link to example screen should be fixed now. 

Regarding Expo, 
Which device do you have? 
As far as I know, there are some issues with running expo app in iOS. 
Maybe consider running our expo-snack app 
https://snack.expo.io/@ethanshar/rnuilib_snack
