### ISSUE TITLE
StackAggregator - not updating size on changing stack component

### ISSUE THREAD

**Issue by bneigher** [wix/react-native-ui-lib#939]
**Describe the bug**
I believe this is a bug.  I have several dynamically sized components being shown inside the stack aggregator.  I've noticed that whatever size of the component is at the top of the stack, any changes to the stack items (collapsed) does not get taken into account when the stack is rendered.  Illustrated below:

**To Reproduce**
1. Have a stack with the first item being a height of 100
2. Change the contents of the stack on the next render so the height of the first item is 50
3. Observe the height is still for a component of 100 height

**Expected behavior**
It would be nice if the calculation for the card height can update

**Code snippet**
N/A

**Screenshots**
Observe I am changing dates which triggers the rerender, and thus the condition for the different size stack components
![Group 33](https://user-images.githubusercontent.com/4627728/93271744-a1731a00-f779-11ea-952c-16c69789dc8c.png)

**Device (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 12.7

**Additional context**
Love this component, and this library!!!! Go Wix

**Comment by Inbal-Tish** [comment]
@bneigher Hi. Try passing 'key' prop with the changing height.

**Comment by bneigher** [comment]
@Inbal-Tish What exactly do you mean?  I have the same method you guys put in your example code:

```
...
  renderItem = (item, index) => {
    return (
      <View key={index} style={{ overflow: 'visible' }}>
        {item}
      </View>
    );
  };

  render() {
    const cards = [<Component />, <Component2 />]
    return (
       <StackAggregator
              contentContainerStyle={{
                overflow: 'visible',
              }}
              containerStyle={{
                marginTop: 8,
                borderBottomColor: GRAY_SCALE.LIGHT,
                borderBottomWidth: 0.25,
                overflow: 'visible',
              }}
              itemBorderRadius={10}
              collapsed={true}
              onItemPress={index =>
                this.onItemPress(cards[index])
              }>
              {cards.map(this.renderItem)}
            </StackAggregator>
    )
  }
```

Which should be yielding essentially 2 children Views with keys set.

**Comment by bneigher** [comment]
I just tried for the sake of testing key changes to set a random uuid for the keys on each render, which doesn't fix the issue either.  I think the problem is reduced to timing / onLayout:

1. https://github.com/wix/react-native-ui-lib/blob/master/src/components/stackAggregator/index.js#L188
2. https://github.com/wix/react-native-ui-lib/blob/master/src/components/stackAggregator/index.js#L202-L203

I tried to modify the source to calculate onLayout every render, which will set firstItemHeight, but it didn't work.  Maybe there is a better way to calculate the first item height?

**Comment by bneigher** [comment]
@Inbal-Tish unrelated but a handy utility for use cases of responding to the aggregator state change https://github.com/wix/react-native-ui-lib/pull/942

**Comment by Inbal-Tish** [comment]
@bneigher Please see the example I made on the `test/StackAgraggaton_state_change` branch to see how changing content is affecting the height of the cards. Let me know if that can work for you.

**Comment by bneigher** [comment]
@Inbal-Tish I ended up using a consistently sized 1st element of the stack in my design to avoid this issue.. but I think adding the `key` to the stackaggregator component itself (changing the key whenever relevant for me) should work.  I was assuming you were talking about the keys of the child components

**Comment by Inbal-Tish** [comment]
Yes. I meant 'key' for the StackAggregator component, not the items.

**Comment by bneigher** [comment]
yea that suggestion works.  thanks! you can close this one
