### ISSUE TITLE
get target by TestID

### ISSUE THREAD

**Issue by ofirdagan** [wix/react-native-ui-lib#96]
Hey, this is an amazing feature and I would love to use it!
The thing is, I don't necessary have access to the ref pointer where my highlight logic is.
Can you add support to getTarget by testId or some other static prop?

Thanks!! <3
@inbalTish @ethanshar 

https://github.com/wix/react-native-ui-lib/blob/90f2622f70ef2e513f56d1fdfcf159b9d95ba988/demo/src/screens/componentScreens/FeatureHighlightScreen.js#L38

**Comment by inbalwix** [comment]
Hi.
I shared with you our UI-Lib requests sheet, so please write a request there so our product can assess and prioritize it.

Thanks,

Inbal Tish
Mobile developer @ OneApp
