### ISSUE TITLE
https://wix.github.io/react-native-ui-lib/docs/Checkbox

### ISSUE THREAD

**Issue by sinafbd** [wix/react-native-ui-lib#962]
**Describe the bug**
gif demo is not about checkbox

**Component?**
checkbox gif 

**Is there a general issue with the docs site?**
https://wix.github.io/react-native-ui-lib/docs/Checkbox

**Comment by mackbrowne** [comment]
This issue is still active

**Comment by ethanshar** [comment]
Fixed !
