### ISSUE TITLE
Forward context from functional component to ThemeManager.setComponentTheme

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [wix/react-native-ui-lib#964]
As of now, when using `setComponentTheme`, we have access to a component's props and context from:

```
ThemeManager.setComponentTheme('Button', (props, context) => {
// do stuff with context
}
```

However, the context is available only when the original component is a `React.Component` and not a functional one.

With a functional component, we use the `useContext` hook which does not communicate with the component itself, and the only solution to forward the context is by using props.
Eg.
```
import {Button} from 'react-native-ui-lib';

export default ({...props}) => {
  const myContext= useContext(ThemeContext);
  return <Button {...props} myContext={myContext} />;
};

```

It would be nice if the library could fully support functional components, as they are becoming the standard nowadays.

**Comment by ethanshar** [comment]
Hi @GabrielePrestifilippo 
sorry for the long time.
Can you please try something... try setting the component static contextType like this 
```
import {Button} from 'react-native-ui-lib';
const CustomContext = React.createContext({test: true});

Button.contextType = CustomContext;
```

Please let me know if it works
