### ISSUE TITLE
Support icon in text field

### ISSUE THREAD

**Issue by Hoopex** [wix/react-native-ui-lib#967]
Hey Any luck to see icon libraries support soon on text field ?

 Ps: i already thats in to do list

**Comment by ethanshar** [comment]
Hi @Hoopex 
In our new implementation of TextField (under `Incubator` at the moment) 
There's the `leadingAccessory` and `trailingAccessory` - there you can pass whatever you want. 
See docs here
https://wix.github.io/react-native-ui-lib/docs/Incubator.TextField/

**Comment by sovetski** [comment]
@ethanshar's url is 404, the new one is: https://wix.github.io/react-native-ui-lib/docs/components/form/TextField
