### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.nativeModules.KeyboardTrackingViewTempManager.KeyboardTrackingScrollBehaviourNone')

### ISSUE THREAD

**Issue by Roka20012** [wix/react-native-ui-lib#968]
### Info
- "@react-native-community/datetimepicker": "^3.0.3",
- "@react-native-community/netinfo": "^5.9.7",
- "@react-native-community/picker": "^1.8.0",
- "react-native-gesture-handler": "^1.6.1",
- "react-native-reanimated": "^1.8.0",
- "react-native-ui-lib": "^5.14.0",
- "react-dom": "^16.9.0",
- "react": "16.9.0",
- "react-native": "0.61.5",

### Image
![image](https://user-images.githubusercontent.com/32239452/95219190-c3ead700-07fd-11eb-8987-2e15d74ac123.png)

### Question

Does somebody have this issue or know how to fix it?

**Comment by ethanshar** [comment]
is that iOS?

**Comment by Roka20012** [comment]
Hey @ethanshar yeah it's iOS

**Comment by ethanshar** [comment]
@Roka20012 
Have you pod install? The keyboards components are native and require to pod install and rebuild the app
`cd ios && pod install && cd ..`

**Comment by M-i-k-e-l** [comment]
@ethanshar 
I managed to reproduce this issue when Pods are not installed, using: `import {KeyboardTrackingView} from 'react-native-ui-lib/keyboard';` in a new project. `cd ios && pod install && cd ..` did solve it.

@Roka20012 could you please verify?

**Comment by Roka20012** [comment]
@M-i-k-e-l @ethanshar thanks guys will check today
I have a feelings that I just didn't rebuild the app)
