### ISSUE TITLE
react-native-keyboard-input cannot work properly after fresh install

### ISSUE THREAD

**Issue by Godman-quake** [wix/react-native-ui-lib#969]
## Ask us any question

react-native-keyboard-input cannot work properly after fresh install in Android 5/7/9, but everything is fine when re-enter.

**Comment by Godman-quake** [comment]
> Hi @Godman-quake,
> I've created a new project, followed our [setup guide](https://wix.github.io/react-native-ui-lib/getting-started/setup) and created a demo screen that uses `KeyboardAccessoryView` and the it works after fresh install.
> Could you please provide a code example that does not work on fresh install?
> Edit: I assumed you meant `KeyboardAccessoryView` from `wix/react-native-ui-lib` and not actually `react-native-keyboard-input`.

Hi, M-i-k-e-l, my app used "react-native-keyboard-input": "^6.0.0", and now I update it to wix/react-native-ui-lib, and at least in Android 9, it works properly. Thank you very much!

**Comment by M-i-k-e-l** [comment]
You're welcome :)
