### ISSUE TITLE
DateTimePicker modal opens when another Modal is opened on Android

### ISSUE THREAD

**Issue by danilovq** [wix/react-native-ui-lib#971]
I have the DateTimePicker component and some another components which trigger the Modal component openning. When the DateTimePicker is opened and closed without changing the value, it appears again if another Modal is opened and closed.

**Steps to reproduce the behavior:**

1. DateTimePicker and Modal components on the one screen
2. Open DateTimePicker modal
3. Click on "Cancel"
4. Open & close another Modal
5. The DateTimePicker modal is visible
6. Change the date and click OK
7. Open & close another Modal
8. DateTimePicker modal is not visible

**Code snippet**
Here is an example Component:

```javascript
import React, {Component} from 'react';
import {Button, DateTimePicker, Modal, View} from 'react-native-ui-lib';

export default class Example extends Component {

    constructor(props) {
        super(props)
        this.state = {
            modalVisible: false,
            date: new Date(),
        };
    }

    renderModal() {
        return (
            <Modal visible={this.state.modalVisible}>
                <View flex center margin-20 bg-blue30 br20>
                    <Button white link label={"Close modal"} onPress={() => this.setState({modalVisible: false})}/>
                </View>
            </Modal>
        )
    }

    render() {
        return (
            <View flexG center>
                <DateTimePicker
                    containerStyle={{marginVertical: 20}}
                    title={'Date'}
                    placeholder={'Select a date'}
                    dateFormat={"DD.MM.YYYY"}
                    value={this.state.date}
                />
                <Button label={"Open modal"} onPress={() => this.setState({modalVisible: true})}/>
                {this.renderModal()}
            </View>
        );
    }
}
```

**Screenshots**

![datetimepicker_modal_bug](https://user-images.githubusercontent.com/7607026/95511795-60b19e00-09d1-11eb-827c-13f2e940f66c.gif)

**Device:**
 - physical devices and emulators
 - OS: Android

I investigated the problem and discovered that the source of the problem is in the following method:

https://github.com/wix/react-native-ui-lib/blob/7514e2e3587c2c2598837b411c7ea0d58d3c9813/src/components/dateTimePicker/index.js#L106

I think, it should be the following:

```javascript
handleChange = (event = {}, date) => {
    // NOTE: will be called on Android even when there was no actual change
    if (event.type !== 'dismissed' && date !== undefined) {
      this.chosenDate = date;

      if (Constants.isAndroid) {
        this.onDonePressed();
      }
    } else {
      this.toggleExpandableOverlay()
    }
  };
```
If this solution is feasable, then I can prepare the PR. Please let me know.

**Comment by ethanshar** [comment]
Hi @danilovq
Is this issue still relevant? 

It doesn't reproduce so I'm closing it.
Please feel free to reopen if still happens
