### ISSUE TITLE
DateTimePicker - update the value on the fly

### ISSUE THREAD

**Issue by danilovq** [wix/react-native-ui-lib#972]
I am not sure is it a bug or feature request, but I am trying to set DateTimePicker value depends on the my component state. It seems, that the DateTimePicker component ignores the value prop when it's already initialized.

Here is the code snippet:

```javascript
import React, {Component} from 'react';
import {Button, DateTimePicker, View} from 'react-native-ui-lib';

export default class Example extends Component {

    constructor(props) {
        super(props)
        this.state = {
            date: new Date(),
        };
    }

    render() {
        return (
            <View flexG center>
                <DateTimePicker
                    containerStyle={{marginVertical: 20}}
                    title={'Date'}
                    placeholder={'Select a date'}
                    dateFormat={"DD.MM.YYYY"}
                    value={this.state.date}
                />
                <Button label={"Set another value"} onPress={() => this.setState({date: new Date("2020-07-01T00:00:00")})}/>
            </View>
        );
    }
}
```

**Comment by Inbal-Tish** [comment]
@danilovq Yes. The 'value' prop is, as mentioned, the initial value. If you want to update it we your screen's state change you should pass the 'key' prop as well to get a new instance of the component.

**Comment by ethanshar** [comment]
@Inbal-Tish 
Maybe we should consider renaming the prop name to `initialValue` for `v6`

**Comment by ethanshar** [comment]
And the community component is controlled or uncontrolled?

**Comment by Inbal-Tish** [comment]
Controlled

**Comment by ethanshar** [comment]
Do you think it's possible to keep it controlled? 
Controlled considered best practice in general, we should aim for that for v6..

**Comment by ethanshar** [comment]
@Inbal-Tish 
This one has been resolved, right?

**Comment by Inbal-Tish** [comment]
Yes

**Comment by abbas-twocx** [comment]
how can I change the theme colour of icon of Datetimepicker RNUILIB,
