### ISSUE TITLE
Horizontal flatlist inside a carousel tab

### ISSUE THREAD

**Issue by jamesjara** [wix/react-native-ui-lib#973]
Hello guys,

We have an horizontal flatlist inside of a carousel tab, so when you try to swipe left/r , the handle will swipe the tab not the list.

What do you have to solve this problem, or any idea I could try to create a PR to support this feature, but not sure if you already have something or any idea about how to solve this issue.

thanks

**Comment by ethanshar** [comment]
We have nothing in mind. 
PRs are welcome (:
