### ISSUE TITLE
tabController doc issue

### ISSUE THREAD

**Issue by surethink** [wix/react-native-ui-lib#984]
**Describe the bug**
A clear and concise description of what the issue with the docs is.

lack of description about PageCarousel
lack of live example of tab page
the code example of tab controller is too complicated for me as a beginner, I spent 2 hours to read the doc and code example, but still don't know how to use tab page. It should have been a very simple thing:)

**Is there a general issue with the docs site?**
besides the live example, relevant code block is needed. the example should be simple,just to exemplify the component's attribute and method. it will be friendly to the people new to this library

This is an excellent library,It helps me a lot, thank you very much. 
 I hope the docs will be excellent too:)

**Comment by ethanshar** [comment]
Hi @surethink 
Thanks for the feedback. 
We always try to improve our docs and our example code. 

Showcasing a complex component (like the TabController) behaviors can be difficult sometime.
Anyway, for now, I added a note in the PageCarousel doc page that explains what are the steps into making it work with TabController. 
I hope you'll find it useful 
https://wix.github.io/react-native-ui-lib/docs/TabController.PageCarousel/
