### ISSUE TITLE
TextField error style

### ISSUE THREAD

**Issue by sinafbd** [wix/react-native-ui-lib#992]
**Which component?**
TextField 

**What is the new feature?**
please consider applying styles for Text Field's error messages. 
for example changing fontFamily for error messages.

**Code snippet**
something like errorStyles prop for TextFields

**Comment by ethanshar** [comment]
Hi @sinafbd 
I recommend start using our new TextField implementation. It's still experimental and its API might change, but it's pretty much in final stages. 
```
import {Incubator} from 'react-native-ui-lib'
const {TextField} = Incubator;

<TextField 
  placeholder="Enter text" 
  enableErrors 
  validationMessage="Error message" 
  validate="required" 
  validationMessageStyle={{color: 'red', fontFamily: 'Roboto'}}
/>

```

**Comment by AlphaJuliettOmega** [comment]
@ethanshar what is this 'incubator' documentation link?
Is that for a test branch?

**Comment by ethanshar** [comment]
Components that under Incubator are experimental and may change API till we officially release them. 
In our docs they are located under "Incubator"

**Comment by ethanshar** [comment]
This feature was added some time ago. 
The validation error message style can be controlled using the validationMessageStyle prop
